### ISSUE TITLE
"File contains data in an unknown format." when loading mp3 given a pathlib.Path

### ISSUE THREAD

**Issue by Luux** [librosa/librosa#1037] opened 2019-12-10 21:48 UTC
#### Description
When using librosa.load to load a mp3 file given a pathlib.Path, you'll get a "File contains data in an unknown format" error.  I tried installing ffmpeg over and over again before I realized it's definitely a bug within librosa.load in a specific constellation. It took some time before I realized how to reproduce that, but it's actually stupidly simple:

#### Steps/Code to Reproduce
```
import librosa
from pathlib import Path

# works
aaa = librosa.load('./test1_22050.mp3')
aaa = librosa.load('./test1_22050.wav')
aaa = librosa.load(Path('./test1_22050.wav'))

# doesn't work
aaa = librosa.load(Path('./test1_22050.mp3'))
```

Since a "normal" load (without pathlib.Path) falls back to audioread instead of PySoundFile according to the usual warning in case of mp3 files, I strongly suspect that this fallback just somehow fails when using pathlib.
Temporary workaround for users: just do
```
aaa = librosa.load(str(Path('./test1_22050.mp3')))
```
if your code utilizes pathlib.

#### Expected Results
It should just correctly load and process the given file even with pathlib.Path

#### Actual Results
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    aaa = librosa.load(Path('./test1_22050.mp3'))
  File "C:\Users\Luux\Miniconda3\envs\3.7\lib\site-packages\librosa\core\audio.py", line 149, in load
    six.reraise(*sys.exc_info())
  File "C:\Users\Luux\Miniconda3\envs\3.7\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "C:\Users\Luux\Miniconda3\envs\3.7\lib\site-packages\librosa\core\audio.py", line 129, in load
    with sf.SoundFile(path) as sf_desc:
  File "C:\Users\Luux\Miniconda3\envs\3.7\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\Luux\Miniconda3\envs\3.7\lib\site-packages\soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "C:\Users\Luux\Miniconda3\envs\3.7\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'test1_22050.mp3': File contains data in an unknown format.

#### Versions
Windows-10-10.0.18362-SP0
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
NumPy 1.17.4
SciPy 1.3.3
librosa 0.7.1

**Comment by lostanlen** [comment] 2019-12-10 22:12
This looks a lot like a duplicate of #1019, fixed by #1021 

Please try the latest version of librosa, including fix #1021, and tell us if the error persists.
We are soon going to release the next bugfix version of librosa (v0.7.2), in which `load` will support `pathlib.Path` objects as inputs.

**Comment by Luux** [comment] 2019-12-10 22:49
Thanks for the extremely fast reply!
Installing from the latest repo does indeed fix this. Sry for duplicate - I even did a quick search for duplicates, but I didn't scroll down *that* much ;)

**Closed** 2019-12-10 22:52 UTC
Labels: bug

**Comment by lostanlen** [comment] 2019-12-10 23:02
I'm glad it helped! Thank you for confirming that it was indeed a duplicate.
We will make sure to release v0.7.2 soon so that you can rely on the Anaconda distribution of librosa, for reproducibility.
