### ISSUE TITLE
multi-dimensional framing

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#944] opened 2019-08-10 23:30 UTC
#### Description
In machine listening applications, it is very common to train a classifier on short audio clips and then deploy it on full-duration audio recordings. In this case, what is necessary to do is to divide the long-duration spectrogram into time-frequency buffers, loop over these buffers, compute a prediction on each of them, and aggregate the predictions over time into a single time series.

Some examples:
* @jtcramer et al. Open-L3: https://github.com/marl/openl3
* @lostanlen et al. BirdVoxDetect: https://github.com/BirdVox/birdvoxdetect
* @rabitt et al. deep salience: https://github.com/rabitt/ismir2017-deepsalience
* dozens, possibly hundreds more among librosa users.

Currently, this is not possible in librosa. We have the cherished `librosa.util.frame` for monophonic audio, but nothing for matrices.

My current code implementation BirdVoxDetect is very opaque, and probably suboptimal, but works miraculously:

```python
        X_shape = (n_strides, clip_length, n_freqs)
        X_stride = (itemsize*n_freqs*stride_length, itemsize*n_freqs, itemsize)
        X_pcen = np.lib.stride_tricks.as_strided(
            np.ravel(np.copy(pcen).T),
            shape=X_shape,
            strides=X_stride,
            writeable=False)
        # Prepare for Keras training
        X_pcen = np.transpose(X_pcen, (0, 2, 1))[:, :, :, np.newaxis]
```

Writing this, with some help from @jongwook, accelerated BirdVoxDetect by an order of magnitude. This is what makes me think that this feature would be vital for machine listening applications of librosa. I would expect to call this with the following prototype:

```python
S_buffers = librosa.util.buffer(S=S, frame_length, hop_length)
```
where `S` is a matrix of size `(n_freqs, n_times)` and `S_buffer` a matrix of size `(n_freqs, frame_length, n_times/hop_length)`.

Doing it with the current implementation of `librosa.util.frame` would break numpy contiguity, and thus defeat the purpose of having a view-based in-place implementation.

Bonus points if it works on multivariate representations like HCQT or multiscale PCEN.

@ all: Let me know what you think!

#### Versions
librosa 0.7.0

**Comment by bmcfee** [comment] 2019-08-12 11:49
This would be great to have, and it's been on my mind a bit lately as well.

How does your implementation handle the underlying array ordering?

I'm a bit nervous about the `np.copy` in there -- if we're copying the array, doesn't that negate much of the benefit here?

**Comment by lostanlen** [comment] 2019-08-12 15:38
You're right. I should not have `np.copy`'d the array.

**Comment by bmcfee** [comment] 2019-08-15 20:34
I think this issue is actually a dupe of #916 (in the stretch goal given in the thread)

**Comment by bmcfee** [comment] 2019-08-15 22:42
I renamed this one, after doing a bit of hacking and realizing that it's not actually too difficult to support framing of multi-dimensional inputs, as long as the memory contiguity is right.

There are two cases to worry about: C-contiguous inputs (where strides decrease along the axes), and F-contiguous inputs (where strides increase along the axes).  Framing only works if the target "time-like" axis is the slowest-varying axis, eg, 0 for the C-contiguous case and -1 for the F-contiguous case.  For mainly historical reasons, librosa was designed for F-contiguous data, which is why we always have time-like axes come last.

At any rate, here's a quick prototype of F-contig multidimensional framing:

```python
def frame_F(x, frame_length, hop_length):
    
    axis = -1
    
    if not x.flags['F_CONTIGUOUS']:
        raise librosa.ParameterError('Input array is not F-contiguous')
    
    n_frames = 1 + (x.shape[axis] - frame_length) // hop_length
    
    shape = list(x.shape)[:-1]
    shape.extend([frame_length, n_frames])
    
    strides = np.asarray(x.strides)
    strides = list(strides) + [hop_length * np.prod(strides // x.itemsize) * x.itemsize]
    
    return np.lib.stride_tricks.as_strided(x, shape=shape, strides=strides)
```
The logic is pretty straightforward: the shape is changed by replacing the last axis (number of samples) by a pair of last axes corresponding to the frame length and the number of frames.  Similarly, the strides are extended by calculated by determining the amount of contiguous memory consumed by one "frame".

In the C-contiguous case, the logic is all the same, but the ordering of indices changes:
```python
def frame_C(x, frame_length, hop_length):
    
    axis = 0
    
    if not x.flags['C_CONTIGUOUS']:
        raise librosa.ParameterError('Input array is not C-contiguous')
    
    n_frames = 1 + (x.shape[axis] - frame_length) // hop_length
    
    shape = list(x.shape)[1:]
    shape.extend([n_frames, frame_length])
    
    strides = np.asarray(x.strides)
    strides = [hop_length * np.prod(strides // x.itemsize) * x.itemsize] + list(strides)
    
    return np.lib.stride_tricks.as_strided(x, shape=shape, strides=strides)
```

I've written these as two separate functions mainly for illustrative purposes.  These can be merged with a bit of branching logic to determine if the selected axis and input contiguity are compatible, and then behave accordingly.

The 1-dimensional input case is a bit special, because there are two ways to do it `(n_frames, frame_length)` vs `(frame_length, n_frames)`, and the input is always treated as `C_CONTIGUOUS` even though F is technically correct as well.  So the rule should be:

- if axis=0 and C-contiguous ==> good
- if axis=-1 and (C-contiguous or F-contiguous and 1-dimensional) ==> good
- else: fail

I think this can all be worked into an extension of the existing `util.frame` API without any backward-incompatible changes.

**Comment by lostanlen** [comment] 2019-08-15 22:46
Amazing! What's the backup plan if it fails on the part of the user? Call `frame` on `x.ascontiguousarray()` / `x.asfortranarray()`? Or `x.copy()`?
Could we include a `copy=False` kwarg which, if set to `True`, causes `frame` to never fail?

**Comment by bmcfee** [comment] 2019-08-15 22:47
> Call `frame` on `x.ascontiguousarray()` / `x.asfortranarray()`?

That'd be excellent, and is what's proposed (in spirit) in #916

**Comment by bmcfee** [comment] 2019-08-15 23:34
One more point about `copy`: should it always invoke a new copy?  Or should we allow framing-by-reference if the data and target axis are frame compatible?

If the latter, then `copy` is not a great name, since `np.ascontiguousarray` is a no-op if the array is already C-contiguous, so the result would be an in-place frame on the original data.

Maybe there's a nicer API for this?

**Comment by lostanlen** [comment] 2019-08-16 00:09
i guess that there are three kinds of behavior that the user might want:
(1) force no copy. error if framing is impossible. `OWNDATA: False` guaranteed
(2) no copy if possible, copy if needed. The value of output `OWNDATA` is not guaranteed. never error
(3) always copy so that the output has `OWNDATA: True` guaranteed. never error

**Comment by bmcfee** [comment] 2019-08-16 00:15
> (1) force no copy. error if framing is impossible. `OWNDATA: False` guaranteed

Current behavior; exception is raised in case of error.


> (2) no copy if possible, copy if needed. The value of output `OWNDATA` is not guaranteed. never error

Should this trigger a warning?  How does the user distinguish this from mode 3?


> (3) always copy so that the output has `OWNDATA: True` guaranteed. never error

I guess this should definitely not warn either?

**Comment by lostanlen** [comment] 2019-08-16 01:40
mode (2) means that `frame` _tries_ to memory-efficient, and guarantees to not fail. I don't think a warning is necessary. If the user wants a warning, they can always bake their own using modes (1) and (3), like so:

```python
try:
    x_frames = librosa.util.frame(x, frame_length, hop_length, mode='1') # no copy guaranteed
except RuntimeError as e:
    warnings.warn('Zut alors! Copying the data')
    x_frames = librosa.util.frame(x, frame_length, hop_length, mode='3') # copy guaranteed
```

**Closed** 2019-08-18 11:39 UTC
Labels: enhancement, functionality
