### ISSUE TITLE
librosa.feature.rms inconsistency - y vs S

### ISSUE THREAD

**Issue by onkyo14taro** [librosa/librosa#1040] opened 2019-12-13 15:38 UTC
#### Description

When calling `librosa.feature.rms`, the result using a wave `y` and the result using the spectrogram `S` are different.  
This is because the algorithm is not correctly implemented to satisfy the Parseval's equation.  

![texclip20191213224740](https://user-images.githubusercontent.com/15100931/70804763-a1b14400-1dfa-11ea-90f6-4a4051d84a13.png)

Specifically, the direct current bin `S[0]` (and only if `n_fft` is odd, the sr/2 bin `S[-1]`) has twice as much influence as the other bins.

#### Steps/Code to Reproduce

```python
import numpy as np
import librosa

# set paramters
np.random.seed(0)
frame_length = 2048
hop_length = 512
center = True

# make a wave and its spectrogram
y = np.random.rand(3000)  # wave, DC component is about 0.5 because the range of np.random.rand is [0, 1)
S = librosa.magphase(librosa.stft(y,  # spectrogram
        n_fft=frame_length,
        hop_length=hop_length,
        window=np.ones,
        center=center))[0]

# calculate RMS
rms1 = librosa.feature.rms(y=y, frame_length=frame_length, hop_length=hop_length, center=center)
rms2 = librosa.feature.rms(S=S, frame_length=frame_length, hop_length=hop_length, center=center)
print(rms1)
print(rms2)
print(np.allclose(rms1, rms2))
```

#### Expected Results

`rms1` and `rms2` are almost the same.

#### Actual Results

```
[[0.57401353 0.58105711 0.58252662 0.58571533 0.58668334 0.58252178]]
[[0.75760764 0.76713306 0.76892614 0.7742523  0.77579546 0.77086043]]
False
```

#### Versions

Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.3 (default, May 28 2019, 02:11:32) 
[Clang 10.0.1 (clang-1001.0.46.3)]
NumPy 1.17.4
SciPy 1.3.3
librosa 0.7.1

**Comment by lostanlen** [comment] 2019-12-13 21:22
Hello @onkyo14taro, thank you for raising this. 
This issue looks like an exact duplicate of #978 (closed by #979)
Can you explain why #978 did not solve the problem?

**Comment by bmcfee** [comment] 2019-12-14 00:04
We do have an integration test that verifies scaling is preserved here: https://github.com/librosa/librosa/blob/master/tests/test_features.py#L414-L442 .. i wonder why our tests pass but this example fails?

**Comment by lostanlen** [comment] 2019-12-14 00:24
@bmcfee one explanation could be the DC component in `np.rand`, which is nonnegative

**Comment by onkyo14taro** [comment] 2019-12-14 05:59
## The reason of inconsistency

I'm sorry, but I can't explain it well in words.
However, I think the formulas will reveal the reason for the inconsistency.

### Case 1: `n_fft = frame_length = N = 2M` (even number)

#### Case 1-1: Given `y`
![image](https://user-images.githubusercontent.com/15100931/70844198-fe574200-1e80-11ea-9b63-d5b77d03aed4.png)

#### Case 1-2: Given `S` (before implementation)
![image](https://user-images.githubusercontent.com/15100931/70844241-aff67300-1e81-11ea-91c7-fcda56cb7246.png)

#### Case 1-3: Given `S` (my implementation)
![image](https://user-images.githubusercontent.com/15100931/70844256-d3212280-1e81-11ea-8653-3243fe676d8c.png)

### Case 2: `n_fft = frame_length = N = 2M+1` (odd number)

#### Case 2-1: Given `y`
![image](https://user-images.githubusercontent.com/15100931/70844263-f6e46880-1e81-11ea-9606-6e9e9078fd43.png)

#### Case 2-2: Given `S` (before implementation)
![image](https://user-images.githubusercontent.com/15100931/70844270-124f7380-1e82-11ea-962e-59756f824e20.png)

#### Case 2-3: Given `S` (my implementation)
![image](https://user-images.githubusercontent.com/15100931/70844283-272c0700-1e82-11ea-8f46-f1cf2cdfc9e9.png)

**Comment by bmcfee** [comment] 2019-12-18 18:30
> @bmcfee one explanation could be the DC component in `np.rand`, which is nonnegative

I don't see how that would change things.

If the idea is that our calculation is wrong for even- or odd-length frames, I don't see how that would apply since all of the test cases we have are even-length frames.

I think I do follow the derviation above though, and I see how averaging and then rescaling could get us into trouble.

**Comment by onkyo14taro** [comment] 2019-12-20 02:09
There are two causes for calculation errors in the previous implementation (correct vs. previous):

1. Constant for averaging
   - if `frame_length` is even, 1/(2M)^2 vs. 1/(4M(M+1))
   - if `frame_length` is odd, 1/(2M+1)^2 vs. 1/(4M(M+1))
2. The bias of specific terms
   - if `frame_length` is even, none vs. |S[0]|^2 + |S[M]|^2
   - if `frame_length` is odd, none vs. |S[0]|^2

The larger `frame_length` (i.e., `n_fft`) is, the smaller the influence of these error factors is.
However, if the value of `frame_length` is small or the DC component (i.e., |S[0]|^2) is relatively large, the calculation error cannot be ignored.

I guess that the reason why the previous implementation passed the previous test is as follows.
- `frame_length` was large enough to ignore the calculation error.
- The previous test code only has been using live recorded audio.
  When recording sound, it is thought that the influence of the DC component is reduced due to the performance of the microphone and the effect of the high-pass filter.
  By nature, the DC component of the audio waveform is small.
  However, when a wave with a large DC component is used, the previous code produces a large calculation error.

**Closed** 2019-12-27 15:56 UTC
Labels: bug
