### ISSUE TITLE
Unhelpful error message when the `duration` parameter of `librosa.load` is invalid

### ISSUE THREAD

**Issue by tasercake** [librosa/librosa#995] opened 2019-09-20 19:35 UTC
#### Description
Trying to load file formats using `audioread` with bad parameters passed to `librosa.load()` can yield confusing error messages

#### Steps/Code to Reproduce
1. Load a file format that's unsupported by `soundfile` (mp3, for instance).
2. Pass an invalid value as the `duration` parameter of `librosa.load()`:
```python
audio, sr = librosa.load('file.mp3', duration="4")  # Note that `duration` is a string
```

#### Expected Results
The file is either loaded as expected (if the parameter can be cast to a valid form), or I get a more descriptive error message about the bad parameter.

#### Actual Results
Running the above code to load an mp3 file yields the following unhelpful, confusing error message:
```
File "d:\programdata\anaconda3\lib\site-packages\librosa\core\audio.py", line 142, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "d:\programdata\anaconda3\lib\site-packages\librosa\core\audio.py", line 173, in __audioread_load
    s_end = s_start + (int(np.round(sr_native * duration))
  File "d:\programdata\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 3382, in round_
    return around(a, decimals=decimals, out=out)
  File "d:\programdata\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 3007, in around
    return _wrapfunc(a, 'round', decimals=decimals, out=out)
  File "d:\programdata\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "d:\programdata\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: ufunc 'rint' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
#### Versions
```
>>> import platform; print(platform.platform())
Windows-10-10.0.18362-SP0
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.7.0
```

**Comment by konoikon** [comment] 2019-09-21 04:59
Please, see my comment at #996

**Comment by bmcfee** [comment] 2019-09-21 14:30
I'm going to close this out as redundant with #996, but thanks for reporting it.

For the record, I don't think we should support string types as duration inputs.  The documentation does explicitly say `float`, so the issue is just that we don't strictly force it in the code.

**Closed by bmcfee** 2019-09-21 14:30 UTC
