### ISSUE TITLE
DOCS: Page for 'amplitude to db' in 0.6.1 does not exist, but shows on google search

### ISSUE THREAD

**Issue by Rubix982** [librosa/librosa#1230] opened 2020-08-25 15:15 UTC
**Describe the bug**

A link to `librosa.core.amplitude_to_db — librosa 0.6.1 documentation` can be seen on google search when searching for `librosa amplitude to db`, but going to the link leads to a 404.

![image](https://user-images.githubusercontent.com/41635766/91192595-8b8caf00-e70f-11ea-8c75-75e762d1cb3f.png)

![image](https://user-images.githubusercontent.com/41635766/91192617-95aead80-e70f-11ea-9aa6-774b12c19e78.png)

**To Reproduce**

Visit https://librosa.org/librosa/0.6.1/generated/librosa.core.amplitude_to_db.html .

**Expected behavior**

A web page for the docs to open

**Screenshots**

Added above

**Software versions***

Not related to code, but docs

**Additional context**
Nope. That's it.

**Comment by bmcfee** [comment] 2020-08-25 15:17
The doc page does exist; google's index is out of date.  I've requested that they recrawl the site, but no telling when it will happen.

Duplicate of #1215

**Closed by bmcfee** 2020-08-25 15:17 UTC
