### ISSUE TITLE
Stream doesn't work with piped input

### ISSUE THREAD

**Issue by hpx7** [librosa/librosa#1049] opened 2020-01-05 01:49 UTC
Repro:
```
import subprocess
import librosa

sp = subprocess.Popen(
    ['ffmpeg', '-i', 'test.mp3', '-f', 'wav', '-'],
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

stream = librosa.stream(sp.stdout.fileno(), block_length=16, frame_length=4096, hop_length=2048)
next(stream)
```

Stacktrace:
```
  File "/usr/local/lib/python3.7/site-packages/librosa/core/audio.py", line 361, in stream
    sr = sf.info(path).samplerate
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 436, in info
    return _SoundFileInfo(file, verbose)
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 383, in __init__
    with SoundFile(file) as f:
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 627, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 1182, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 1355, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 4: File contains data in an unknown format.
```

One fix would be to optionally take `sr` as input from the user

Related issue: https://github.com/bastibe/SoundFile/issues/141

**Comment by bmcfee** [comment] 2020-01-05 15:39
I think this issue is out of scope for us.  The problem is entirely down to soundfile not handling pipes, and librosa's stream will only work with what soundfile supports.



> One fix would be to optionally take `sr` as input from the user

I don't want to add that to the API for stream.  It would be confusing to have the `sr` parameter here, but have it behave quite differently than in `load` (where it triggers a sample rate conversion).

**Closed** 2020-05-29 14:40 UTC
Labels: Upstream/dependency bug
