### ISSUE TITLE
beat_track() behaves quite differently btw 0.8.1 and 0.9.0/0.10.x .

### ISSUE THREAD

**Issue by raymond-dms** [librosa/librosa#1691] opened 2023-03-20 23:42 UTC
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!
Checked and did not find related issues filed before.

**Describe the bug**
beat_track() behaves quite differently btw 0.8.1 and 0.9.0/0.10.x .

**Example:**

(run in notebook on colab)
!pip install numpy==1.23.5

!pip install librosa==0.8.1
#!pip install librosa==0.9.0
#!pip install librosa==0.10.0

##restart runtime/reset kernel after pip

import librosa
import numpy as np

print("librosa : ", librosa.__version__)
print("numpy : ", np.__version__)

array1=np.load('../array_1.npy', allow_pickle=False)
array2=np.load('../array_2.npy', allow_pickle=False)

sr=44100
tempo1, beats1= librosa.beat.beat_track(y=array1, sr=sr)
tempo2, beats2= librosa.beat.beat_track(y=array2, sr=sr)
print(tempo1, tempo2)

**Expected behavior**
librosa :  0.10.0
numpy :  1.23.5
0 120.18531976744185

===========================================

librosa :  0.8.1
numpy :  1.23.5
129.19921875 129.19921875

**Software versions***

iLinux-5.10.147+-x86_64-with-glibc2.31
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
NumPy 1.23.5
SciPy 1.10.1
librosa 0.10.0
INSTALLED VERSIONS
------------------
python: 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]

librosa: 0.10.0

audioread: 3.0.0
numpy: 1.23.5
scipy: 1.10.1
sklearn: 1.2.2
joblib: 1.1.1
decorator: 4.4.2
numba: 0.56.4
soundfile: 0.12.1
pooch: v1.7.0
soxr: 0.3.4
typing_extensions: installed, no version number available
lazy_loader: installed, no version number available
msgpack: 1.0.5

======================================

Linux-5.10.147+-x86_64-with-glibc2.31
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
NumPy 1.23.5
SciPy 1.10.1
librosa 0.8.1
INSTALLED VERSIONS
------------------
python: 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]

librosa: 0.8.1

audioread: 3.0.0
numpy: 1.23.5
scipy: 1.10.1
sklearn: 1.2.2
joblib: 1.1.1
decorator: 4.4.2
soundfile: 0.12.1
resampy: 0.4.2
numba: 0.56.4

numpydoc: None
sphinx: 3.5.4
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 3.6.4
pytest-mpl: None
pytest-cov: None
matplotlib: 3.7.1
presets: None

```
-->

**Additional context**
I ran everything 2 times, each with a different Librosa version, got 2 corresponding outputs (with confirmed Lib's version), also 2 outputs of python snippet to show software versions. Each pair of two outputs is separated by "==================". Two .npy files used in example are in attached array_1_2.zip. 
[array_1_2.zip](https://github.com/librosa/librosa/files/11023825/array_1_2.zip)

**Comment by bmcfee** [comment] 2023-03-21 01:20
Without having looked at your specific data, there are two changes documented in the changelog that might be relevant here:

1. 0.10 years a different sample rate conversion library by default, so the audio data will be slightly different
2. 0.9.0 changed the default frame padding mode for spectrograms from 'reflect' to 'zeros', so the features will be slightly different at the boundaries of the signal.

I don't think either is much to worry about, but should be easy enough to verify by overriding the default values to be consistent across both versions when comparing results.

**Comment by raymond-dms** [comment] 2023-03-21 05:46
Hi bmcfee, 

thanks for your reply. I checked document of 0.8.1 & 0.10.0 for beat_track(), they have identical default values : 
0.10.0
librosa.beat.beat_track(*, y=None, sr=22050, onset_envelope=None, hop_length=512, start_bpm=120.0, tightness=100, trim=True, bpm=None, prior=None, units='frames')

0.8.1
librosa.beat.beat_track(	 y=None, sr=22050, onset_envelope=None, hop_length=512, start_bpm=120.0, tightness=100, trim=True, bpm=None, prior=None, units='frames')

I did not see any padding or sampling rate conversion selection here. also i used same code w/ same sampling rate specified for both versions of librosa, and this is the only librosa function i called. are there other places i need to modify?

I also confirmed that, although 0.8.1's & 0.10.0's beat_track() produced very different outputs as above (129 vs 0), their similar counterpart of tempo() : 
0.10.0 : tempo_see1= librosa.feature.rhythm.tempo(y=array1, sr=sr)
0.8.1 :   tempo_see1= librosa.beat.tempo(y=array1, sr=sr)
produce identical results of 129.2 for both .npy files, so padding or resampling seem not affecting results on the tempo() front. 

Thanks again.

**Comment by raymond-dms** [comment] 2023-03-21 17:06
Hi bmcfee, 

playing with beat_track(), i had another interesting observation :

using 0.10.0, running first array_1.npy as input, it failed to find any beat, therefore outputs 0, as we've already seen. I then ran : 
onset_env = librosa.onset.onset_strength(y=array1, sr=sr,
                                         aggregate=np.median)

and plot it, found it to be all 0's in this onset_env[8681] array (so also failed to find anything).   I then set all elements in this array to !=0, but == 1e-16 instead, and ran : 

tempo1, beats1= librosa.beat.beat_track(y=array1, sr=sr, onset_envelope=onset_env)

this time it surprisingly can find some beats @ 123 (though not quite 129)

a similar run of 0.8.1's onset_strength() shows a heathy onset map , as shown in attached png. 

![ver_0_8_1_onset](https://user-images.githubusercontent.com/63673218/226684745-3fa4a6ac-f9e6-4057-81eb-44c58cdbf5b1.png)

I'm not sure if the failed onset detection leads to failed beat_track(), just something i observed. Thanks.

**Comment by bmcfee** [comment] 2023-03-22 16:23
> I'm not sure if the failed onset detection leads to failed beat_track(), just something i observed. Thanks.

Yes, that would definitely do it.

I loaded in your signals and exported them back as wavs, and noticed that they're band-limited at 1KHz.  My hunch is that this is the root cause of the empty onset envelope: if more than half of the mel frequencies have zero energy, then `aggregate=np.median` (default for beat tracking) will always produce a 0.  With the default parameter setup, 1KHz is around index 39 out of 128, so that would definitely produce this behavior.  If you switch to `aggregate=np.mean` you should see behavior closer to what you expect here.

As to why this is showing up in 0.9+ and not 0.8.1, i expect it's issue #1361 (fixed in 0.9.0).  In 0.8.1, the default fmax when computing onset strength was 11025, independent of the actual sampling rate.  In 0.9, it was set to Nyquist (sr/2).  If using the default sampling rate of 22050, there would be no difference, but if you're using sr=44100, then you'll see different behavior from 0.8.1 to 0.9 and above.



> I did not see any padding or sampling rate conversion selection here. also i used same code w/ same sampling rate specified for both versions of librosa, and this is the only librosa function i called. are there other places i need to modify?

Sampling rate conversion would happen on load, which is maybe not an issue if you already have the audio buffers in numpy arrays.

Padding parameters would be exposed in the computation of stft, melspectrogram, or onset strength.  It is not exposed from the top-level call at the beat tracker, but you can get the same behavior by computing the onset strength directly with the parameters you want.

That said, I think the above two issues are not the cause of the behavior you're seeing, though they will subtly influence beat tracker output.

If you want totally consistent behavior between 0.8.1 and the current release, I would suggest to compute the onset strength envelope directly with `fmax` fully specified, and then use that as input to the beat tracker instead of the audio buffer.

**Comment by bmcfee** [comment] 2023-03-23 17:23
Slight correction to the above: the band limit for your signals is around 2K, not 1K (I had saved with the wrong sampling rate!).  However, the rest of what I said still applies, and I'm quite confident that this is the source of the problem:

```python
In [7]: freqs = librosa.mel_frequencies(fmax=11025)

In [8]: np.searchsorted(freqs, 2000)
Out[8]: 64

In [9]: freqs = librosa.mel_frequencies(fmax=22050)

In [10]: np.searchsorted(freqs, 2000)
Out[10]: 54
```

For the first case, analogous to 0.8.1, it's 2K lands right in the middle (64 of 128 bins), so it's possible for median aggregation to produce a non-zero output.  In the second case, analogous to 0.9, all bins above 54 have zero energy, and this dominates the median calculation regardless of what's happening in the lower bands.

So I think this is all correct and intended behavior that just happens to be bad for the specific signals that you're analyzing.  The fact that it appeared to work in 0.8.1 was a bug, but you can get it to work by explicitly setting fmax=11025 when calculating your mel spectrogram / onset strength envelope.  (Changing to mean aggregation will also work, but give you a different onset envelope.)

**Comment by raymond-dms** [comment] 2023-03-23 20:20
Thank you, bmcfee, for your detailed insights and kind suggestions. I've tried your suggestions on some examples which sometimes show differences. (attached please find array3.npy). Is this the right way to inject fmax=11025?

0.10.0

--------------------------------------------------------------------

array3=np.load("array3.npy", allow_pickle=False)

onset_env = librosa.onset.onset_strength(y=array3, fmax=11025)  or 
onset_env = librosa.onset.onset_strength(y=array3, sr=22050)

out, beats1 = librosa.beat.beat_track(y=array3, onset_envelope=onset_env, sr=44100)  -> got 120.2

out, beats1 = librosa.beat.beat_track(y=array3, onset_envelope=onset_env, sr=22050) ==
out, beats1 = librosa.beat.beat_track(y=array3, onset_envelope=onset_env) -> 99.4

 out, beats1 = librosa.beat.beat_track(y=array3, onset_envelope=onset_env, sr=11025)  -> 117.5

out, beats1 = librosa.beat.beat_track(y=array3)  -> 0 for similar reason as before

-----------------------------------------------------------------------

I'm trying to find a way to make the result matching that of 0.8.1, which is :
0.8.1

------------------------------------------------------------------------

array3=np.load("array3.npy", allow_pickle=False)

out, beats1 = librosa.beat.beat_track(y=array3, sr=44100);  --> got 35.39

------------------------------------------------------------------------

Thanks. 
[array3.zip](https://github.com/librosa/librosa/files/11055712/array3.zip)

**Comment by raymond-dms** [comment] 2023-03-23 20:36
also, just saw in docs..does 0.8.1 & 0.10.0's onset_strength() both default to np.mean? so the results i showed above for 0.10.0 are using default (np.mean). If i set it to 
onset_env = librosa.onset.onset_strength(y=array3, fmax=11025, aggregate=np.median)

all beat_track()s using it returns 0.

**Comment by raymond-dms** [comment] 2023-03-23 22:37
Sorry for the multiple comments...but this example shows difference in tempo() also...

To clarify bandwidth issue, I started testing full bw music (>~20k bw). attached please find bw_20k_full_array.npy

with 
array3=np.load('bw_20k_full_array.npy', allow_pickle=False)

I ran 0.8.1
tempo_0_8_0= librosa.beat.tempo(y=array3, sr=44100) -> 120.18

if ran 0.10.0 
tempo_0_10_0= librosa.feature.tempo(y=array3, sr=44100)             -> 92.28
tempo_0_10_0= librosa.feature.rhythm.tempo(y=array3, sr=44100) -> 92.28
[bw_20k_full_array.zip](https://github.com/librosa/librosa/files/11056900/bw_20k_full_array.zip)

differences also appear in beat_track(), similar to before, though i did not change sr or fmax there yet..

**Comment by bmcfee** [comment] 2023-03-24 01:01
> Is this the right way to inject fmax=11025?

Yes, but if you want to match what `beat_track` does exactly, you'll need to also set aggregate=np.median.  If you additionally want numerical equivalence to the 0.8.1 outputs, you'll also need to revisit the other two things I mentioned earlier in the thread (padding mode and sample rate conversion, if applicable).

Note that `feature.tempo` is just an alias for `rhythm.tempo` now, they use the exact same code.

**Comment by raymond-dms** [comment] 2023-03-24 03:02
> Yes, but if you want to match what `beat_track` does exactly, you'll need to also set aggregate=np.median. 

I did, as shown above, for a comparison to "np.mean": 
in 0.10.0 :
onset_env = librosa.onset.onset_strength(y=array3, fmax=11025, aggregate=np.median)
all beat_track() using it now return 0 (w/ default and various sr settings)

>If you additionally want numerical equivalence to the 0.8.1 outputs, you'll also need to revisit the other two things I mentioned earlier in the thread (padding mode and sample rate conversion, if applicable).

1. rate conversion is not applicable here, as you mentioned before, for we load .npy.
2. seems beat_track() & onset_strength() have no "padding" option exposed on API level
3. even if there is, i thought it only affects the output in a minor way. but the difference btw outputs now from array3 is 99.4 vs 35.39

> Note that `feature.tempo` is just an alias for `rhythm.tempo` now, they use the exact same code.
Thanks for the note. Yes, i added "rhythm.tempo" just to be sure af i saw warnings of upcoming 1.0 version move about it. Thanks.

**Comment by raymond-dms** [comment] 2023-03-27 14:37
Thanks again for your patience and kind help. I finally make 0.10.0's outputs match those of 0.8.1 on BOTH beat_track() and tempo() : 

  onset_env = librosa.onset.onset_strength(y=data, pad_mode='reflect', fmax=11025, sr=44100, aggregate=np.median)
  tempp beats1 = librosa.beat.beat_track(sr=sr, onset_envelope=onset_env)

  onset_env1 = librosa.onset.onset_strength(y=data, pad_mode='reflect', fmax=11025, sr=44100, aggregate=np.mean)
  tempo2= librosa.feature.rhythm.tempo(sr=sr, onset_envelope=onset_env1)

as you advised. The only twist is that : for tempo(), different from beat_track(), i need to use aggregate=np.mean instead of np.median. Is it  because 0.8.1 & 0.10.0 use different default in onset_strength() for tempo and for beat_track()? Thanks.

**Comment by bmcfee** [comment] 2023-03-27 14:39
Glad you got it sorted out!


> Is it because 0.8.1 & 0.10.0 use different default in onset_strength() for tempo and for beat_track()?

Yeah, that seems likely.  IIRC we factored the tempo estimator out of the beat tracker some time after the initial parameter settings were fixed, so that might explain the API divergence.

**Closed by bmcfee** 2023-03-27 14:39 UTC
Labels: question
