### ISSUE TITLE
Supress "PySoundFile failed. Trying audioread instead." warning

### ISSUE THREAD

**Issue by Vichoko** [librosa/librosa#1015] opened 2019-11-08 00:03 UTC
I'm trying to load an mp3 file with librosa.load(path) and it returns the following warning:

```
>>> import librosa
>>> librosa.load('mysong.mp3')
/data/anaconda3/envs/aidio/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
(array([-0.00183699, -0.00195219,  0.00391953, ..., -0.00337326,
        0.00295902,  0.00624093], dtype=float32), 22050)
```

As I'm doing this multiple times it floods the stdout.
So I have some questions:

1. Why is this a warning? Does it imply something bad?
2. Can I hide this warning text? As it floods my stdout in my batch operations.

**Comment by bmcfee** [comment] 2019-11-11 16:09
>     1. Why is this a warning? Does it imply something bad?

It's a warning, not an error.  This warning will always occur when loading mp3 because libsndfile does not (yet/currently) support the mp3 format.  Librosa tries to use libsndfile first, and if that fails, it will fall back on the audioread package, which is a bit slower and more brittle, but supports more formats. 



>     2\. Can I hide this warning text? As it floods my stdout in my batch operations.

Yes, you can always filter warnings. https://docs.python.org/3/library/warnings.html

**Comment by lostanlen** [comment] 2019-11-18 15:50
I think we can say that the Q has been answered. I am going to close this. Feel free to re-open if needed.

**Closed by lostanlen** 2019-11-18 15:50 UTC
Labels: question

**Comment by Vichoko** [comment] 2019-11-19 00:54
Any idea how to fix it? 
The performance issue worries me because I need to load a ton of files and a speedup would be cool
I got the error on a freshly set Ubuntu 18 conda environment.

**Comment by bmcfee** [comment] 2019-11-19 14:30
> Any idea how to fix it?

There is nothing to fix: this is operating as intended.

Again, this is not an error, it is a warning.  Your code will work just fine, it just will fall back on the (slower) audioread decoder.  This is unavoidable for now, since libsndfile still does not support mp3.

If you're really concerned about speed, you could transcode your mp3s into a more permissive format (eg ogg vorbis).

**Comment by Vichoko** [comment] 2019-11-20 20:36
Ok, i got it now. 
Thank you for the help 👍

**Comment by Vichoko** [comment] 2020-01-15 18:20
Any idea how to avoid getting this warnings printed on STDOUT?

I tried launching script with `python -W ignore <script>` and adding:
```
import warnings
warnings.filterwarnings('ignore')
```

At the beginning of the scripts and this User Warnings keep poping out.

**Comment by riven314** [comment] 2020-04-11 17:58
@bmcfee I encountered the same issue and thanks for the address. 
Meanwhile you mentioned audioread leads to slower performance and it's more brittle, could you elaborate more on how it is brittle because I would like to know its potential drawbacks. Besides that, would like to know if audioread would lead to any audio quality degration.

**Comment by bmcfee** [comment] 2020-05-12 13:21
> could you elaborate more on how it is brittle because I would like to know its potential drawbacks. Besides that, would like to know if audioread would lead to any audio quality degration.

Sure.  The "brittle" comment mainly refers to software health. The audioread package has very minimal test coverage, and its dependency chain varies substantially across platforms and environments.  Much of this is hidden from the end user, but it does make it difficult to debug and diagnose errors.

In terms of quality degradation, it should be fine.  In principle, these formats should all decode to the same bit stream, but there will always be subtle differences arising from frame alignment, floating point rounding error, etc. MP3 decoders are notorious for this kind of thing.

**Comment by egbertn** [comment] 2022-03-31 12:06
This is definitely a problem as of today.
"UserWarning: PySoundFile failed. Trying audioread instead"

When I get this warning, my python process hangs. So, i am loading an mp3 e.g. but this has problems. Cannot explain, but I am seeing this behavior, and I am working already many hours on this.

**Comment by bmcfee** [comment] 2022-03-31 12:41
> This is definitely a problem as of today.

Again, this is a *warning* and not an *error*.  If it's hanging when you load an mp3, that's a problem with audioread (or more likely, whatever decoder it is using) and not with librosa.

**Comment by egbertn** [comment] 2022-03-31 18:29
> > This is definitely a problem as of today.
> 
> Again, this is a _warning_ and not an _error_. If it's hanging when you load an mp3, that's a problem with audioread (or more likely, whatever decoder it is using) and not with librosa.

Ok, I found out why this happens. When the wav file is corrupt it gives this warning. I later found that my wavs sometimes were corrupt.

**Comment by bluenote10** [comment] 2022-09-06 20:26
The intention of the warning is good, but in practice it can still be a bit counter productive, e.g. when working with mp3 files. In this case the warnings conveys little information after having seen it many times.

The issue is that the warning encourages "bad", i.e., overly broad or even complete disabling of warnings like suggested in the post above. Turning off all warnings to silence this particular warning is harmful, because it can hide relevant warnings. Setting up a specific filterwarning is possible, but somewhat tricky and tedious, and the above "solution" is evidence that most users don't want to spend the time to do it properly.

Instead I'd love to have a boolean kwarg `use_audioread` (or `allow_audioread`, `no_warning`, ...), which I could specifically turn on in cases where I know I need audioread. This feels cleaner and more accessible than messing with filterwarnings. I can prepare to PR to demonstrate the idea...

**Comment by bmcfee** [comment] 2022-09-06 20:40
> Instead I'd love to have a boolean kwarg `use_audioread` (or `allow_audioread`, `no_warning`, ...), which I could specifically turn on in cases where I know I need audioread. This feels cleaner and more accessible than messing with filterwarnings. I can prepare to PR to demonstrate the idea...

I appreciate the motivation here, but I expect the entire point to be moot in the very near future.  libsndfile supports mp3 now, and we're basically waiting on a release of python-soundfile (currently on b6 for the 0.11 release) for this to be supported out of the box with no additional effort from our side.

Once soundfile releases with mp3 support, this warning should almost never appear - and when it does, it's a sign that something actually is very wrong!

At any rate, our eventual plan is to deprecate and remove audioread support #1456 , but it is a bit of a question-mark about how long that will take in practice based on release cycles.

**Comment by bluenote10** [comment] 2022-09-06 20:43
@bmcfee Great to hear, then I'll hold my horses :wink:

**Comment by javaprogrammer32072** [comment] 2022-09-20 10:42
h

**Comment by sanxchep** [comment] 2022-10-10 08:07
heyy faced is problem today while loading m4a file,
File is a valid m4a file,

1) Tried importing it on jupyter running librosa 0.9.2, worked with warning shown, 
2) Tried importing it on django environment running same librosa 0.9.2, throws the same warning as exception,

![Screenshot from 2022-10-10 13-36-01](https://user-images.githubusercontent.com/32956082/194822413-acd1aa1a-729f-4c20-9831-c5d428ae6cf5.png)
![Screenshot from 2022-10-10 13-35-08](https://user-images.githubusercontent.com/32956082/194822426-5504faed-97e1-43b7-b146-b4c9a7205f40.png)

Can anyone help?

**Comment by sanxchep** [comment] 2022-10-10 08:10
Sorry, my bad I had to install ffmpeg 
it worked after that.

apt install ffmpeg


https://stackoverflow.com/questions/62774301/can%C2%B4t-use-librosa-with-python-3

**Comment by Ritika457** [comment] 2023-11-17 20:32
I was working with .flac files using librosa and I am getting this warning:
UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
Can anybody help me with this ?

**Comment by bmcfee** [comment] 2023-11-17 21:08
Either your flac files are corrupted, or your libsndfile was compiled without flac support.  For the latter, you can check it by running
```python
>>> import soundfile
>>> soundfile.available_formats()
```
to make sure that FLAC is listed.

**Comment by ARusDian** [comment] 2024-10-06 10:54
> Either your flac files are corrupted, or your libsndfile was compiled without flac support. For the latter, you can check it by running
> 
> ```python
> >>> import soundfile
> >>> soundfile.available_formats()
> ```
> 
> to make sure that FLAC is listed.

hello my i ask something, so i have wav file and it runs smoothly on windows but it cant fails on ubuntu server, i don't know why untill i got know this 
![image](https://github.com/user-attachments/assets/c4f23b07-6588-41df-8480-263dfab47041)

does this means it only can read wav on windows ?

**Comment by bmcfee** [comment] 2024-10-07 14:40
> hello my i ask something, so i have wav file and it runs smoothly on windows but it cant fails on ubuntu server, i don't know why untill i got know this ![image](https://private-user-images.githubusercontent.com/87649208/373940672-c4f23b07-6588-41df-8480-263dfab47041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTIyNjcsIm5iZiI6MTcyODMxMTk2NywicGF0aCI6Ii84NzY0OTIwOC8zNzM5NDA2NzItYzRmMjNiMDctNjU4OC00MWRmLTg0ODAtMjYzZGZhYjQ3MDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE0MzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YTM2ZWViYmJkYTUzZGNkZTQ2MmYxODUyZDMwZTUzYjg4MDYzZGJlYzEyYThhM2I3MjU2MGJjMWIxNTg2N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._dbRiXNRE-hpzwI0De6Vkvrq_5Y7S6Uzt7Glm34OhKo)
> 
> does this means it only can read wav on windows ?

Your screen capture is cut off and only shows a small part of the output, so it's impossible for us to say.  It's also not clear whether this was run on windows or ubuntu.

**Comment by sonumb-z** [comment] 2025-03-13 07:14
> I was working with .flac files using librosa and I am getting this warning: UserWarning: PySoundFile failed. Trying audioread instead. warnings.warn("PySoundFile failed. Trying audioread instead.") Can anybody help me with this ?我正在使用librosa处理.flac文件，我得到了这个警告：UserWarning：PySoundFile失败。尝试有声阅读。warnings.warn（“PySoundFile失败。尝试有声阅读。")有人能帮我吗？

you can try it:pip install soundfile==0.12.0 or pip install soundfile==0.13.0
