### ISSUE TITLE
librosa.core.load truncates the audio duration? 

### ISSUE THREAD

**Issue by feliiiiicity** [librosa/librosa#876] opened 2019-05-06 02:13 UTC
Hi,

I used 2 ways to get the duration of an audio file. Namely, 

1. duration = librosa.get_duration(filename="xxxx.wav")
2. y, sr = librosa.core.load("xxxx.wav")
    duration = librosa.get_duration(y=y, sr=sr)

The second way returns a duration that is way much shorter than the first one. Is there any explanation? 

Thanks!

**Comment by lostanlen** [comment] 2019-05-06 02:19
Hello @feliiiiicity, welcome to librosa.
You may be interested in reading this thread: https://github.com/librosa/librosa/issues/686

The bottom line is that the first way uses the header of the WAV file (some metadata), whereas the latter uses the actual length of the waveform (data).

It seems like your file has an inconsistency between header and actual data. There's not much we can do about it on librosa's side.

I hope this helps!

**Comment by feliiiiicity** [comment] 2019-05-06 02:24
Hi @lostanlen thanks for the reply! 
But I played the audio and it is indeed the long duration, so I'm quite confused about the definition of the " the actual length of the waveform (data)" you mentioned.

**Comment by feliiiiicity** [comment] 2019-05-06 02:26
@lostanlen actually, the difference is huge. The audio is of 1:07:02.229 (according to Cool Edit Pro), and the first method returns 4022.229375, the second method returns 138.3615625

**Comment by lostanlen** [comment] 2019-05-06 02:28
hm, strange. can you host the file somewhere so i can load it myself?

**Comment by lostanlen** [comment] 2019-05-06 02:28
perhaps the sample rate is wrong in the header?

**Comment by feliiiiicity** [comment] 2019-05-06 02:33
I'm afraid I can't upload the audio file. The waveform looks periodic, 138.3615625 seems like one period, do you think this could be the reason ? 

The original sample rate (by soxi) and the objective sample rate are both 16000.

**Comment by lostanlen** [comment] 2019-05-06 02:45
if the file has a single channel, `librosa.get_duration(y=y, sr=sr)` is really nothing more than `len(y)/float(sr)`, so the problem is either in the loader or in the file itself. 
Downloading Bmr011 now

**Comment by lostanlen** [comment] 2019-05-06 02:53
I can't reproduce the problem on my computer (Max OS X 10.4.4). Methods 1 and 2 respectively return
4022.229387755102 and 4022.229375

what are your `librosa.__version__` and `soundfile.__version__`? mine are 0.6.3 and 0.10.2

**Comment by feliiiiicity** [comment] 2019-05-06 02:57
mine are 0.6.2 and 0.10.2

**Comment by lostanlen** [comment] 2019-05-06 03:00
ok, can you please run the following piece of code and tell me if it errors?


```
path = 'path/to/Bmr011.interaction.wav'

import soundfile as sf

with sf.SoundFile(path) as sf_desc:
    sr_native = sf_desc.samplerate
    if offset:
        # Seek to the start of the target read
        sf_desc.seek(int(offset * sr_native))
    if duration is not None:
        frame_duration = int(duration * sr_native)
    else:
        frame_duration = -1

    # Load the target number of frames, and transpose to match librosa form
    y = sf_desc.read(frames=frame_duration, dtype=dtype, always_2d=False).T
```

where you replace `path` by the appropriate in your filesystem

**Comment by feliiiiicity** [comment] 2019-05-06 03:10
offset is not defined

**Comment by lostanlen** [comment] 2019-05-06 03:13
ah, of course. please set
```
sr=16000
mono=True
offset=0.0
duration=None
```
before

**Comment by feliiiiicity** [comment] 2019-05-06 03:22
y is of shape (2213785,), around 138 seconds.

**Comment by lostanlen** [comment] 2019-05-06 03:28
ok, great. now can you try the following?

```
y, sr_native = __audioread_load(path, offset, duration, dtype)
print([len(y), sr_native])
```

**Comment by feliiiiicity** [comment] 2019-05-06 03:35
module "librosa.core.audio" has  no attribute "__audioread_load"

**Comment by bmcfee** [comment] 2019-05-07 18:52
This to me really sounds like a corrupted audio file.  If not that, it's almost certainly an upstream issue (eg in soundfile, audioread, or one its underlying codec implementations).

Is there any chance you could share the file in question so that we can investigate locally?

**Comment by feliiiiicity** [comment] 2019-05-08 00:54
@bmcfee @lostanlen Yes, it seems that the Bmr011 wav I used is corrupted. I re-downloaded the Bmr011 wav file, and this time nothing went wrong. Thank you for your help!

**Comment by bmcfee** [comment] 2019-05-08 01:16
I'm glad we got this sorted out!  I'll close this issue.

**Closed by bmcfee** 2019-05-08 01:16 UTC
