### ISSUE TITLE
Normalise Mel filters to constant energy of 1

### ISSUE THREAD

**Issue by gerazov** [librosa/librosa#1030] opened 2019-12-04 14:39 UTC
There is some scaling introduced by the Mel filter bank when calculating the Mel spectrogram. As stated in the documentation setting `norm = 1` does give constant energy per filter, but their energy is not 1. In fact, if you sum the filters you don't get a value of 1, but rather an average of 0.0929 with the following distribution (for `n_mel = 128`):

<img src='https://user-images.githubusercontent.com/15214418/70150753-cb57c600-16aa-11ea-8e96-2f4ecec87647.png' width='300'/>

This is due to the Mel frequency bandwidth of the triangles used for normalisation, but I'm thinking it might make sense to have the sum of the filter weights equal to 1 when normalised, maybe as an additional option.

**Comment by bmcfee** [comment] 2019-12-05 15:38
This is mainly an artifact of maintaining API compatibility with Slaney's auditory toolbox.  That was very important in 2012, less so these days.

I'm generally in favor of expanding the API to support different normalization modes here.  The only snag is that the current behavior is actually inconsistent with the rest of the API when it comes to norm conventions.  Everywhere else, we use `util.normalize` to implement l_p normalization, which with `norm=1` implements the normalization that you propose.  However, `norm=1` in `filters.mel` normalizes by 2/bandwidth.

This is all to say that extending the API in the right way is actually somewhat tricky, and would likely require a deprecation cycle.  How about the following:

- Add a new option `norm='slaney'` (new default value) that retains the current behavior
- If `norm=1` is given, throw a warning that this behavior will change in the next major release (probably 0.8)
- In the 0.8 release, remove the old `norm=1` behavior and replace it by the more consistent `util.normalize` behavior.  We'd still keep `norm='slaney'` as the default, so people would only see a change in behavior if they were explicitly calling mel functions with `norm=1` (which I doubt anyone is doing anyway).

Does that sound like a reasonable plan?

**Comment by bmcfee** [comment] 2019-12-05 20:40
Added context, pr #551 is relevant here. It seems that this PR added documentation for `norm=np.inf` support, but it's not actually implemented anywhere. Oops!

The discussion in that PR does provide some background on how the normalization taken here is "exact" in the sense of continuous frequency, rather than approximate and derived from the sampled frequencies.  (And, also, why this should be preferred over the `util.normalize()` case especially in low frequencies.)

That said, I'm still in favor of clarifying the API here and making the norm parameter more consistent.  Per the above suggestion, maybe `norm='exact'` rather than 'slaney'?  (No offense to Malcolm, but it might be more transparent what's going on with an adjective rather than a proper noun. :grin: )

**Comment by bmcfee** [comment] 2019-12-05 22:23
Side note: this is also related to #1018 and a broader conversation with @lostanlen about energy preservation in our transforms.

**Comment by lostanlen** [comment] 2019-12-05 22:47
Yes, energy conservation is one of the most difficult things to guarantee from an API standpoint. We struggle with this all the time in Kymatio. It's rewarding though! It makes so many things work better: NMF, convnets, entropy-based approaches, generalized likelihood ratios, etc. So it's definitely worth the effort.

I would prefer `continuous` over `exact`. But really, i don't see anything wrong with calling it `slaney`. I don't see any reason to keep it that way other than reproducing historical experiments of our field.

**Comment by bmcfee** [comment] 2019-12-05 23:03
Re keeping it the same vs changing, the principle of least surprise is important here. In this case, I don't think default behavior should change unless there's a strong reason for doing so, as it would break make things and prevent people from upgrading.  However, if it's part of a larger concerted effort to revise our filter normalizations across the package, I could see it being better off in the long run to change.

**Comment by lostanlen** [comment] 2019-12-05 23:33
I see. If the default behavior does not change, then IMO the most pressing issue becomes: "how can i measure the true acoustic energy of a spectrogram frame?"

**Comment by gerazov** [comment] 2019-12-06 14:48
Thanks @bmcfee - #551 was really informative. In deed, what I originally suggested doesn't make much sense considering the sampling of the Mel triangles, especially in the low frequencies.

To get an area of 1, if it makes sense to pursue it, we could normalize with the number of bins for each filter, like so:
```python
mel_basis_no_norm = librosa.filters.mel(sr, n_mels=128, n_fft=2048, norm=None)
enorm = np.sum(mel_basis_no_norm > 0, axis=1)
enorm = 2.0 / enorm
mel_basis_new = mel_basis_no_norm * enorm[:, np.newaxis]
```
The results with this are a bit noisier, but at least around 1 (1.0043 to be exact :stuck_out_tongue:)
<img src="https://user-images.githubusercontent.com/15214418/70330784-882e5c00-183e-11ea-94df-253d9cce0f1b.png" width="300">

To get it to 1 we would have to use the exact triangle crossings...

**Comment by bmcfee** [comment] 2019-12-06 15:18
> To get it to 1 we would have to use the exact triangle crossings...

Yes, which is what we do now.  The only difference is that it's normalized in natural units of Hz.  The filters should sum to `n_fft / sr` (more or less).  Of course, the filters are also discretely sampled, so summing the values directly will not get us exactly to 1:

```python
In [29]: M = librosa.filters.mel(44100, n_fft=2048, n_mels=128)                               

In [30]: M.sum(axis=1) * 44100 / 2048                                                         
Out[30]: 
array([0.907, 1.061, 0.965, 1.003, 1.023, 0.945, 1.081, 0.907, 1.099,
       0.927, 1.041, 0.985, 0.983, 1.043, 0.925, 1.101, 0.907, 1.079,
       0.947, 1.021, 1.005, 0.963, 1.063, 0.907, 1.117, 0.909, 1.059,
       0.967, 1.001, 1.025, 0.942, 1.08 , 0.928, 1.054, 0.981, 0.965,
       1.049, 0.995, 0.99 , 0.997, 1.001, 1.001, 0.998, 0.993, 0.999,
       1.025, 0.975, 1.015, 0.983, 1.021, 0.987, 0.996, 1.002, 1.004,
       1.003, 0.999, 0.993, 1.003, 1.001, 1.002, 0.995, 1.001, 1.003,
       1.002, 0.998, 0.994, 1.009, 0.996, 0.999, 1.001, 1.   , 0.997,
       1.005, 0.996, 1.001, 1.002, 1.   , 0.996, 1.005, 0.998, 0.999,
       1.002, 0.998, 1.001, 0.999, 1.002, 0.998, 1.001, 1.001, 0.999,
       1.001, 0.999, 1.001, 0.999, 1.   , 0.999, 1.001, 1.001, 0.999,
       1.001, 0.999, 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   ], dtype=float32)
```

**Comment by gerazov** [comment] 2019-12-06 15:55
Ok, I see - thanks. 

I originally wanted to get an energy estimate from the Mel spectrogram close to the one from the spectrogram. As is, the Mel FB scales down the energy. On the other hand, if we normalize with the number of bins instead of bandwidth in Hz, we get more energy in the Mel spectrogram. Here's a comparison (n_mel = 128):
<img src="https://user-images.githubusercontent.com/15214418/70336198-0132b100-1849-11ea-9c6f-4270d80f8274.png" width="300" />

This of course depends on the number of bins, so might not be that worth it at the end.

**Comment by bmcfee** [comment] 2019-12-06 19:12
> I originally wanted to get an energy estimate from the Mel spectrogram close to the one from the spectrogram. As is, the Mel FB scales down the energy. On the other hand, if we normalize with the number of bins instead of bandwidth in Hz, we get more energy in the Mel spectrogram.

I think almost all of this could be resolved by proper dimensional analysis.  Alas, numpy does not support units on ndarrays, and I don't think it's practical to use `pint` objects instead, so we'll just need to be careful in our analysis.

I'm not sure it's fair to say that melfb scales down the energy, it's just reporting in different units.  As such, a direct comparison between values will be misleading.

**Comment by gerazov** [comment] 2019-12-13 11:03
Yes, but it might be more practical (easier) to just sum the coefficients to get the energy, as is commonly done with the spectrogram.

**Comment by onkyo14taro** [comment] 2020-01-04 10:15
Pardon me for butting in.

I think that it is more natural to directly calculate the area (sum) of each channel without using the Slaney's area normalization method.
In this case, the method for setting the area of each channel to 1 is as follows:
```python
weights = weights / np.sum(weights, axis=1, keepdims=1)
```
The following equation is considered to be appropriate if it corresponds to the total energy of the spectrogram:
```python
weights = weights / np.sum(weights, axis=1, keepdims=1) * (n_fft - 2) / n_mels
```
The reason for `n_fft - 2` is that the weight of the terminal frequency (0 Hz and sr/2 Hz) is always 0.

I don't think it's always necessary to match the total energy in the spectrogram, but intuitively it feels better.

**Comment by bmcfee** [comment] 2020-01-04 16:38
@onkyo14taro thanks for the input.

The proposal, as it currently stands (summarized in [this comment](https://github.com/librosa/librosa/issues/1030#issuecomment-562183483)), is to adjust the API to allow for normalization as you described (using our numerically stable `util.norm` function), and conform to the L_p norm conventions used elsewhere in the API.  Stability is crucial here, as many Mel basis configurations leave gaps in the spectrum, which would result in `1/0` factors.

The default normalization will stay the same, though we still need to settle on nomenclature.  `norm='continuous'` seems non-obvious to me, but I agree that `norm='exact'` isn't really any better.

**Comment by onkyo14taro** [comment] 2020-01-05 09:41
I'm sorry, I had not understood the flow of the discussion very much, but I understand now thanks to your comment.

The problem of `norm`'s option name is controversial.
I think it's a bit difficult to convey that nuance in one word.
This is because the currently implemented area normalization based on Slaney's method is, in a sense (_continuous frequency, not discrete_), also an **exact** normalization.

- the current Slaney's implementation:
  - `enorm = 2.0 / (mel_f[2:n_mels+2] - mel_f[:n_mels])`
  - `area = n_fft / sr`
  - continuous frequency
- the proposed implementation 1:
  - `enorm = 2.0 / (mel_f[2:n_mels+2] - mel_f[:n_mels]) * sr / n_fft`
  - `area = 1`
  - continuous frequency
- the proposed implementation 2 (using `librosa.util.normalize`):
  - `enorm = 1.0 / np.sum(weights, axis=1, keepdims=True)`
  - `area = 1`
  - discrete frequency

In my opinion, the proposed implementation 2 would be better, and the following names are considered as candidates:

- `norm='exact_1'`
- `norm='continuous_1'`
- `norm='L1'`
- `norm='each'`
- `norm='each_1'`
- `norm='librosa'`

Umm, it's difficult to come up with a name that convinces everyone...

(The name `area` is confusing because `area` reminiscents the Slaney's area normalization.)

**Comment by bmcfee** [comment] 2020-01-06 20:00
> In my opinion, the proposed implementation 2 would be better,

I think I agree with that, and don't see a need for implementing proposal 1.  (Users who really want that behavior can always scale by `sr / n_fft` post-hoc.)

Where it gets a little tricky is in dealing with FFT normalization modes.  By default, numpy's FFT is unnormalized, though since 1.10 (released in 2016) you can specify `norm='ortho'` to scale by `sqrt(n_fft)` -- I think at some point it's worth considering extending `stft` (and related) methods to expose this functionality, which did not exist when we first designed the API.

However, this raises a bit of a problem for downstream processing like `mel`.  Slaney's normalization (our current method) cancels out the factor of `n_fft`, so that mel spectra computed with different frame lengths (but the same sampling rate) should have comparable scale.  This is a nice property to have when you want to experiment with things like frequency over-sampling.  Proposals 1 and 2 lose this feature, in favor of propagating frame length scaling through to the output.  (It typically comes out in the wash of `power_to_db` anyway, especially when using an adaptive reference point, but it's nice to account for all variables here.)

However, if we support `ortho` mode, we lose this property in mel spectra with the current normalization (and proposal 1).  Proposal 2 will have consistent behavior though; I would actually prefer a normalization of the form
```python
util.normalize(melfb, norm=norm, axis=1)
```
where `norm` can be any supported normalization (l1, l2, inf, None, etc).

---

> and the following names are considered as candidates:

I think it's helpful here to follow the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).  For consistency with the rest of the API, the `norm=` parameter should conform to the values supported by `util.norm()`.  We can add extra modes, encoded by string values, but we should not change the definition of existing conventions (1, 2, inf, None) or add alternate identifiers for existing conventions; L1 should just be `norm=1`.

As for how to name the current normalization... maybe `'slaney'` is okay after all?  Since we haven't been able to come up with a pithy name that isn't easily misconstrued, referring to it by attribution rather than description could be a nice compromise.

**Comment by onkyo14taro** [comment] 2020-01-08 16:39
@bmcfee Thanks for giving many suggestions!

> However, this raises a bit of a problem for downstream processing like mel. Slaney's normalization (our current method) cancels out the factor of n_fft, so that mel spectra computed with different frame lengths (but the same sampling rate) should have comparable scale. This is a nice property to have when you want to experiment with things like frequency over-sampling. Proposals 1 and 2 lose this feature, in favor of propagating frame length scaling through to the output. (It typically comes out in the wash of power_to_db anyway, especially when using an adaptive reference point, but it's nice to account for all variables here.)
However, if we support ortho mode, we lose this property in mel spectra with the current normalization (and proposal 1). 

This perspective was new to me.

> I think it's helpful here to follow the principle of least surprise. For consistency with the rest of the API, the norm= parameter should conform to the values supported by util.norm(). We can add extra modes, encoded by string values, but we should not change the definition of existing conventions (1, 2, inf, None) or add alternate identifiers for existing conventions; L1 should just be norm=1.

This made me understand that following the APIs of other existing functions (like `normalize`) can reduce user confusion.

**Closed** 2020-01-10 14:21 UTC
Labels: API change, enhancement, functionality
