### ISSUE TITLE
waveplot() segfaults when given input of shape (1, 35000)

### ISSUE THREAD

**Issue by sliedes** [librosa/librosa#1122] opened 2020-05-18 09:30 UTC
#### Description
When waveplot() is given a numpy array of shape (1, 35000), the interpreter segfaults.

#### Steps/Code to Reproduce
```
$ python
Python 3.7.6 (default, Feb  8 2020, 13:20:58) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from librosa.display import waveplot
/home/sliedes/.virtualenvs/torch/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
/home/sliedes/.virtualenvs/torch/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
>>> import numpy as np
>>> waveplot(np.zeros((1, 35000)))
Segmentation fault (core dumped)
```

#### Expected Results
waveplot fails gracefully, at least does not crash the interpreter.

#### Actual Results
Python interpreter segfaults.

#### Versions
Linux-5.6.7-arch1-1-x86_64-with-arch
Python 3.7.6 (default, Feb  8 2020, 13:20:58) 
[GCC 9.2.0]
NumPy 1.17.3
SciPy 1.2.0
librosa 0.7.2

**Comment by bmcfee** [comment] 2020-05-18 12:56
Thanks for catching this.  I've confirmed it locally on the development branch.
The error seems to come from having `shape=(1,N)`; N=35000 is unimportant, as it also fails for much smaller values.

Technically, this isn't exactly a bug, as `shape=(1,N)` is not among the supported types listed in the docstring `(n,) or (2, N)`.  However, it certainly shouldn't crash, so we should at least throw an exception before running into trouble.

In the meantime, you can work around this by squashing out the singleton dimension.

**Comment by bmcfee** [comment] 2020-05-23 14:56
Thinking more on this one, I think the problem is due to a gap in the logic for `valid_audio`.  Right now a `(1, N)` passes for valid, but I'm not sure that it should.  This matters because if we decide that `(1, N)` is not valid, then we can fix this in `valid_audio` and not change `waveplot` at all.  However, if we decide that `(1, N)` is okay, then we'll need to implement the fix inside `waveplot`, and potentially audit the code for other places where this snag could hit.

---

We define an array `y` to be valid audio if it's mono (`y.ndim==1`) or stereo (`y.ndim == 2`), and satisfies certain data and memory contiguity requirements: [see here](https://github.com/librosa/librosa/blob/f94424aa6d77abb92856d762fc70e57850cd0617/librosa/util/utils.py#L260-L281)

However, we never check the number of channels in the case that `y` is not constrained to be monophonic.  A stereo file would have `y.shape == (2, N)`, but if we want to support multi-channel more generally, it should have shape `(K, N)`.  This would specialize to the monophonic case as `(1, N)`.

I think in the long run, it will make sense to aim for a consistent API for mono and multi-channel, which would mean promoting everything to `(K, N)` (for `K >= 1`).  However, I'm not sure it makes sense to do that right now.  (This might be more of a 2.0 issue.) The good news is that `np.atleast_2d` makes it easy to push a `(N,)` up to `(1, N)` without invoking any copies.

---

As an aside, the waveplot fill_between logic stops making sense for `K>2`, so an easy option would be to force waveplot to only work for mono or stereo anyway, which renders the above discussion somewhat moot.

I'm curious for input on this before I go about fixing it.  @lostanlen ?

**Comment by lostanlen** [comment] 2020-05-25 18:31
Should we be [taking vector transposes seriously](https://github.com/JuliaLang/julia/issues/4774)?

**Comment by bmcfee** [comment] 2020-05-27 14:12
I gave this one some though, and I think the following proposal is reasonable.

## Short term (0.8)

Tighten `valid_audio` to be more explicit about its expectations: `(N,)` for mono, `(2, N)` for stereo, and nothing else is allowed.  Right now, the documentation for `valid_audio` is a bit ambiguous on this point, and I'd like to clarify it in the fix for this bug.

**Discussion point**: should we allow `(K>2, N)` at this point?  I'm not sure that any of our codec dependencies can even produce multi-channel data, so maybe it's not a big deal to rule it out for now.

## Longer term (0.9 and beyond)

Take multi-channel seriously. :rofl: 

Support `(N,)` (mono) `(1,N)` (mono), `(K, N)` (stereo and multichannel) fully.  This will require substantial rewriting of many core methods, though some of them might be easily adapted by replacing dot products with einstein summations (eg mel spectrogram).  The hard part of this will be determining which methods will support multi-channel and which ones only make sense for mono.  I'll kick this out to a separate issue so we can discuss it thoroughly.

**Closed** 2020-05-28 10:20 UTC
Labels: bug
