### ISSUE TITLE
librosa.resample not working with pyinstaller

### ISSUE THREAD

**Issue by sirish-gambhira** [librosa/librosa#1797] opened 2024-01-15 06:05 UTC
**Describe the bug**
librosa.resample is giving the following error inside .exe application
File "librosa\core\audio.py", line 677, in resample
 File "lazy_loader\__init__.py", line 112, in __getattr__
TypeError: can only join an iterable
**To Reproduce**
```
import soundfile
import librosa
import numpy as np

SAMPLING_RATE = 16000
# load any .wav file
data, sr = soundfile.read('audio.wav', dtype=np.int16)

if sr != SAMPLING_RATE:
    data = data.astype(np.float32) / 0x8000
    data = librosa.resample(data, orig_sr=sr, target_sr=SAMPLING_RATE, res_type='kaiser_fast')
    data = (data * 0x8000).astype(np.int16)
```
Convert the .py program into a .exe application using pyinstaller and run it

**Software versions**
librosa version: 0.10.1

**Comment by sirish-gambhira** [comment] 2024-01-15 06:06
UPDATE: I rolled back to 0.9.2 version and faced no problem.

**Comment by bmcfee** [comment] 2024-01-15 15:15
This is a duplicate of #1705

**Closed by bmcfee** 2024-01-15 15:15 UTC

**Comment by XPDD** [comment] 2024-06-24 02:48
I also have this problem.
