### ISSUE TITLE
test_sorted_decompose fails on aarch64

### ISSUE THREAD

**Issue by ggardet** [librosa/librosa#1304] opened 2021-04-09 07:46 UTC
**Describe the bug**
On aarch64, some tests fail, including `test_sorted_decompose `.

**To Reproduce**
Run tests on aarch64

**Expected behavior**
`test_sorted_decompose ` should pass.

**Screenshots**
N/A

**Software versions***
Platform: openSUSE Tumbleweed aarch64
Python: 3.8.8
Numpy: 1.20.1
SciPy: 1.6.1
librosa: 0.8.0

**Additional context**
Error log:
```
[  846s] ____________________________ test_sorted_decompose _____________________________
[  846s] [gw1] linux -- Python 3.8.8 /usr/bin/python3.8
[  846s] 
[  846s]     def test_sorted_decompose():
[  846s]     
[  846s]         X = np.array([[1, 2, 3, 4, 5, 6], [1, 1, 1.2, 1, 0.8, 1]])
[  846s]     
[  846s] >       (W, H) = librosa.decompose.decompose(X, sort=True, random_state=0)
[  846s] 
[  846s] tests/test_decompose.py:74: 
[  846s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  846s] librosa/decompose.py:156: in decompose
[  846s]     activations = transformer.fit_transform(S.T).T
[  846s] /usr/lib64/python3.8/site-packages/sklearn/decomposition/_nmf.py:1311: in fit_transform
[  846s]     W, H, n_iter_ = non_negative_factorization(
[  846s] /usr/lib64/python3.8/site-packages/sklearn/utils/validation.py:63: in inner_f
[  846s]     return f(*args, **kwargs)
[  846s] /usr/lib64/python3.8/site-packages/sklearn/decomposition/_nmf.py:1066: in non_negative_factorization
[  846s]     W, H = _initialize_nmf(X, n_components, init=init,
[  846s] /usr/lib64/python3.8/site-packages/sklearn/decomposition/_nmf.py:346: in _initialize_nmf
[  846s]     U, S, V = randomized_svd(X, n_components, random_state=random_state)
[  846s] /usr/lib64/python3.8/site-packages/sklearn/utils/validation.py:63: in inner_f
[  846s]     return f(*args, **kwargs)
[  846s] /usr/lib64/python3.8/site-packages/sklearn/utils/extmath.py:357: in randomized_svd
[  846s]     Uhat, s, Vt = linalg.svd(B, full_matrices=False)
[  846s] /usr/lib64/python3.8/site-packages/scipy/linalg/decomp_svd.py:106: in svd
[  846s]     a1 = _asarray_validated(a, check_finite=check_finite)
[  846s] /usr/lib64/python3.8/site-packages/scipy/_lib/_util.py:262: in _asarray_validated
[  846s]     a = toarray(a)
[  846s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  846s] 
[  846s] a = array([[-9.536, -2.191],
[  846s]        [   nan,    nan]]), dtype = None
[  846s] order = None
[  846s] 
[  846s]     @set_module('numpy')
[  846s]     def asarray_chkfinite(a, dtype=None, order=None):
[  846s]         """Convert the input to an array, checking for NaNs or Infs.
[  846s]     
[  846s]         Parameters
[  846s]         ----------
[  846s]         a : array_like
[  846s]             Input data, in any form that can be converted to an array.  This
[  846s]             includes lists, lists of tuples, tuples, tuples of tuples, tuples
[  846s]             of lists and ndarrays.  Success requires no NaNs or Infs.
[  846s]         dtype : data-type, optional
[  846s]             By default, the data-type is inferred from the input data.
[  846s]         order : {'C', 'F', 'A', 'K'}, optional
[  846s]             Memory layout.  'A' and 'K' depend on the order of input array a.
[  846s]             'C' row-major (C-style),
[  846s]             'F' column-major (Fortran-style) memory representation.
[  846s]             'A' (any) means 'F' if `a` is Fortran contiguous, 'C' otherwise
[  846s]             'K' (keep) preserve input order
[  846s]             Defaults to 'C'.
[  846s]     
[  846s]         Returns
[  846s]         -------
[  846s]         out : ndarray
[  846s]             Array interpretation of `a`.  No copy is performed if the input
[  846s]             is already an ndarray.  If `a` is a subclass of ndarray, a base
[  846s]             class ndarray is returned.
[  846s]     
[  846s]         Raises
[  846s]         ------
[  846s]         ValueError
[  846s]             Raises ValueError if `a` contains NaN (Not a Number) or Inf (Infinity).
[  846s]     
[  846s]         See Also
[  846s]         --------
[  846s]         asarray : Create and array.
[  846s]         asanyarray : Similar function which passes through subclasses.
[  846s]         ascontiguousarray : Convert input to a contiguous array.
[  846s]         asfarray : Convert input to a floating point ndarray.
[  846s]         asfortranarray : Convert input to an ndarray with column-major
[  846s]                          memory order.
[  846s]         fromiter : Create an array from an iterator.
[  846s]         fromfunction : Construct an array by executing a function on grid
[  846s]                        positions.
[  846s]     
[  846s]         Examples
[  846s]         --------
[  846s]         Convert a list into an array.  If all elements are finite
[  846s]         ``asarray_chkfinite`` is identical to ``asarray``.
[  846s]     
[  846s]         >>> a = [1, 2]
[  846s]         >>> np.asarray_chkfinite(a, dtype=float)
[  846s]         array([1., 2.])
[  846s]     
[  846s]         Raises ValueError if array_like contains Nans or Infs.
[  846s]     
[  846s]         >>> a = [1, 2, np.inf]
[  846s]         >>> try:
[  846s]         ...     np.asarray_chkfinite(a)
[  846s]         ... except ValueError:
[  846s]         ...     print('ValueError')
[  846s]         ...
[  846s]         ValueError
[  846s]     
[  846s]         """
[  846s]         a = asarray(a, dtype=dtype, order=order)
[  846s]         if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
[  846s] >           raise ValueError(
[  846s]                 "array must not contain infs or NaNs")
[  846s] E           ValueError: array must not contain infs or NaNs
[  846s] 
[  846s] /usr/lib64/python3.8/site-packages/numpy/lib/function_base.py:488: ValueError
```

**Comment by bmcfee** [comment] 2021-04-09 11:33
Closing this out as a dupe of #1301

**Closed by bmcfee** 2021-04-09 11:33 UTC
