### ISSUE TITLE
test_default_decompose fails on aarch64

### ISSUE THREAD

**Issue by ggardet** [librosa/librosa#1301] opened 2021-04-09 07:41 UTC
**Describe the bug**
On aarch64, some tests fail, including `test_default_decompose`.

**To Reproduce**
Run tests on aarch64

**Expected behavior**
`test_default_decompose` should pass.

**Screenshots**
N/A

**Software versions***
Platform: openSUSE Tumbleweed aarch64
Python: 3.8.8
Numpy: 1.20.1
SciPy: 1.6.1
librosa: 0.8.0

**Additional context**
Error log:
```
[  845s] ____________________________ test_default_decompose ____________________________
[  845s] [gw1] linux -- Python 3.8.8 /usr/bin/python3.8
[  845s] 
[  845s]     def test_default_decompose():
[  845s]     
[  845s]         X = np.array([[1, 2, 3, 4, 5, 6], [1, 1, 1.2, 1, 0.8, 1]])
[  845s]     
[  845s] >       (W, H) = librosa.decompose.decompose(X, random_state=0)
[  845s] 
[  845s] tests/test_decompose.py:28: 
[  845s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  845s] librosa/decompose.py:156: in decompose
[  845s]     activations = transformer.fit_transform(S.T).T
[  845s] /usr/lib64/python3.8/site-packages/sklearn/decomposition/_nmf.py:1311: in fit_transform
[  845s]     W, H, n_iter_ = non_negative_factorization(
[  845s] /usr/lib64/python3.8/site-packages/sklearn/utils/validation.py:63: in inner_f
[  845s]     return f(*args, **kwargs)
[  845s] /usr/lib64/python3.8/site-packages/sklearn/decomposition/_nmf.py:1066: in non_negative_factorization
[  845s]     W, H = _initialize_nmf(X, n_components, init=init,
[  845s] /usr/lib64/python3.8/site-packages/sklearn/decomposition/_nmf.py:346: in _initialize_nmf
[  845s]     U, S, V = randomized_svd(X, n_components, random_state=random_state)
[  845s] /usr/lib64/python3.8/site-packages/sklearn/utils/validation.py:63: in inner_f
[  845s]     return f(*args, **kwargs)
[  845s] /usr/lib64/python3.8/site-packages/sklearn/utils/extmath.py:357: in randomized_svd
[  845s]     Uhat, s, Vt = linalg.svd(B, full_matrices=False)
[  845s] /usr/lib64/python3.8/site-packages/scipy/linalg/decomp_svd.py:106: in svd
[  845s]     a1 = _asarray_validated(a, check_finite=check_finite)
[  845s] /usr/lib64/python3.8/site-packages/scipy/_lib/_util.py:262: in _asarray_validated
[  845s]     a = toarray(a)
[  845s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  845s] 
[  845s] a = array([[-9.536, -2.191],
[  845s]        [   nan,    nan]]), dtype = None
[  845s] order = None
[  845s] 
[  845s]     @set_module('numpy')
[  845s]     def asarray_chkfinite(a, dtype=None, order=None):
[  845s]         """Convert the input to an array, checking for NaNs or Infs.
[  845s]     
[  845s]         Parameters
[  845s]         ----------
[  845s]         a : array_like
[  845s]             Input data, in any form that can be converted to an array.  This
[  845s]             includes lists, lists of tuples, tuples, tuples of tuples, tuples
[  845s]             of lists and ndarrays.  Success requires no NaNs or Infs.
[  845s]         dtype : data-type, optional
[  845s]             By default, the data-type is inferred from the input data.
[  845s]         order : {'C', 'F', 'A', 'K'}, optional
[  845s]             Memory layout.  'A' and 'K' depend on the order of input array a.
[  845s]             'C' row-major (C-style),
[  845s]             'F' column-major (Fortran-style) memory representation.
[  845s]             'A' (any) means 'F' if `a` is Fortran contiguous, 'C' otherwise
[  845s]             'K' (keep) preserve input order
[  845s]             Defaults to 'C'.
[  845s]     
[  845s]         Returns
[  845s]         -------
[  845s]         out : ndarray
[  845s]             Array interpretation of `a`.  No copy is performed if the input
[  845s]             is already an ndarray.  If `a` is a subclass of ndarray, a base
[  845s]             class ndarray is returned.
[  845s]     
[  845s]         Raises
[  845s]         ------
[  845s]         ValueError
[  845s]             Raises ValueError if `a` contains NaN (Not a Number) or Inf (Infinity).
[  845s]     
[  845s]         See Also
[  845s]         --------
[  845s]         asarray : Create and array.
[  845s]         asanyarray : Similar function which passes through subclasses.
[  845s]         ascontiguousarray : Convert input to a contiguous array.
[  845s]         asfarray : Convert input to a floating point ndarray.
[  845s]         asfortranarray : Convert input to an ndarray with column-major
[  845s]                          memory order.
[  845s]         fromiter : Create an array from an iterator.
[  845s]         fromfunction : Construct an array by executing a function on grid
[  845s]                        positions.
[  845s]     
[  845s]         Examples
[  845s]         --------
[  845s]         Convert a list into an array.  If all elements are finite
[  845s]         ``asarray_chkfinite`` is identical to ``asarray``.
[  845s]     
[  845s]         >>> a = [1, 2]
[  845s]         >>> np.asarray_chkfinite(a, dtype=float)
[  845s]         array([1., 2.])
[  845s]     
[  845s]         Raises ValueError if array_like contains Nans or Infs.
[  845s]     
[  845s]         >>> a = [1, 2, np.inf]
[  845s]         >>> try:
[  845s]         ...     np.asarray_chkfinite(a)
[  845s]         ... except ValueError:
[  845s]         ...     print('ValueError')
[  845s]         ...
[  845s]         ValueError
[  845s]     
[  845s]         """
[  845s]         a = asarray(a, dtype=dtype, order=order)
[  845s]         if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
[  845s] >           raise ValueError(
[  845s]                 "array must not contain infs or NaNs")
[  845s] E           ValueError: array must not contain infs or NaNs
[  845s] 
[  845s] /usr/lib64/python3.8/site-packages/numpy/lib/function_base.py:488: ValueError
```

**Comment by bmcfee** [comment] 2021-04-09 10:55
I don't have an aarch64 machine to test on, but I'm >99% confident that this  (and the flurry of related issues just posted, #1302 #1303 #1304) are upstream issues in scipy.  If you follow the backtrace:

```
[  845s] tests/test_decompose.py:28: 
[  845s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  845s] librosa/decompose.py:156: in decompose
[  845s]     activations = transformer.fit_transform(S.T).T
[  845s] /usr/lib64/python3.8/site-packages/sklearn/decomposition/_nmf.py:1311: in fit_transform
[  845s]     W, H, n_iter_ = non_negative_factorization(
[  845s] /usr/lib64/python3.8/site-packages/sklearn/utils/validation.py:63: in inner_f
[  845s]     return f(*args, **kwargs)
[  845s] /usr/lib64/python3.8/site-packages/sklearn/decomposition/_nmf.py:1066: in non_negative_factorization
[  845s]     W, H = _initialize_nmf(X, n_components, init=init,
[  845s] /usr/lib64/python3.8/site-packages/sklearn/decomposition/_nmf.py:346: in _initialize_nmf
[  845s]     U, S, V = randomized_svd(X, n_components, random_state=random_state)
[  845s] /usr/lib64/python3.8/site-packages/sklearn/utils/validation.py:63: in inner_f
[  845s]     return f(*args, **kwargs)
[  845s] /usr/lib64/python3.8/site-packages/sklearn/utils/extmath.py:357: in randomized_svd
[  845s]     Uhat, s, Vt = linalg.svd(B, full_matrices=False)
[  845s] /usr/lib64/python3.8/site-packages/scipy/linalg/decomp_svd.py:106: in svd
[  845s]     a1 = _asarray_validated(a, check_finite=check_finite)
[  845s] /usr/lib64/python3.8/site-packages/scipy/_lib/_util.py:262: in _asarray_validated
[  845s]     a = toarray(a)
[  845s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
```

The input that we're providing is well-formed, and the error only pops up in the call to svd.  I expect that this can be reproduced outside of librosa (e.g., just by using sklearn's NMF) and is therefore not our issue to resolve.

**Comment by bmcfee** [comment] 2021-05-12 15:12
Since this is by all appearances an upstream issue, I'm closing this out.

**Closed by bmcfee** 2021-05-12 15:12 UTC
Labels: Upstream/dependency bug
