### ISSUE TITLE
librosa.load(0) hangs

### ISSUE THREAD

**Issue by eyaler** [librosa/librosa#1377] opened 2021-09-17 15:09 UTC
librosa.load(0) hangs for me on windows / python 3.9.5

**Comment by bmcfee** [comment] 2021-09-17 15:12
Please use the template when filing issues.  Deleting the structure that we give you to format issues is somewhat rude.

**Comment by bmcfee** [comment] 2021-09-18 00:24
I'm pretty sure this is not a "hang", but rather that soundfile is waiting for input from file descriptor 0 (stdin).  When the first argument is an integer, it is treated as an open file descriptor (which stdin ought to be) by soundfile.

Since this is documented and expected behavior, I don't see anything wrong here and will close this out.  @eyaler can reopen this if my diagnosis is incorrect, but please provide more information if so.

**Closed by bmcfee** 2021-09-18 00:24 UTC
Labels: wontfix
