### ISSUE TITLE
Compatibility with numba >= 49.x

### ISSUE THREAD

**Issue by alexandreCameron** [librosa/librosa#1204] opened 2020-07-06 07:47 UTC
**Describe the bug**

Librosa does not seem to function properly with version >= 49.x

**To Reproduce**
linux: ubuntu 18.04 LTS
python: 3.8
numba: 50.1

**Expected behavior**
librosa can be excuted

**Software versions***

Linux-5.3.0-62-generic-x86_64-with-glibc2.27
python: 3.8.0 (Oct 28 2019)
numpy: 1.19.0
scipy: 1.4.1
librosa: 0.7.2

INSTALLED VERSIONS
------------------
python: 3.8.0 (default, Oct 28 2019, 16:14:01)
[GCC 8.3.0]

librosa: 0.7.2

audioread: 2.1.8
numpy: 1.19.0
scipy: 1.4.1
sklearn: 0.23.1
joblib: 0.14.1
decorator: 4.4.2
six: 1.14.0
soundfile: 0.10.3
resampy: 0.2.2
**numba: 0.48.0**

numpydoc: None
sphinx: 3.0.4
sphinx_rtd_theme: 0.4.3
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 5.4.3
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.2
presets: None

**Comment by lostanlen** [comment] 2020-07-06 10:41
Closing as duplicate of #1105, fixed by #1107
installing numba 0.48 will solve your problem

Let's redirect the discussion to: https://github.com/numba/numba/issues/5865

**Closed by lostanlen** 2020-07-06 10:41 UTC
Labels: already fixed

**Comment by alexandreCameron** [comment] 2020-07-08 08:14
@lostanlen : I'm sorry but staying up to date with the last version of numba is my objective.

Is there a way to run librosa on the latest version of numba ?

If not, do you have a plan to patch librosa in the future ?

**Comment by bmcfee** [comment] 2020-07-08 10:52
@alexandreCameron the problem is already fixed on the development branch.  You can follow the directions in the readme for installing from github.

The 0.8 release will be out some time in the next few weeks.
