### ISSUE TITLE
New installations of librosa break with numba 0.50.0

### ISSUE THREAD

**Issue by JulianFerry** [librosa/librosa#1162] opened 2020-06-12 16:20 UTC
**Describe the bug**

Numba has had a new release (0.50.0) which breaks new installations of librosa. Importing librosa now returns:
```
  File "/site-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'
```

**To Reproduce**
```
python -m venv venv
source venv/bin/activate
pip install librosa
python -c "import librosa"
```

Edit:

This was the warning message before the update:
```
/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning:
An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators'
or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
```

**Comment by lostanlen** [comment] 2020-06-12 16:27
@JulianFerry hello, this issue is a duplicate of #1105 and was closed in #1107

As the warning says, you need to  `pip install numba==0.48.0`

**Comment by JulianFerry** [comment] 2020-06-13 09:01
Hi, sorry about the duplicate! I missed the closed issues. Isn't it a bit strange to force the user to install the correct requirements themselves? Can't this just be set in the requirements for the package?

**Comment by JulianFerry** [comment] 2020-06-13 10:29
Ah so it looks like there hasn't been a release which includes #1107 yet which was an oversight on my part. So I suppose my request/suggestion is to release a 0.7.3 with this bugfix soon :) I can work around it. Just wanted to let you know.

**Comment by bmcfee** [comment] 2020-06-13 14:42
> Hi, sorry about the duplicate! I missed the closed issues. Isn't it a bit strange to force the user to install the correct requirements themselves? Can't this just be set in the requirements for the package?

If all dependencies strictly adhered to semantic versioning, then yes, that would work.  The problem here is that numba introduced an API-breaking change with a relatively short deprecation cycle (less than 2 months!), and they don't generally adhere to semantic versioning (neither do we), so it would be impossible to anticipate this kind of thing by pinning to version numbers.  They have significantly more developer time and resources than we do, and we were not able to put out a release before the change took effect.





>  So I suppose my request/suggestion is to release a 0.7.3 with this bugfix soon

Thanks for the suggestion.  At this point, we're pretty close to the 0.8.0 release, and will just go for that rather than roll back changes to put out a point release for this issue.

**Closed by bmcfee** 2020-06-13 14:42 UTC
Labels: already fixed

**Comment by JulianFerry** [comment] 2020-06-15 15:57
> > Hi, sorry about the duplicate! I missed the closed issues. Isn't it a bit strange to force the user to install the correct requirements themselves? Can't this just be set in the requirements for the package?
> 
> If all dependencies strictly adhered to semantic versioning, then yes, that would work. The problem here is that numba introduced an API-breaking change with a relatively short deprecation cycle (less than 2 months!), and they don't generally adhere to semantic versioning (neither do we), so it would be impossible to anticipate this kind of thing by pinning to version numbers. They have significantly more developer time and resources than we do, and we were not able to put out a release before the change took effect.
> 
> > So I suppose my request/suggestion is to release a 0.7.3 with this bugfix soon
> 
> Thanks for the suggestion. At this point, we're pretty close to the 0.8.0 release, and will just go for that rather than roll back changes to put out a point release for this issue.

Okay makes sense. I massively appreciate the detail you put in your responses by the way.
