### ISSUE TITLE
Librosa doesn't work with python2.7

### ISSUE THREAD

**Issue by ayushch3** [librosa/librosa#732] opened 2018-06-27 12:32 UTC
Installing librosa using pip on python 2.7 runs into this error:
    Traceback (most recent call last):
      File "/tmp/pip-install-50714txv/llvmlite/ffi/build.py", line 153, in <module>
        main()
      File "/tmp/pip-install-50714txv/llvmlite/ffi/build.py", line 143, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-50714txv/llvmlite/ffi/build.py", line 105, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 6.0.x. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

    error: command '/usr/bin/python3' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-50714txv/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9nrave3l/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-50714txv/llvmlite/

If I use git and install from setup.py, while importing the librosa, i run into this error:
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/__init__.py", line 104, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python2.7/dist-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/librosa/util/utils.py", line 111, in <module>
    def valid_audio(y, mono=True):
  File "/usr/local/lib/python2.7/dist-packages/librosa/cache.py", line 49, in wrapper
    if self.cachedir is not None and self.level >= level:
  File "/usr/local/lib/python2.7/dist-packages/joblib-0.12.0-py2.7.egg/joblib/memory.py", line 847, in cachedir
    DeprecationWarning, stacklevel=2)
TypeError: expected string or buffer

On python3, librosa works just fine

**Comment by bmcfee** [comment] 2018-06-27 13:23
This is not actually a 2/3 error, but a duplicate of #729 . That has already been fixed here, but we haven't posted out the 0.6.2 release yet.  In the meantime, you can roll back joblib to 0.11 and it ought to work.

**Comment by ayushch3** [comment] 2018-06-28 12:11
I already rolled back joblib to 0.11, still running into the same error. I had actually looked at the issue #729
before posting issue here again

**Comment by bmcfee** [comment] 2018-06-28 14:16
I suspect something is amiss in your install/environment then.  If you have the current master branch installed, and joblib 0.12, you shouldn't see this error.  Our tests pass on py2.7 in this config, so I'm pretty sure whatever's wrong isn't internal to librosa.

If you have the stable version installed (via pip), then joblib with 0.11 should also work.  (Notwithstanding any llvm install errors, which you should definitely not see, but are also upstream of us.)

If you have current master with joblib 0.11, or pip stable with joblib 0.12, it will break in ways listed above.

If all else is failing, I suggest uninstalling librosa and joblib and starting fresh.  You might need to `pip uninstall librosa` multiple times if there are conflicting installations in your environment.

**Comment by bafonso** [comment] 2018-07-05 00:34
I was running into this problem too and replacing with 0.11 works.

`pip install 'joblib==0.11' --force-reinstall`

**Closed** 2018-08-03 18:51 UTC
Labels: already fixed

**Comment by xizhang37** [comment] 2020-01-30 17:59
You have to install librosa which version is down 1.7.0

**Comment by MitchellX** [comment] 2021-06-18 08:53
yes, you're right.

please make sure the version matching:
librosa==0.6
joblib==0.11
