### ISSUE TITLE
specshow custom xaxis

### ISSUE THREAD

**Issue by dizcza** [librosa/librosa#1746] opened 2023-09-02 19:18 UTC
**Is your feature request related to a problem? Please describe.**
I'm currently using the `specshow` function like so:
```python
hop_length = 128  # my audio data sampled at 1024 freq
stft = librosa.stft(Y, n_fft=2 * hop_length, hop_length=hop_length)
D = librosa.amplitude_to_db(np.abs(stft), ref=np.max)
img = librosa.display.specshow(D, y_axis='log', sr=1024,
hop_length=hop_length,
x_axis='time', ax=axes[-1])
```
But I'd like to pass the absolute time as X values rather than the duration since the start.
Basically, I'd like to shift the whole X range to represent the specific date a recording was made.

**Describe the solution you'd like**
I have an array of `datetime64[us]` datatype as X values that correspond to the Y values from which the matrix `D` has been computed. I'm not sure if passing these X values would be feasible but simply adding a starting date to the time duration would do the trick.

So either
1. add an option to set the starting date;
2. allow passing X values as the `xaxis`; this array must have the same dimension as the input Y.

**Comment by lostanlen** [comment] 2023-09-04 14:21
Hello @dizcza, indeed this is exactly #1364, more precissely, the follow-up plan of PR #1485.


1. support two new types in x_coords and y_coords: numpy array of datetime64 and timedelta64

2. support strftime formats in specshow (if "%" in x_axis:  branch)

3. write one utility function:  timedelta_like(X, sr, hop_length)
(i don’t think datetime_like(X, sr, hop_length, offset) is necessary because it’s just offset + timedelta_like(X, sr, hop_length) )
the one problem i see right now is that timedelta doesn’t speak strftime. it works well up from 0:00:00 to 23:59:59 but getting it to work for negative values and for durations above one day requires custom code
https://stackoverflow.com/a/63198084

**Comment by bmcfee** [comment] 2024-04-04 17:32
Closing this out as a duplicate of #1364, but noting here also that this is blocked upstream by matplotlib and not currently feasible.

**Closed by bmcfee** 2024-04-04 17:32 UTC
Labels: question
