### ISSUE TITLE
Getting an Error: ValueError: Input signal length=0 is too small to resample from 44100->22050 ,  while loading an mp3 file by librosa.load()

### ISSUE THREAD

**Issue by Soumendraprasad** [librosa/librosa#1622] opened 2022-12-13 06:49 UTC
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
Recently I am working with some audio data .  But the issue I am facing that 
while I am trying to load the audio file by **librosa.load()**.

**To Reproduce**

**Expected behavior**
**I am guessing that this error is may be happening as the x which should be 1-D numpy array , it is empty in this case. but why??**
**When I am playing the sound by Ipython ,It is working fine .**
![i4](https://user-images.githubusercontent.com/102607452/207244696-6c7d9677-32a8-41ea-83f5-d4ddb94f1fd2.png)
![i2](https://user-images.githubusercontent.com/102607452/207244068-548682ca-8e0c-4419-8c65-f2f65b197645.png)
![i3](https://user-images.githubusercontent.com/102607452/207244992-9c3a77f9-0730-43bf-8635-a751c2725238.png)

**Screenshots**

**Software versions***

Windows-10-10.0.22621-SP0
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
NumPy 1.22.3
SciPy 1.8.0
librosa 0.9.2
INSTALLED VERSIONS
------------------
python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]

librosa: 0.9.2

audioread: 3.0.0
numpy: 1.22.3
scipy: 1.8.0
sklearn: 1.0.2
joblib: 1.1.0
decorator: 5.1.1
soundfile: 0.11.0
resampy: 0.4.2
numba: 0.56.4
pooch: v1.6.0
packaging: 21.3

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib-svg2pdfconverter: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.5.1
samplerate: None
soxr: None
contextlib2: None
presets: None
**Additional context**
Please help me to fix this issue . As the x is getting store an empty numpy 1-D array I cann't able to proceed further .I am not getting it's solution no where .

**Comment by bmcfee** [comment] 2022-12-13 12:10
> **I am guessing that this error is may be happening as the x which should be 1-D numpy array , it is empty in this case. but why??**
> **When I am playing the sound by Ipython ,It is working fine .**

The problem is almost certainly with the audio file, but there's not enough information here to determine what exactly is wrong.  Are you able to load it with resampling disabled (`load(..., sr=None)`)?

**Comment by Soumendraprasad** [comment] 2022-12-13 13:45
@bmcfee , I think may be  there  is no error in the audio file , because I have tried some other audio files with .mp3 extension they are also giving same error  . 
To answer your question `Are you able to load it with resampling disabled (load(..., sr=None))?`
I had also tried this . Please have a look on this below image .
![i1](https://user-images.githubusercontent.com/102607452/207332488-3e1fbb27-b6e4-4480-99c5-687089085dcf.png)

We can observe that x is containing 'Null' data , So at time of resampling it is giving same error .But I don't think there is some issue with audio because, It has length of 2.5 min & also playing smoothly with IPython .
You could also download the audio file from below link.
[ Single sound Download Source ](https://www.cjoint.com/c/LGivxzQK0vN)
Waititng for youe reponse . As I am working with some **birds sound** , Librosa is very needed but I cann't going forward due to this .
You could also download some bird voice from below link & hope it will help you to figure out .
[The bird voice download link source page](https://xeno-canto.org/species/Struthio-camelus)

**Comment by bmcfee** [comment] 2022-12-13 13:49
Ok, so it's definitely an audio decoding error of some kind - possibly due to a corrupted file (maybe not), or due to whatever audio decoder librosa is using here.

I suggest updating your soundfile package and libsndfile installation to the latest available on conda.  These have built in mp3 support, and using them (instead of audioread + ffmpeg/gstreamer/whatever) will help narrow the problem down.

**Comment by Soumendraprasad** [comment] 2022-12-13 14:12
`your soundfile package and libsndfile installation to the latest available on conda`
@bmcfee , I am using  the `soundfile version:0.11.0` & it is the latest version . I am using windows pip environment not conda . According to documentation of soundfile libsndfile is installed automatically with soundfile . If I am wrong in some where , then kindly guide me .

**Comment by bmcfee** [comment] 2022-12-13 14:30
> I am using windows pip environment not conda

I believe the pypi (pip installable) build of soundfile is not compiled with mp3 support. This is why I specifically suggested the conda build.

It should be possible to install a version of libsndfile / soundfile without conda, but you'll have to build from source.

**Comment by ClementDecaux** [comment] 2022-12-14 18:32
I have exactly the same problem.

Using `mediainfo` from pydub.utils I can extract `start_time` value (I have no clue what it is. Imo, every file should start at 0.0 s but apparently they can extract this from metadata and it is related to something).

I **can load** every file for which `start_time` **is not 0.00**
I **can't load** every file for which `start_time` **is 0.00**

Can we validate this with your files and setup ?

```python
from pydub.utils import mediainfo
mediainfo(<file>)['start_time']
```

**Comment by Soumendraprasad** [comment] 2022-12-24 10:29
Hey @ClementDecaux , I think You Should try Using `Soundfile` .This May help You . If this will not work for you then there might be an error In That File . You Might Use My Dataset Which I had recently Uploaded On Kaggle With attached kernel .[Dataset Link](https://www.kaggle.com/datasets/soumendraprasad/sound-of-114-species-of-birds-till-2022)

Hope It will help You .

**Comment by Soumendraprasad** [comment] 2022-12-24 10:37
Hey @bmcfee , I am thinking to become an open Source Contributor Librosa . Is it possible ?? If possible , then kindly share some ways , I am wanting to solve other peoples query also . I think it is a great way to learn . And People are also facing some issues while working with audio files & the resources are also very less available now a days..

**Comment by sammlapp** [comment] 2023-01-10 15:10
@bmcfee I am experiencing this issue as well. Interestingly, it occurs with some mp3s but not others. I can't tell why or what the difference is so far. It seems to be an issue with mp3 files from xeno canto that I downloaded a long time (>1 yr?) ago. But if I download a file from xeno canto now, I can load it without the error.

The error is specifically that the file loads with an empty sample array: using load(...,sr=None) avoids the Exception caused by trying to resample and returns [] for samples. 

The mp3 files don't have any issue opening or playing back in Audacity or the mac system player. If I open the mp3 in Audacity and save it as a new file, it then loads fine. This does seem to suggest a "corruption" or incompatibility of the way the file was saved with how it's being loaded. 

Surprisingly (to me at least), loading the samples directly with soundfile works fine on a file where librosa loads zero samples
```
len(soundfile.read('file.mp3')[0]) # 319488
len(librosa.load('file.mp3',sr=None)[0]) # 0 
```

I currently have: librosa==0.9.2, soundfile==0.11.0. 

I'm not sure how to check libsndfile version actually.  

I'm on Apple Silicon M1 Pro chip with Mac OS 12.6

**Comment by sammlapp** [comment] 2023-01-10 15:37
Ooh, this is weird and interesting:
librosa.core.audio.__soundfile_load returns the sample array if dtype=None, but returns an empty array if dtype=float32

Not sure why that would happen, but could be the cause of the issue

**Comment by sammlapp** [comment] 2023-01-10 15:42
Ok, it looks like its a known issue with float64 vs float32 dtype in soundfile and libsndfile. [Libsndfile](https://github.com/libsndfile/libsndfile/issues/880) recently resolved the issue, and @bastibe says 

> That's good to hear! As soon as they libsndfile release a new version (and the build systems catch up, so we can actually use them), we'll push an update to soundfile as well.

in the soundfile [issue](https://github.com/bastibe/python-soundfile/issues/349)

**Comment by bastibe** [comment] 2023-01-11 09:10
Libsndfile did indeed just release a new version that should fix this issue. Alas, I haven't found time yet to recompile/release a new version of soundfile. But if you put a newer version of libsndfile in your load path, soundfile will pick the new one instead of the included one.

**Comment by bmcfee** [comment] 2023-01-13 17:16
Glad to hear this is resolved!  I'll close this one out here.

@bastibe I haven't rebuilt the conda-forge package for soundfile since the 1.2 release, do you think it's necessary?

**Comment by bastibe** [comment] 2023-01-14 08:17
I'll comment again when a new version of soundfile has been released. It has not happened, yet. With any luck, I'll get around to it next week.

**Comment by bmcfee** [comment] 2023-01-14 23:06
@bastibe sure, but what I meant to ask is whether issuing a new build of the current soundfile release (0.11.0) against 1.2 would resolve this?  Or is there something in soundfile that needs to be updated specifically to support the changes in 1.2?

**Comment by bastibe** [comment] 2023-01-15 10:53
It should be a drop-in replacement, but I haven't tested it yet.

**Comment by bmcfee** [comment] 2023-02-01 15:41
Circling back on this - I have an updated conda-forge recipe for soundfile to build against libsndfile 1.2.  It all appears to work - compiles, imports, etc - but I'm holding off on merging it and shipping the updated package build until there's some confirmation that it fixes the issue.

**Comment by bastibe** [comment] 2023-02-02 16:13
I am working on a new release of soundfile. However, neither I nor the Github CI have no access to an ARM Mac, so I can't compile a macOS version of libsndfile 1.2.0. If someone could help me out with that, check out [mac_build.sh](https://github.com/bastibe/libsndfile-binaries/blob/master/mac_build.sh), and push the compiled library in a pull request to [libsndfile-binaries](https://github.com/bastibe/libsndfile-binaries), that would help me a lot!

**Comment by bmcfee** [comment] 2023-02-02 16:51
@bastibe I don't have an ARM mac myself, but you might want to check out the conda-forge build recipe https://github.com/conda-forge/libsndfile-feedstock which includes osx-arm64 in the matrix and compiles on azure.  You might be able to yoink the binary directly from the conda package, though I suspect setting up your own azure CI might be preferable.

**Comment by bastibe** [comment] 2023-02-03 06:55
It appears that cross compilation on the Github CI might be just about ready, actually: https://github.com/bastibe/libsndfile-binaries/pull/16

**Comment by bastibe** [comment] 2023-02-06 13:01
The new release is just about ready: https://github.com/bastibe/python-soundfile/pull/364

If you could, please test-run the release to see if it works, and check that we are actually loading v1.2.0 in `soundfile.__libsndfile_version__`, and can indeed open MP3 files.

**Closed** 2023-02-16 18:42 UTC
Labels: Upstream/dependency bug

**Comment by code-leitianshuo** [comment] 2023-03-03 14:07
我也遇到了这个问题，我的音频可以正常使用播放器打开，但是无法使用librosa.load()打开，请作者尽快修复
