### ISSUE TITLE
error when loading the librosa example

### ISSUE THREAD

**Issue by lvbaouu** [librosa/librosa#765] opened 2018-10-01 22:46 UTC
#### Description

When I tried to load the example audio of librosa following the example code provided, I encountered an error of division by 0.

#### Steps/Code to Reproduce
```python
# I used the following code after importing librosa
filename = librosa.util.example_audio_file()
y, sr = librosa.load(filename)
y
# expected output: array([ -4.756e-06,  -6.020e-06, ...,  -1.040e-06,   0.000e+00], dtype=float32) 

```

but I got the following error:
```python
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-58-51ccf84ebac8> in <module>()
----> 1 y, sr = librosa.load(filename)

/anaconda2/lib/python2.7/site-packages/librosa/core/audio.pyc in load(path, sr, mono, offset, duration, dtype, res_type)
    158 
    159         if sr is not None:
--> 160             y = resample(y, sr_native, sr, res_type=res_type)
    161 
    162         else:

/anaconda2/lib/python2.7/site-packages/librosa/core/audio.pyc in resample(y, orig_sr, target_sr, res_type, fix, scale, **kwargs)
    277         return y
    278 
--> 279     ratio = float(target_sr) / orig_sr
    280 
    281     n_samples = int(np.ceil(y.shape[-1] * ratio))

ZeroDivisionError: float division by zero
```

**Comment by bmcfee** [comment] 2019-03-08 15:44
@lvbaouu did you ever get this working / figure out what the problem was?  I'm quite sure it's an upstream issue (i.e. in audioread), but I'd like to have confirmation before closing this.

**Comment by lvbaouu** [comment] 2019-03-19 16:17
yeah, it worked. sorry for the delayed response.

**Comment by bmcfee** [comment] 2019-03-19 16:37
Thanks for confirming.

**Closed by bmcfee** 2019-03-19 16:37 UTC
Labels: Upstream/dependency bug

**Comment by chanjeed** [comment] 2019-10-25 05:20
@lvbaouu  I am stuck with exact same issue with some of my mp3 files. Can you tell me how you fixed it?

**Comment by Rubix982** [comment] 2020-08-26 07:03
@bmcfee can you tell us how you solved it? I'm just going to go for a try - catch block right now.

**Comment by bmcfee** [comment] 2020-08-26 10:41
@Rubix982 there was no problem on our end, it was either an upstream bug as previously mentioned, or a corrupted file.

**Comment by Rubix982** [comment] 2020-08-26 11:16
@bmcfee understood, thank you. I've made an issue for audioread itself.

**Comment by Stapelueberflieger** [comment] 2020-11-19 16:29
**Description**
Same as original issue by @lvbaou : "When I tried to load the example audio of librosa following the example code provided, I encountered an error of division by 0."

**Steps/Code to Reproduce**
```
import librosa
filename = "test.wav"
y, sr = librosa.load(filename)
```
Details:
> Platform: Raspberry pi 1, Raspberry pi 2
> Python Version: 3.7

**Error:**
   ```
y = resample(y, sr_native, sr, res_type=res_type)
File "(...) env/lib/python3.7/site-packages/librosa/core/audio.py", line 584, in resample
y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=-1)
File "(...) env/lib/python3.7/site-packages/resampy/core.py", line 120, in resample
resample_f(x_2d, y_2d, sample_ratio, interp_win, interp_delta, precision)
ZeroDivisionError: integer division by zero

```
I assume dependency issue, but dont kow how to track it down. Unfortunately I dont know much about dependency management.

**Comment by Rubix982** [comment] 2020-11-19 16:56
@Stapelueberflieger can you share the audio clip somehow? Librosa parses those audio files. It clearly has an issue with the format. Is the audio clip corrupted? Not completely cut off as it is supposed to be? What the file format for that is, what the encoding is, etc etc.
An examine of what file exactly causes the issue for you would help to replicate the issue.

**Comment by Stapelueberflieger** [comment] 2020-11-19 17:05
@Rubix982 
I will change to a copyright free track so I can share it.
However, the same track worked with librosa on my desktop.
Thank you for your very fast reply 👍

**Comment by Stapelueberflieger** [comment] 2020-11-19 17:10
@Rubix982 I change from a wav file to [this mp3](https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Jazz_at_Mladost_Club/Jazz_Night/Jazz_at_Mladost_Club_-_05_-_Caravan.mp3?download=1) file, now I get 
```
UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
```
[Then loading for a long time]
`Killed`

**Comment by Rubix982** [comment] 2020-11-19 17:13
@Stapelueberflieger no problem! 
Hmm, interesting. There is something within the file itself.
Can you tell me, if it is playable - can you hear it via any sound software? Or does it through an error?

**Comment by alexcrist** [comment] 2021-06-08 00:43
I was able to fix this by explicitly setting the `sr` parameter of the `load` function

example
```
audio, sample_rate = load(filename, sr=44100)
```
