### ISSUE TITLE
Librosa import just stops and does nothing

### ISSUE THREAD

**Issue by DorianCreuze** [librosa/librosa#1620] opened 2022-12-10 23:30 UTC
I import librosa in my program using the following line
import librosa

and when I run my program it just stops there and does nothing, there is no error message so I can't give you any

here you see a screen shot of the beginning of my program and the output window
and as you can see the import librosa stop everything
![p](https://user-images.githubusercontent.com/114405894/206879330-97a0e46f-3c6e-4d88-a9ed-fb86030fbe06.png)

if you need more info just ask them

thank you

**Comment by lostanlen** [comment] 2022-12-11 21:37
Thanks. How did you install librosa? Are you using a virtual environment?

I see you're using Windows 10 ... can you try `import numba; numba.__version__` ?

**Comment by DorianCreuze** [comment] 2022-12-11 22:24
sorry I forgot to write a pretty important par, i'm using visual studio 2022.
numba's version is 0.56.4

**Comment by bmcfee** [comment] 2022-12-12 12:56
Sounds like a duplicate of https://github.com/librosa/librosa/issues/1576

IIRC the solution was that the user had installed librosa to a directory where there were no write permissions, so the numba cache could not be constructed.  The [numba documentation](https://numba.pydata.org/numba-doc/dev/reference/envvars.html#envvar-NUMBA_CACHE_DIR) should be helpful here if you want to change the cache path to something where you definitely have write access.

Note that importing numba would not be enough to detect this problem - you'd need to jit compile a function with caching enabled.

**Comment by bmcfee** [comment] 2022-12-13 14:00
Side note: if @DorianCreuze can confirm that this was the problem, it's probably worth adding an entry to the troubleshooting section of the docs to talk about this.

**Comment by bmcfee** [comment] 2023-01-16 15:10
Closing this out after a month with no activity.  Feel free to reopen if the diagnosis above turns out to be incorrect.

**Closed by bmcfee** 2023-01-16 15:10 UTC
Labels: question, Upstream/dependency bug
