### ISSUE TITLE
error when running tests using anaconda

### ISSUE THREAD

**Issue by chananshgong** [librosa/librosa#583] opened 2017-05-28 07:50 UTC
I am trying to run the master tests so I can contribute, but I get errors regarding mkl. I am using anaconda and I did `conda install mkl`. 

Any change you know how to solve this?

```
~/community/librosa$ nosetests --with-coverage --cover-package=librosa -w tests/
./home/hanan/anaconda3/lib/python3.6/site-packages/librosa/beat.py:210: DeprecationWarning: librosa.beat.estimate_tempo
        Deprecated as of librosa version 0.5.0.
        It will be removed in librosa version 0.6.
  @cache(level=30)
.................................................................................../home/hanan/anaconda3/lib/python3.6/site-packages/librosa/beat.py:210: DeprecationWarning: librosa.beat.estimate_tempo
        Deprecated as of librosa version 0.5.0.
        It will be removed in librosa version 0.6.
  @cache(level=30)
./home/hanan/anaconda3/lib/python3.6/site-packages/librosa/beat.py:210: DeprecationWarning: librosa.beat.estimate_tempo
        Deprecated as of librosa version 0.5.0.
        It will be removed in librosa version 0.6.
  @cache(level=30)
./home/hanan/anaconda3/lib/python3.6/site-packages/librosa/beat.py:210: DeprecationWarning: librosa.beat.estimate_tempo
        Deprecated as of librosa version 0.5.0.
        It will be removed in librosa version 0.6.
  @cache(level=30)
./home/hanan/anaconda3/lib/python3.6/site-packages/librosa/beat.py:210: DeprecationWarning: librosa.beat.estimate_tempo
        Deprecated as of librosa version 0.5.0.
        It will be removed in librosa version 0.6.
  @cache(level=30)
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................../home/hanan/anaconda3/lib/python3.6/site-packages/numpy/core/function_base.py:224: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  y = linspace(start, stop, num=num, endpoint=endpoint)
........................................................................................................................................................................................................................................................................................................................................................../home/hanan/anaconda3/lib/python3.6/site-packages/numpy/core/function_base.py:224: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  y = linspace(start, stop, num=num, endpoint=endpoint)
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................../home/hanan/anaconda3/lib/python3.6/site-packages/audioread/__init__.py:80: ResourceWarning: unclosed file <_io.BufferedReader name='/home/hanan/anaconda3/lib/python3.6/site-packages/librosa/util/example_data/Kevin_MacLeod_-_Vibe_Ace.ogg'>
  pass
/home/hanan/community/librosa/tests/test_core.py:77: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  res_type=res_type)
/home/hanan/community/librosa/tests/test_core.py:77: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  res_type=res_type)
/home/hanan/anaconda3/lib/python3.6/site-packages/audioread/__init__.py:80: ResourceWarning: unclosed file <_io.BufferedReader name='/home/hanan/anaconda3/lib/python3.6/site-packages/librosa/util/example_data/Kevin_MacLeod_-_Vibe_Ace.ogg'>
  pass
/home/hanan/community/librosa/tests/test_core.py:85: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  res_type=res_type)
/home/hanan/community/librosa/tests/test_core.py:85: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  res_type=res_type)
./home/hanan/anaconda3/lib/python3.6/site-packages/audioread/__init__.py:80: ResourceWarning: unclosed file <_io.BufferedReader name='/home/hanan/anaconda3/lib/python3.6/site-packages/librosa/util/example_data/Kevin_MacLeod_-_Vibe_Ace.ogg'>
  pass
/home/hanan/community/librosa/tests/test_core.py:77: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  res_type=res_type)
/home/hanan/community/librosa/tests/test_core.py:77: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  res_type=res_type)
/home/hanan/anaconda3/lib/python3.6/site-packages/audioread/__init__.py:80: ResourceWarning: unclosed file <_io.BufferedReader name='/home/hanan/anaconda3/lib/python3.6/site-packages/librosa/util/example_data/Kevin_MacLeod_-_Vibe_Ace.ogg'>
  pass
/home/hanan/community/librosa/tests/test_core.py:85: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  res_type=res_type)
/home/hanan/community/librosa/tests/test_core.py:85: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  res_type=res_type)
./home/hanan/anaconda3/lib/python3.6/site-packages/audioread/__init__.py:80: ResourceWarning: unclosed file <_io.BufferedReader name='/home/hanan/anaconda3/lib/python3.6/site-packages/librosa/util/example_data/Kevin_MacLeod_-_Vibe_Ace.ogg'>
  pass
/home/hanan/community/librosa/tests/test_core.py:77: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  res_type=res_type)
/home/hanan/community/librosa/tests/test_core.py:77: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  res_type=res_type)
/home/hanan/anaconda3/lib/python3.6/site-packages/audioread/__init__.py:80: ResourceWarning: unclosed file <_io.BufferedReader name='/home/hanan/anaconda3/lib/python3.6/site-packages/librosa/util/example_data/Kevin_MacLeod_-_Vibe_Ace.ogg'>
  pass
/home/hanan/community/librosa/tests/test_core.py:85: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  res_type=res_type)
/home/hanan/community/librosa/tests/test_core.py:85: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  res_type=res_type)
...................................................................................................................................................................................................................................................Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

**Comment by bmcfee** [comment] 2017-05-28 15:30
Can you run this again with `nosetests -v` so we can see exactly which test is triggering the failure?

Since librosa doesn't have any direct content with BLAS or compiled code, I suspect the problem is with one of the dependencies that does, either numpy, scipy, or sklearn.

**Comment by bmcfee** [comment] 2017-09-28 18:14
This issue is almost certainly out of scope for librosa, and idiosyncratic to the reporter's specific setup.  I'll close this, but feel free to re-open if there's some action we need to take.

**Closed by bmcfee** 2017-09-28 18:14 UTC
