### ISSUE TITLE
Loading fragments of file is slow in newer version

### ISSUE THREAD

**Issue by sammlapp** [librosa/librosa#1550] opened 2022-08-08 16:45 UTC
**Describe the bug**
Loading a piece of a longer audio file is much slower in v0.9.2 than it was in v0.8.1. For instance, loading a 2-hour wav file takes 440 ms, and loading the first 5 seconds using librosa 0.8.1 only takes about 1 ms. However, in the 0.9.2 package version, loading the first 5 seconds is taking about 130 ms. 

Apologies if this is a duplicate issue, I have not found a similar one when searching the issues. 

**To Reproduce**

```
import librosa
from time import time

t=time()
librosa.load('two_hour_file.wav') 
print(time()-t) # 440 ms, good

t=time()
librosa.load('two_hour_file.wav',offset=0,duration=2)
print(time()-t) # 130 ms, slow! 

```

**Expected behavior**
Loading a short piece of audio should be very fast, as it was in previous package versions.

**Software versions**
```
Linux-5.15.0-43-generic-x86_64-with-glibc2.17
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0]
NumPy 1.22.0
SciPy 1.9.0
librosa 0.9.2
INSTALLED VERSIONS
------------------
python: 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0]

librosa: 0.9.2

audioread: 2.1.9
numpy: 1.22.0
scipy: 1.9.0
sklearn: 1.1.2
joblib: 1.1.0
decorator: 5.1.1
soundfile: 0.10.3
resampy: 0.3.1
numba: 0.56.0
pooch: v1.6.0
packaging: 21.3

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib-svg2pdfconverter: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.5.2
samplerate: None
soxr: None
contextlib2: installed, no version number available
presets: None
```

**Comment by agkphysics** [comment] 2022-08-12 01:49
I can confirm that loading is significantly slower in 0.9.2, even with resampy 0.4.0.

I have an audio file which is ~2 sec and 60 KB. The below code reports 6.7 seconds with librosa 0.9.2 and only 0.0076 seconds with 0.9.1!

```python
import time

import librosa


start_time = time.perf_counter()
for _ in range(100):
    librosa.load("audio.wav", sr=None)
total_time = time.perf_counter() - start_time
print(total_time)
```

**Comment by bmcfee** [comment] 2022-08-12 02:20
Loading with sr=None bypasses all sample rate conversion, so resampy is not a factor here.

I'm very puzzled by this behavior. There's nothing in the diff from 0.9.1 to 0.9.2 that should have anything to do with loading time. Are you certain that the environment and all dependencies are all otherwise the same?

**Comment by agkphysics** [comment] 2022-08-12 06:46
I believe the issue may be with calling `audioread.available_backends()`:
https://github.com/librosa/librosa/blob/b9830b4a335b1e7e4be66ee81870573bf3d516d0/librosa/core/audio.py#L158

A quick test in IPython shows this call is adding ~50 ms to each call of `load()`:
```ipython
In [1]: import audioread

In [2]: %timeit audioread.available_backends()
52.9 ms ± 374 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
I believe the reason is because it's trying to find various libraries. I did a profile and found that `ctypes.util.find_library()` is taking about 29 ms each call.

Perhaps it would be better to cache the available backends upon import of librosa? It's called again in `__audioread_load()`:
https://github.com/librosa/librosa/blob/b9830b4a335b1e7e4be66ee81870573bf3d516d0/librosa/core/audio.py#L221

**Comment by bmcfee** [comment] 2022-08-12 11:48
> I believe the issue may be with calling `audioread.available_backends()`:

Ah! Excellent sleuthing.  Yes, I agree that this is probably the culprit.


> Perhaps it would be better to cache the available backends upon import of librosa? It's called again in `__audioread_load()`:

That would work, but I think it might cause us more problems in the future as we begin to phase out audioread.

A better option might be to patch audioread to cache the backend list after the first query.  I think this would be easy to do:

https://github.com/beetbox/audioread/blob/ee68207c86ac6d2ca67cf0e23d6f0732f8aadbbb/audioread/__init__.py#L63-L68

**Comment by bmcfee** [comment] 2022-08-12 12:08
I hacked out a quick test of the backend cache idea, and it does bring timing down considerably (~3µs from tens of milliseconds).  Raised an issue over at beetbox/audioread#125 - can do a PR for it later if they're interested.

**Comment by bmcfee** [comment] 2022-08-12 18:30
https://github.com/beetbox/audioread/pull/126 is merged and should fix this issue for you, if you're willing to run on a development version of audioread.

**Comment by agkphysics** [comment] 2022-08-12 23:23
Yes I can confirm that with `audioread==3.0.0` the audio loading times are the fast for both `librosa==0.9.2` and `librosa==0.9.1`.

**Closed** 2022-08-12 23:37 UTC
Labels: IO
