### ISSUE TITLE
meet problem "audioread.ffdec.ReadTimeoutError: ffmpeg output:",need your help

### ISSUE THREAD

**Issue by sunnnnnnnny** [librosa/librosa#975] opened 2019-08-23 10:35 UTC
I use librosa to read the m4a files to process them. The program will always interrupt during processing and report the following error. I also tried the file name corresponding to .m4a when the error was reported. There is no problem in the command line librosa.load. It is very strange that I have stuck on this issue for two days and need your help.
Here are some package versions:
platfom : 'Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.3.1611-Core'
sys : '3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) \n[GCC 7.3.0]'
numpy:'1.17.0'
scipy: '1.3.1'
librosa:'0.6.1'

`Traceback (most recent call last):
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 167, in read_data
    data = self.stdout_reader.queue.get(timeout=timeout)
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "encoder_preprocess.py", line 61, in <module>
    preprocess_func[dataset](**args)
  File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/encoder/preprocess.py", line 245, in preprocess_voxceleb2
    _preprocess_speaker_dirs(speaker_dirs, dataset_name, datasets_root, out_dir, "m4a",skip_existing, logger)
  File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/encoder/preprocess.py", line 156, in _preprocess_speaker_dirs
    list(tqdm(map(preprocess_speaker, speaker_dirs), dataset_name, len(speaker_dirs), unit="speakers"))
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py", line 594, in __iter__
  File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/encoder/preprocess.py", line 117, in preprocess_speaker
    wav = audio.preprocess_wav(in_fpath)
  File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/encoder/audio.py", line 29, in preprocess_wav
    wav, source_sr = librosa.load(fpath_or_wav, sr=None)
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/site-packages/librosa/core/audio.py", line 126, in load
    for frame in input_file:
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 181, in read_data
    ''.join(self.stderr_reader.queue.queue)
audioread.ffdec.ReadTimeoutError: ffmpeg output:`

**Comment by lostanlen** [comment] 2019-08-23 11:53
Is this a duplicate of #928?

**Comment by bmcfee** [comment] 2019-08-23 12:32
I believe it is, and that it's still a problem with the ffmpeg installation.  @sunnnnnnnny never responded to my questions in the last issue, so it's difficult to diagnose

**Comment by sunnnnnnnny** [comment] 2019-08-23 14:38
@bmcfee  sorry,I am really sorry, the same problem happened to me twice. I didn’t even notice that the memory was too bad. I will perfect the issue template today and apologize to you again.

**Comment by sunnnnnnnny** [comment] 2019-08-23 15:06
@bmcfee 
#### Description
First of all, I multi-threaded the first data set v1 (wav file) can pass smoothly, no bugs; when I use multi-threaded processing data set v2 (m4a file), the above mentioned bug will appear in the process I suspect that it is a multi-threaded problem. I changed the code to single-threaded. I still have this problem, so I suspect that Librosa is compatible with the m4a type. This is just my guess.
#### Steps/Code to Reproduce
`
def _preprocess_speaker_dirs(speaker_dirs, dataset_name, datasets_root, out_dir, extension,skip_existing, logger):
    print("%s: Preprocessing data for %d speakers." % (dataset_name, len(speaker_dirs)))
    
    # Function to preprocess utterances for one speaker
    def preprocess_speaker(speaker_dir: Path):
        # Give a name to the speaker that includes its dataset
        speaker_name = "_".join(speaker_dir.relative_to(datasets_root).parts)
        # speaker_dir = PosixPath('/mnt/lustre/aifs/home/sw122/import/sid/voxceleb2/dev/aac/id05199')
        # datasets_root = PosixPath('/mnt/lustre/aifs/home/sw122/import/sid')
        # speaker_name = 'voxceleb2_dev_aac_id05199'

        # Create an output directory with that name, as well as a txt file containing a 
        # reference to each source file.
        speaker_out_dir = out_dir.joinpath(speaker_name)
        # speaker_out_dir = PosixPath('SV2TTS/v2/voxceleb2_dev_aac_id05199')
        speaker_out_dir.mkdir(exist_ok=True)
        sources_fpath = speaker_out_dir.joinpath("_sources.txt")

        # PosixPath('SV2TTS/v2/voxceleb2_dev_aac_id05199/_sources.txt')
        
        # There's a possibility that the preprocessing was interrupted earlier, check if 
        # there already is a sources file.
        if sources_fpath.exists():
            try:
                with sources_fpath.open("r") as sources_file:
                    existing_fnames = {line.split(",")[0] for line in sources_file}
            except:
                existing_fnames = {}
        else:
            existing_fnames = {}
        
        # Gather all audio files for that speaker recursively
        sources_file = sources_fpath.open("a" if skip_existing else "w")
        #  sources_file = <_io.TextIOWrapper name='SV2TTS/v2/voxceleb2_dev_aac_id05199/_sources.txt' mode='w' encoding='UTF-8'>
        for in_fpath in speaker_dir.glob("**/*.%s" % extension):
            #print(in_fpath)
            # Check if the target output file already exists
            # speaker_dir=PosixPath('/mnt/lustre/aifs/home/sw122/import/sid/voxceleb2/dev/aac/id05199')
            # in_fpath=PosixPath('/mnt/lustre/aifs/home/sw122/import/sid/voxceleb2/dev/aac/id05199/cf844ZGXE-k/00104.m4a')
            #print("in_fpath:",in_fpath)
            out_fname = "_".join(in_fpath.relative_to(speaker_dir).parts)
            # out_fname = 'cf844ZGXE-k_00104.m4a'
            out_fname = out_fname.replace(".%s" % extension, ".npy")
            #print("out_fname:",out_fname)
            # out_fname=  'cf844ZGXE-k_00104.npy'
            if skip_existing and out_fname in existing_fnames:
                continue
                
            # Load and preprocess the waveform
            wav = audio.preprocess_wav(in_fpath)
            if len(wav) == 0:
                continue
            
            # Create the mel spectrogram, discard those that are too short
            frames = audio.wav_to_mel_spectrogram(wav)
            if len(frames) < partials_n_frames:
                continue
            
            out_fpath = speaker_out_dir.joinpath(out_fname)
            # speaker_out_dir= PosixPath('SV2TTS/v2/voxceleb2_dev_aac_id05199')
            # out_fname = 'cf844ZGXE-k_00104.npy'
            # out_fpath= PosixPath('SV2TTS/v2/voxceleb2_dev_aac_id05199/cf844ZGXE-k_00104.npy')
            np.save(out_fpath, frames)
            #print("save success")
            logger.add_sample(duration=len(wav) / sampling_rate)
            sources_file.write("%s,%s\n" % (out_fname, in_fpath))
        
        sources_file.close()
    
    #with ThreadPool(30) as pool:
    #list(tqdm(pool.imap(preprocess_speaker, speaker_dirs), dataset_name, len(speaker_dirs),unit="speakers"))
    list(tqdm(map(preprocess_speaker, speaker_dirs), dataset_name, len(speaker_dirs), unit="speakers"))
    print("Done preprocessing %s.\n" % dataset_name)
`
#### Expected Results
Completely processed more than 80GB m4a files without error
#### Actual Results
`
Traceback (most recent call last):
File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 167, in read_data
data = self.stdout_reader.queue.get(timeout=timeout)
File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/queue.py", line 172, in get
raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "encoder_preprocess.py", line 61, in 
preprocess_funcdataset
File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/encoder/preprocess.py", line 245, in preprocess_voxceleb2
_preprocess_speaker_dirs(speaker_dirs, dataset_name, datasets_root, out_dir, "m4a",skip_existing, logger)
File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/encoder/preprocess.py", line 156, in _preprocess_speaker_dirs
list(tqdm(map(preprocess_speaker, speaker_dirs), dataset_name, len(speaker_dirs), unit="speakers"))
File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py", line 594, in iter
File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/encoder/preprocess.py", line 117, in preprocess_speaker
wav = audio.preprocess_wav(in_fpath)
File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/encoder/audio.py", line 29, in preprocess_wav
wav, source_sr = librosa.load(fpath_or_wav, sr=None)
File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/site-packages/librosa/core/audio.py", line 126, in load
for frame in input_file:
File "/mnt/lustre/aifs/home/yqz05/miniconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 181, in read_data
''.join(self.stderr_reader.queue.queue)
audioread.ffdec.ReadTimeoutError: ffmpeg output:
`
#### Versions
platfom : 'Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.3.1611-Core'
sys : '3.6.7 | packaged by conda-forge | (default, Jul 2 2019, 02:18:42) \n[GCC 7.3.0]'
numpy:'1.17.0'
scipy: '1.3.1'
librosa:'0.6.1'

I am in trouble, I hope to get your help and reply.

**Comment by bmcfee** [comment] 2019-08-23 19:55
> First of all, I multi-threaded the first data set v1 (wav file) can pass smoothly, no bugs; when I use multi-threaded processing data set v2 (m4a file), the above mentioned bug will appear in the process I suspect that it is a multi-threaded problem. I changed the code to single-threaded. I still have this problem, so I suspect that Librosa is compatible with the m4a type.

This is not a librosa problem -- if the file won't load, it's because audioread is unable to decode it.  It appears to be using the ffmpeg backend, which means (probably) that ffmpeg can't decode it either.  That to me says that the file itself is corrupt.  I suggest putting some debug prints in to track down exactly which file is causing problems.

**Closed** 2019-09-04 14:53 UTC
Labels: Upstream/dependency bug
