### ISSUE TITLE
Computing melspectrogram (so as some other features) hangs only with joblib(n_jobs >= 2)

### ISSUE THREAD

**Issue by keunwoochoi** [librosa/librosa#381] opened 2016-07-01 04:05 UTC
The original code is redundant, but it can be summarised as below.
```
...
   Parallel(n_jobs=N_JOBS)(delayed(convert)(path) for path in paths)
...

def convert(path):
    x, sr = librosa.load(path)
    X = librosa.feature.melspectrogram(x)
```
* It's okay when N_JOB = 1.
* Also okay if the function is directly called.
* STFT/CQT works fine.

I just checked out other librosa.feature functions.
* `chroma_*, spectral_*, tonnetz, zero crossing`: working well
* `mfcc, melspectrogram, poly_feature, tempogram`: hangs

Is it a known problem (if it's a problem)? I tested it after `pip install librosa --upgrade`, i.e. version 0.4.3 .

**Comment by dawenl** [comment] 2016-07-01 04:17
Does joblib hang even without librosa (but with numpy)? It's a known problem that joblib can conflict with some blas (e.g. openblas) with multiprocessing. If you are using openblas, the following works for me:

```
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'
```

**Comment by keunwoochoi** [comment] 2016-07-01 04:30
Hm, I thought that was only if I use `multiprocessing` but perhaps whatever they are if it does multiprocessing (which is so annoying).
With the option it still hangs,

The test was on MacOS so far, but on ubuntu it's the same. :(

**Comment by stefan-balke** [comment] 2016-07-01 08:01
Got the same problem last week.

On MacOS `joblib` and `numpy` have their problems.

The solution: Use `joblib`'s `forkserver` like this:

`(py3) bash$ JOBLIB_START_METHOD='forkserver' python foo.py`

This will set the variable `JOBLIB_START_METHOD` to `forkserver` for this python VM. This is a little bit slower due to more overhead but at least it works...

Have fun!

**Comment by keunwoochoi** [comment] 2016-07-01 15:24
That gives me a good reason to move from python2.7 to 3.4.. I'll try, thanks!

**Comment by bmcfee** [comment] 2016-07-01 15:27
Strange -- I've never had this problem, but thanks for reporting it here.

**Comment by keunwoochoi** [comment] 2016-07-19 01:45
> The test was on MacOS so far, but on ubuntu it's the same. :(
No, it is not the same, with python 2.7 and ubuntu 14.04 it's okay. 

I tried what @stefan-balke proposed - with python2.7 - on mac and it didn't work, haven't test on 3 yet.

**Comment by stefan-balke** [comment] 2016-07-20 09:01
Sorry, no experience with Python 2.7 and `joblib` but at some point, @faroit said he had problems when using it...

**Comment by faroit** [comment] 2016-07-21 09:39
@keunwoochoi I cannot really remember what caused the problems but I am using standard python multiprocessing instead of joblib since then. There I found that some problems are caused by pickling errors. Those can sometimes be solved by using [dill](https://github.com/uqfoundation/dill)

**Comment by bmcfee** [comment] 2016-09-23 19:28
Since this is a numpy/joblib issue, and not librosa, I'm closing this out.

**Closed by bmcfee** 2016-09-23 19:28 UTC
Labels: discussion, question, wontfix
