### ISSUE TITLE
OSError: file not found

### ISSUE THREAD

**Issue by JoeyChuuichi** [librosa/librosa#899] opened 2019-06-16 11:49 UTC
#### Description
I face a problem when I follow the tutorial:
```python
# Beat tracking example
from __future__ import print_function
import librosa

# 1. Get the file path to the included audio example
filename = librosa.util.example_audio_file()

# 2. Load the audio as a waveform `y`
#    Store the sampling rate as `sr`
y, sr = librosa.load(filename)

# 3. Run the default beat tracker
tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)

print('Estimated tempo: {:.2f} beats per minute'.format(tempo))

# 4. Convert the frame indices of beat events into timestamps
beat_times = librosa.frames_to_time(beat_frames, sr=sr)

print('Saving output to beat_times.csv')
librosa.output.times_csv('beat_times.csv', beat_times)


```

#### Expected Results

It may run without error
#### Actual Results

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhongyi/anaconda3/envs/tf-torch/lib/python3.6/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/zhongyi/anaconda3/envs/tf-torch/lib/python3.6/site-packages/audioread/__init__.py", line 111, in audio_open
    return ffdec.FFmpegAudioFile(path)
  File "/home/zhongyi/anaconda3/envs/tf-torch/lib/python3.6/site-packages/audioread/ffdec.py", line 150, in __init__
    self._get_info()
  File "/home/zhongyi/anaconda3/envs/tf-torch/lib/python3.6/site-packages/audioread/ffdec.py", line 206, in _get_info
    raise IOError('file not found')
OSError: file not found

```

#### Versions

```
>>> import platform; print(platform.platform())
Linux-4.15.0-51-generic-x86_64-with-debian-buster-sid
>>> import sys; print("Python", sys.version)
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.13.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.1.0
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.3

```

**Comment by JoeyChuuichi** [comment] 2019-06-16 11:55
I install it through
```
conda install -c conda-forge librosa
```

**Comment by JoeyChuuichi** [comment] 2019-06-16 12:00
I have tried to create a new conda env, which install the package by
```
pip install librosa
```
And it works.

However, I am not sure why installation through conda cannot work. 
And I uninstall through
```
conda uninstall librosa
```
Then reinstall through ```pip``` does not work

**Comment by lostanlen** [comment] 2019-06-16 22:29
what is the output of
```
print(librosa.util.example_audio_file())
```
?

**Comment by JoeyChuuichi** [comment] 2019-06-17 04:04
> what is the output of
> 
> ```
> print(librosa.util.example_audio_file())
> ```
> 
> ?

```python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
>>> print(librosa.util.example_audio_file())
/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/librosa/util/example_data/Kevin_MacLeod_-_Vibe_Ace.ogg

```

**Comment by lostanlen** [comment] 2019-06-17 15:31
@JoeyChuuichi can you try opening another OGG file at a different location and make sure that the loading still fails? If that is the case, then it's a missing codec error, not a filesystem error.

**Comment by JoeyChuuichi** [comment] 2019-06-18 04:56
@lostanlen 

I used the .ogg file in this link: https://commons.wikimedia.org/wiki/File:Example.ogg
```
>>> import os
>>> import librosa
>>> filename = 'Example.ogg'
>>> os.path.exists(filename)
True
>>> y, sr = librosa.load(filename)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/__init__.py", line 111, in audio_open
    return ffdec.FFmpegAudioFile(path)
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 150, in __init__
    self._get_info()
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 206, in _get_info
    raise IOError('file not found')
OSError: file not found

```

**Comment by lostanlen** [comment] 2019-06-18 12:13
@JoeyChuuichi thank you. So it's definitely a missing codec.

Please make sure that FFMPEG is installed in your conda environment:
`conda install -c conda-forge ffmpeg`

Please read this part of the documentation:
https://github.com/librosa/librosa#audioread-and-mp3-support

And/or this issue: #219

**Comment by JoeyChuuichi** [comment] 2019-06-18 14:18
@lostanlen 
It seems that it does not work
```

(py36) zhongyi@zhongyi-XPS-15-9560:~$ sudo apt-get install ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ffmpeg is already the newest version (7:3.4.6-0ubuntu0.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 88 not upgraded.
(py36) zhongyi@zhongyi-XPS-15-9560:~$ conda install -c conda-forge ffmpeg
Collecting package metadata: done
Solving environment: done

# All requested packages already installed.

(py36) zhongyi@zhongyi-XPS-15-9560:~$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
>>> 
>>> # 1. Get the file path to the included audio example
... filename = librosa.util.example_audio_file()
>>> 
>>> # 2. Load the audio as a waveform `y`
... #    Store the sampling rate as `sr`
... y, sr = librosa.load(filename)
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/__init__.py", line 111, in audio_open
    return ffdec.FFmpegAudioFile(path)
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 150, in __init__
    self._get_info()
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 206, in _get_info
    raise IOError('file not found')
OSError: file not found

```

**Comment by lostanlen** [comment] 2019-06-18 21:17
can you install it within a conda environment?

**Comment by JoeyChuuichi** [comment] 2019-06-19 02:35
@lostanlen 
Actually I can, but must install through ```pip install librosa``` at the very beginning.

The problem is once I install through ``` conda install -c conda-forge librosa``` I cannot find any way that can install it correctly. I mean even through ```conda uninstall``` and then ```pip install```

**Comment by bmcfee** [comment] 2019-06-19 16:43
This problem is most likely coming from upstream (audioread) and not librosa.

I suspect there is some dependency chain failure because you installed by pip instead of conda.  Pip can only really track dependencies of python packages, so it won't be able to tell if ffmpeg is available or not.

I recommend that you not use pip for this, since you're already in a conda environment.  If `conda install -c conda-forge libroas` is not working for you, that's a separate problem, and we should fix it, but you didn't say why exactly it doesn't work.

**Comment by JoeyChuuichi** [comment] 2019-06-20 04:45
> This problem is most likely coming from upstream (audioread) and not librosa.
> 
> I suspect there is some dependency chain failure because you installed by pip instead of conda. Pip can only really track dependencies of python packages, so it won't be able to tell if ffmpeg is available or not.
> 
> I recommend that you not use pip for this, since you're already in a conda environment. If `conda install -c conda-forge libroas` is not working for you, that's a separate problem, and we should fix it, but you didn't say why exactly it doesn't work.

Sorry I cannot understand it.
On my test, ```pip``` works while ```conda install``` does not work. See https://github.com/librosa/librosa/issues/899#issuecomment-502445834

Could you please be more specific about what I should do to provide you more detail information about the problem?

**Comment by bmcfee** [comment] 2019-06-20 13:40
@JoeyChuuichi , all you say is that it doesn't work.  What kind of error does it give?

**Comment by JoeyChuuichi** [comment] 2019-06-21 01:23
@bmcfee 
Here is the error message
```
(py36) zhongyi@zhongyi-XPS-15-9560:~$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
>>> 
>>> # 1. Get the file path to the included audio example
... filename = librosa.util.example_audio_file()
>>> 
>>> # 2. Load the audio as a waveform `y`
... #    Store the sampling rate as `sr`
... y, sr = librosa.load(filename)
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/__init__.py", line 111, in audio_open
    return ffdec.FFmpegAudioFile(path)
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 150, in __init__
    self._get_info()
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 206, in _get_info
    raise IOError('file not found')
OSError: file not found
```

**Comment by lostanlen** [comment] 2019-06-21 12:34
@JoeyChuuichi what's the output of 
```
source activate py36
conda install -c conda-forge librosa
```

?

**Comment by JoeyChuuichi** [comment] 2019-06-21 12:42
@lostanlen 
```
(base) zhongyi@zhongyi-XPS-15-9560:~$ conda activate py36
(py36) zhongyi@zhongyi-XPS-15-9560:~$ conda install -c conda-forge librosa
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/zhongyi/anaconda3/envs/py36

  added / updated specs:
    - librosa


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-2.7                   |         openblas           6 KB  conda-forge
    certifi-2019.6.16          |           py36_0         148 KB  conda-forge
    liblapacke-3.8.0           |       7_openblas           6 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         160 KB

The following NEW packages will be INSTALLED:

  liblapacke         conda-forge/linux-64::liblapacke-3.8.0-7_openblas

The following packages will be UPDATED:

  blas                         pkgs/main::blas-1.0-openblas --> conda-forge::blas-2.7-openblas
  ca-certificates    pkgs/main::ca-certificates-2019.5.15-0 --> conda-forge::ca-certificates-2019.6.16-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.0.2s-h7b6447c_0 --> conda-forge::openssl-1.0.2r-h14c3975_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi-2019.6.16    | 148 KB    | ##################################### | 100% 
blas-2.7             | 6 KB      | ##################################### | 100% 
liblapacke-3.8.0     | 6 KB      | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(py36) zhongyi@zhongyi-XPS-15-9560:~$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
>>> filename = librosa.util.example_audio_file()
>>> 
>>> # 2. Load the audio as a waveform `y`
... #    Store the sampling rate as `sr`
... y, sr = librosa.load(filename)
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/__init__.py", line 111, in audio_open
    return ffdec.FFmpegAudioFile(path)
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 150, in __init__
    self._get_info()
  File "/home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/audioread/ffdec.py", line 206, in _get_info
    raise IOError('file not found')
OSError: file not found

```

**Comment by lostanlen** [comment] 2019-06-21 12:57
OK so then please run:

```
pip uninstall librosa
conda install -c conda-forge librosa
```

**Comment by JoeyChuuichi** [comment] 2019-06-21 13:01
@lostanlen 
```
(base) zhongyi@zhongyi-XPS-15-9560:~$ conda activate py36
(py36) zhongyi@zhongyi-XPS-15-9560:~$ pip uninstall librosa
Uninstalling librosa-0.6.3:
  Would remove:
    /home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/librosa-0.6.3.dist-info/*
    /home/zhongyi/anaconda3/envs/py36/lib/python3.6/site-packages/librosa/*
Proceed (y/n)? y
  Successfully uninstalled librosa-0.6.3
(py36) zhongyi@zhongyi-XPS-15-9560:~$ conda install -c conda-forge librosa
Collecting package metadata: done
Solving environment: done

# All requested packages already installed.

(py36) zhongyi@zhongyi-XPS-15-9560:~$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'librosa'
>>> 
>>> # 1. Get the file path to the included audio example
... filename = librosa.util.example_audio_file()
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'librosa' is not defined
>>> 
>>> # 2. Load the audio as a waveform `y`
... #    Store the sampling rate as `sr`
... y, sr = librosa.load(filename)
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
NameError: name 'librosa' is not defined

```

**Comment by lostanlen** [comment] 2019-06-21 13:03
ok so here we have a problem. can you do
```
which python
which conda
conda list
```
?

**Comment by JoeyChuuichi** [comment] 2019-06-21 13:04
@lostanlen 
```
(py36) zhongyi@zhongyi-XPS-15-9560:~$ which python
/home/zhongyi/anaconda3/envs/py36/bin/python
(py36) zhongyi@zhongyi-XPS-15-9560:~$ which conda
/home/zhongyi/anaconda3/bin/conda
(py36) zhongyi@zhongyi-XPS-15-9560:~$ conda list
# packages in environment at /home/zhongyi/anaconda3/envs/py36:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl  
absl-py                   0.7.1                    py36_0  
astor                     0.7.1                    py36_0  
attrs                     19.1.0                   py36_1  
audioread                 2.1.8                    pypi_0    pypi
backcall                  0.1.0                    py36_0  
blas                      2.7                    openblas    conda-forge
bleach                    3.1.0                    py36_0  
bzip2                     1.0.6             h14c3975_1002    conda-forge
c-ares                    1.15.0               h7b6447c_1  
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py36_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.4.0                    py36_1  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py36_0  
expat                     2.2.5             hf484d3e_1002    conda-forge
ffmpeg                    3.4.1                         0    conda-forge
fontconfig                2.11.1                        6  
freetype                  2.5.5                         2  
gast                      0.2.2                    py36_0  
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.53.5                        1    conda-forge
gmp                       6.1.2                h6c8ec71_1  
grpcio                    1.14.1           py36h9ba97e2_0  
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
h5py                      2.9.0            py36h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
icu                       54.1                          0  
ipykernel                 5.1.0            py36h39e3cac_0  
ipython                   7.5.0            py36h39e3cac_0  
ipython_genutils          0.2.0                    py36_0  
jedi                      0.13.3                   py36_0  
jinja2                    2.10.1                   py36_0  
joblib                    0.13.2                   pypi_0    pypi
jpeg                      8d                            2  
jsonschema                3.0.1                    py36_0  
jupyter_client            5.2.4                    py36_0  
jupyter_core              4.4.0                    py36_0  
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.1.0                      py_1  
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
liblapacke                3.8.0                7_openblas    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.8.0                hd408876_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.4                         0  
llvmlite                  0.29.0                   pypi_0    pypi
markdown                  3.1.1                    py36_0  
markupsafe                1.1.1            py36h7b6447c_0  
matplotlib                2.0.2               np113py36_0  
mistune                   0.8.4            py36h7b6447c_0  
mock                      3.0.5                    py36_0  
nb_conda                  2.2.1                    py36_0  
nb_conda_kernels          2.2.1                    py36_0  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py36_0  
notebook                  5.7.8                    py36_0  
numba                     0.44.0                   pypi_0    pypi
numpy                     1.16.4                   pypi_0    pypi
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.0.2r               h14c3975_0    conda-forge
pandas                    0.24.2           py36he6710b0_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py36_1  
parso                     0.4.0                      py_0  
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.7.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pip                       19.1.1                   py36_0  
prometheus_client         0.6.0                    py36_0  
prompt_toolkit            2.0.9                    py36_0  
protobuf                  3.8.0            py36he6710b0_0  
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                    py36_0  
pygments                  2.4.0                      py_0  
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
pyrsistent                0.14.11          py36h7b6447c_0  
python                    3.6.0                         0  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1              py36h7b6447c_0  
pyzmq                     18.0.0           py36he6710b0_0  
qt                        5.6.2                         0  
readline                  6.2                           2  
resampy                   0.2.1                    pypi_0    pypi
scikit-learn              0.21.2           py36h627018c_0    conda-forge
scipy                     1.3.0                    pypi_0    pypi
send2trash                1.5.0                    py36_0  
setuptools                41.0.1                   py36_0  
sip                       4.18.1          py36hf484d3e_1000    conda-forge
six                       1.12.0                   py36_0  
sqlite                    3.13.0                        0  
tensorboard               1.13.1           py36hf484d3e_0  
tensorflow                1.13.1          mkl_py36h27d456a_0  
tensorflow-base           1.13.1          mkl_py36h7ce6ba3_0  
tensorflow-estimator      1.13.0                     py_0  
termcolor                 1.1.0                    py36_1  
terminado                 0.8.2                    py36_0  
testpath                  0.4.2                    py36_0  
tk                        8.5.18                        0  
tornado                   6.0.2            py36h7b6447c_0  
traitlets                 4.3.2                    py36_0  
wcwidth                   0.1.7                    py36_0  
webencodings              0.5.1                    py36_1  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py36_0  
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.3.1                he6710b0_3  
zlib                      1.2.11               h7b6447c_3  
```

**Comment by lostanlen** [comment] 2019-06-25 21:56
This is most likely a hiccups in the setup process of your environment, causing filesystem inconsistencies in audioread.

Unless you can provide a list of steps to reproduce the problem and narrow the problem down to librosa, i am going to close this issue. Right now, my recommendations to you are, first, to avoid mixing the system Python `/usr/bin/python` and Anaconda's Python, and second, to avoid mixing `pip install` with `conda install` in the same environment. One source of the problem could be that you `pip install`-ed `audioread` with system `pip` yet `pip install`-ed `librosa` with `conda`'s `pip`.

If another user encounters the exact same issue, let them reopen it.

**Closed by lostanlen** 2019-06-25 21:56 UTC
Labels: IO, Upstream/dependency bug

**Comment by Tao-Sun** [comment] 2019-07-31 18:35
I encounter the same problem. 

Librosa is installed from conda through
      conda install -c conda-forge librosa.

When reading a .wav file generated by a librosa installed not through conda, it always reports 'file not found' error.

**Comment by bmcfee** [comment] 2019-07-31 18:52
> Librosa is installed from conda through
> conda install -c conda-forge librosa.
> 
> When reading a .wav file generated by a librosa installed not through conda,

Sorry, but I don't understand what you mean.  If the wav file is valid, it shouldn't matter how it was generated.  If you have two different librosas installed (one through conda and one not), that could be a problem.

**Comment by Tao-Sun** [comment] 2019-07-31 19:09
The machine has two librosa installed by two users (conda version and other version). Is this a valid installation pattern? My conda version can not read .wav files generated by the other librosa, but it can read other downloaded .wav files.

**Comment by bmcfee** [comment] 2019-07-31 19:18
> The machine has two librosa installed by two users (conda version and other version). Is this a valid installation pattern?

That's fine, but if they're two users (and neither is root / administrator), then these should be totally independent python environments.  That is, one user should not have access to the other's environment.  At any rate, I don't think that's the problem you're having, and I suspect that your installation is fine.


> My conda version can not read .wav files generated by the other librosa, but it can read other downloaded .wav files

This sounds like the .wav file in question is corrupted.  Can anything load it?  If not, please open a new issue as that's unrelated to the (closed) issue for this thread.

**Comment by jmostrom013** [comment] 2021-04-30 19:44
Hi, I am getting this same problem as well, a file not found error. I tried installing in a conda environment using  `conda install -c conda-forge librosa`. I also made sure that `ffmpeg` is installed (4.3.1). Here's the full message:

```
/Users/janetmostrom/miniconda3/envs/torch/lib/python3.9/site-packages/librosa/core/audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/miniconda3/envs/torch/lib/python3.9/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    145     try:
--> 146         with sf.SoundFile(path) as sf_desc:
    147             sr_native = sf_desc.samplerate

~/miniconda3/envs/torch/lib/python3.9/site-packages/soundfile.py in __init__(self, file, mode, samplerate, channels, subtype, endian, format, closefd)
    628                                          format, subtype, endian)
--> 629         self._file = self._open(file, mode_int, closefd)
    630         if set(mode).issuperset('r+') and self.seekable():

~/miniconda3/envs/torch/lib/python3.9/site-packages/soundfile.py in _open(self, file, mode_int, closefd)
   1182             raise TypeError("Invalid file: {0!r}".format(self.name))
-> 1183         _error_check(_snd.sf_error(file_ptr),
   1184                      "Error opening {0!r}: ".format(self.name))

~/miniconda3/envs/torch/lib/python3.9/site-packages/soundfile.py in _error_check(err, prefix)
   1356         err_str = _snd.sf_error_number(err)
-> 1357         raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
   1358 

RuntimeError: Error opening '~/machine_learning_class/cats_dogs/train/dog/dog_barking_0.wav': System error.

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-4728a8f3fa65> in <module>
      7 train_dog_path = "~/machine_learning_class/cats_dogs/train/dog/"
      8 
----> 9 x, fs = librosa.load(train_dog_path+"dog_barking_0.wav")

~/miniconda3/envs/torch/lib/python3.9/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    161         if isinstance(path, (str, pathlib.PurePath)):
    162             warnings.warn("PySoundFile failed. Trying audioread instead.")
--> 163             y, sr_native = __audioread_load(path, offset, duration, dtype)
    164         else:
    165             raise (exc)

~/miniconda3/envs/torch/lib/python3.9/site-packages/librosa/core/audio.py in __audioread_load(path, offset, duration, dtype)
    185 
    186     y = []
--> 187     with audioread.audio_open(path) as input_file:
    188         sr_native = input_file.samplerate
    189         n_channels = input_file.channels

~/miniconda3/envs/torch/lib/python3.9/site-packages/audioread/__init__.py in audio_open(path, backends)
    109     for BackendClass in backends:
    110         try:
--> 111             return BackendClass(path)
    112         except DecodeError:
    113             pass

~/miniconda3/envs/torch/lib/python3.9/site-packages/audioread/rawread.py in __init__(self, filename)
     60     """
     61     def __init__(self, filename):
---> 62         self._fh = open(filename, 'rb')
     63 
     64         try:

FileNotFoundError: [Errno 2] No such file or directory: '~/machine_learning_class/cats_dogs/train/dog/dog_barking_0.wav'


```

**Comment by bmcfee** [comment] 2021-05-01 11:39
Are you sure that the file exists?

**Comment by happyTonakai** [comment] 2024-05-28 03:19
I have this issue as well. `os.path.exists` tells me that the file exists, and `soundfile.read` can read it properly but `librosa.load` cannot find it.
