### ISSUE TITLE
librosa.feature.stack_memory returns WRONG VALUES

### ISSUE THREAD

**Issue by beantowel** [librosa/librosa#1061] opened 2020-01-16 16:20 UTC
#### Description

Error when using `librosa.feature.stack_memory ` function, the returned array contains some values that doesn't exists in the input array, and the wrong result is random, the probability of failure increases with bigger `n_steps` parameter

#### Steps/Code to Reproduce

```python
import librosa
import numpy as np

# generate random array in range [0, 24)
x = np.remainder((np.random.random(10000)*100).astype(int), 24)
assert (x < 24).all(), f'this should not alarm'
stackedX = librosa.feature.stack_memory(
    x, n_steps=500, mode='constant')  # same error with mode type edge and reflect
print(f'{stackedX[stackedX >= 24]}')  # will print very big integers
assert (stackedX < 24).all(), f'this will alarm'

```

#### Expected Results

```
$ python test
(nothing happens)
```

#### Actual Results

```
$ python test
[2097163]
Traceback (most recent call last):
  File "testST.py", line 10, in <module>
    assert (stackedX < 24).all(), f'this will alarm'
AssertionError: this will alarm
```

#### Versions

```python
>>> import platform; print(platform.platform())
Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
>>> import sys; print("Python", sys.version)
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.0
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.7.2
>>> 
```

**Comment by bmcfee** [comment] 2020-01-16 17:12
I was not able to reproduce this behavior.  Both constant and edge padding work as expected on my machine:
```python
In [1]: import numpy as np                                                                    

In [2]: import librosa                                                                        
x = 
In [3]: x = np.remainder((np.random.random(10000)*100).astype(int), 24)                       

In [4]: x                                                                                     
Out[4]: array([14,  2,  6, ..., 23,  2, 14])

In [5]: x.max()                                                                               
Out[5]: 23

In [6]: x.min()                                                                               
Out[6]: 0

In [7]: sx = librosa.feature.stack_memory(x, n_steps=500, mode='constant')                    

In [8]: sx.shape                                                                              
Out[8]: (500, 10000)

In [9]: x                                                                                     
Out[9]: array([14,  2,  6, ..., 23,  2, 14])

In [10]: x.shape                                                                              
Out[10]: (10000,)

In [11]: sx.max()                                                                             
Out[11]: 23

In [12]: sx.min()                                                                             
Out[12]: 0
```

```python
In [13]: librosa.show_versions()                                                              
INSTALLED VERSIONS
------------------
python: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 20:28:53) 
[GCC 7.3.0]

librosa: 0.7.2

audioread: 2.1.8
numpy: 1.17.4
scipy: 1.3.0
sklearn: 0.21.2
joblib: 0.13.2
decorator: 4.4.0
six: 1.13.0
soundfile: 0.10.2
resampy: 0.2.2
numba: 0.44.1

numpydoc: 0.9.2
sphinx: 2.3.1
sphinx_rtd_theme: 0.4.2
sphinxcontrib.versioning: 2.2.1
sphinx-gallery: None
pytest: 3.10.1
pytest-mpl: None
pytest-cov: None
matplotlib: 3.1.1
presets: 0.1.3
```

Can you modify your example to remove randomness and use a smaller array?  My guess is that something is going awry with `np.pad` under the hood, so it would be helpful to have a smaller example that we can inspect directly.

**Comment by beantowel** [comment] 2020-01-17 03:28
Thank you for your reply! I removed the randomness in the following scripts, but i can't use smaller example beacause the code with bug doesn't produce same result every time, and the probability of failure seems to increase with both increased array length and `n_steps`.
```python
import librosa
import numpy as np

# generate random array in range [0, 24)
# x = np.remainder((np.random.random(100000)*100).astype(int), 24)
x = np.remainder(np.arange(100000), 24)
assert (x < 24).all(), f'this should not alarm'
stackedX = librosa.feature.stack_memory(
    x, n_steps=500, mode='constant')  # same error with mode type edge and reflect
print(f'{stackedX[stackedX >= 24]}')  # will print very big integers
assert (stackedX < 24).all(), f'this will alarm'
```

And this is two results:
```
$ python test.py
[2097163 2097175 2097159 2097157 2097158 2097157 2097156 2097154]
Traceback (most recent call last):
  File "testST.py", line 10, in <module>
    print(f'{stackedX[stackedX >= 24]}')  # will print very big integers
AssertionError: this will alarm

$ python test.py
[2097174 2097162 2097165 2097173 2097167 2097155 2097165 2097154 2097152
 2097160 2097167 2097172 2097170 2097162 2097170 2097168]
Traceback (most recent call last):
  File "testST.py", line 11, in <module>
    assert (stackedX < 24).all(), f'this will alarm'
AssertionError: this will alarm
```

**Comment by bmcfee** [comment] 2020-01-17 15:12
Thanks for the update.  I still cannot reproduce this behavior locally, and I tried with several `n_steps` values (5 up to 500).

Just out of curiosity, could you print the results of `x.dtype` and `stackedX.dtype`?

**Comment by beantowel** [comment] 2020-01-17 15:32
i added line 
```python
print(f'x:{x.dtype} sx:{stackedX.dtype}')
```
in the script, the result was:
```
$ python test.py
x:int64 sx:int64
[2097160 2097160 2097161 2097170 2097161 2097155 2097160 2097174 2097157
 2097152 2097168 2097160 2097170 2097161 2097161 2097155 2097161 2097159
 2097163 2097163 2097163 2097175 2097167 2097174 2097171 2097169 2097175
 2097165 2097160 2097161 2097158 2097162 2097171 2097162 2097174 2097157
 2097170 2097156 2097161 2097162 2097158 2097162 2097166 2097159 2097175
 2097160 2097175]
Traceback (most recent call last):
  File "testST.py", line 12, in <module>
    assert (stackedX < 24).all(), f'this will alarm'
AssertionError: this will alarm
```

**Comment by bmcfee** [comment] 2020-01-17 15:55
Ok, so it's definitely not an overflow error.  I wonder if you get the same result by calling `np.pad` directly? Like so:

```python
sx = np.pad(x, [(500, 0)], mode='constant', constant_values=0)
```

This is more or less what librosa is doing under the hood (coupled with a bunch of vstacks).  If the above fails, then the problem is internal to numpy.  If the direct pad call succeeds but librosa fails, then we'll need to dig a little deeper.

**Comment by beantowel** [comment] 2020-01-18 06:03
I tried this:
```python
import librosa
import numpy as np

# generate random array in range [0, 24)
# x = np.remainder((np.random.random(100000)*100).astype(int), 24)
x = np.remainder(np.arange(10000), 24)
assert (x < 24).all(), f'this should not alarm'

sx = np.pad(x, [(500, 0)], mode='constant', constant_values=0)
assert (sx < 24).all()
print('numpy test passed')

stackedX = librosa.feature.stack_memory(
    x, n_steps=500, mode='constant')  # same error with mode type edge and reflect
print(f'x:{x.dtype} sx:{stackedX.dtype}')
print(f'{stackedX[stackedX >= 24]}')  # will print very big integers
assert (stackedX < 24).all(), f'this will alarm'
```
and the bad news is:
```
$ python test.py
numpy test passed
x:int64 sx:int64
[2097159 2097156 2097173 2097162 2097164 2097173 2097162 2097172 2097159
 2097167 2097169 2097171 2097153 2097166 2097163 2097156 2097154 2097154
 2097152 2097172 2097163 2097171 2097175 2097167 2097159 2097152 2097162
 2097170 2097163 2097155 2097162 2097173 2097168 2097160 2097157 2097152
 2097172 2097174 2097166 2097152 2097165 2097154 2097158 2097164 2097174
 2097167 2097173]
Traceback (most recent call last):
  File "testST.py", line 17, in <module>
    assert (stackedX < 24).all(), f'this will alarm'
AssertionError: this will alarm

```

**Comment by beantowel** [comment] 2020-01-23 13:19
I digged into librosa's code and found the error happens in the  `librosa/feature/utils.py` line 246, i reproduced the error using the similar code in `librosa.feature.stack_memory`:
```python
import librosa
import numpy as np

data = np.remainder(np.arange(10000), 24)
n_steps = 300
assert (data < 24).all(), f'this should not alarm'


def testNumpy(data, n_steps=n_steps):
    n_steps, delay = n_steps, 1
    padding = (int((n_steps - 1) * delay), 0)
    data = np.atleast_2d(data)
    data = np.pad(data, [(0, 0), padding], mode='constant')
    history = data
    for i in range(1, n_steps):
        y = np.roll(data, -i * delay, axis=1)
        history = np.vstack([np.roll(data, -i * delay, axis=1), history])
        # history = np.vstack([y, history])
        print(f'i:{i} max history:{np.max(history)} max y:{np.max(y)}')


def testLibrosa(x, n_steps=n_steps):
    sx = np.pad(x, [(n_steps, 0)], mode='constant', constant_values=0)
    assert (sx < 24).all()
    print('numpy test passed')

    stackedX = librosa.feature.stack_memory(
        x, n_steps=n_steps, mode='constant')  # same error with mode type edge and reflect
    print(f'x:{x.dtype} sx:{stackedX.dtype}')
    print(f'{stackedX[stackedX >= 24]}')  # will print very big integers
    assert (stackedX < 24).all(), f'this will alarm'


print(f'data:{data.shape, data.dtype}')
testNumpy(data)
# testLibrosa(data)
```
this is the one of the output of the executions (same as before, the output is different every time):
```
$ python testST.py
data:((10000,), dtype('int64'))
i:1 max history:23 max y:23
i:2 max history:23 max y:23
i:3 max history:23 max y:23
(repeats..........)
i:220 max history:23 max y:23
i:221 max history:23 max y:23
i:222 max history:2097160 max y:23
i:223 max history:2097160 max y:23
i:224 max history:2097160 max y:23
(repeats.........)
```
And i found the max value of `y` is correct every time, if i replace the line `history = np.vstack([np.roll(data, -i * delay, axis=1), history])` with `history = np.vstack([y, history])`, i won't encounter the problem (at least within 10 times of executions i don't)

**Comment by bmcfee** [comment] 2020-01-23 13:25
Thanks for looking into it!  I'm still a bit perplexed here, not being able to replicate the error in any of my test environments.

I do wonder if rewriting the function to avoid iterative stacking (which is slow) and instead fill slices of a pre-allocated array might solve the problem.  I'll try to give it a spin over the next couple of days and get back to you here.

**Comment by bmcfee** [comment] 2020-01-23 17:48
I gave this a think over lunch, and I suggest that we just take this as an opportunity to rewrite this function more efficiently using numba, linking back to #157.  We have some precedent to go on here from #949 , as time-delay embedding is quite similar to shearing, and the existing `utils.__roll_dense` function could be a good starting point if anyone wants to take this on.

However, I'm still wary of flagging the original issue here as a librosa bug until we can get some independent confirmation of the behavior.

**Comment by bmcfee** [comment] 2020-03-04 15:07
Please don't mark issues closed until the fix has been merged. Thanks!

**Closed** 2020-03-07 16:00 UTC
Labels: bug
