### ISSUE TITLE
master chroma_cqt: n_fft=1024 is too small for input signal of length=864

### ISSUE THREAD

**Issue by turian** [librosa/librosa#1194] opened 2020-06-29 13:31 UTC
**Describe the bug**

I am testing this new PR https://github.com/librosa/librosa/pull/1183
on my short audio, 2.5s.

However, I get warning 

```
/usr/local/lib/python3.7/site-packages/librosa/core/spectrum.py:205: UserWarning: n_fft=1024 is too small for input signal of length=864
  warnings.warn('n_fft={} is too small for input signal of length={}'.format(n_fft, y.shape[-1]))
```

**To Reproduce**

Pull master.

import librosa

```
Z = []
x, sr = librosa.load("/Users/personal/Dropbox/tmp/1.mp3")
print(x.shape)
z = librosa.feature.chroma_cqt(x)
```

The shape is `(55296,)`

I can share the MP3 if you like.

**Expected behavior**

No warning

**Version**

```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.7 (default, Mar 10 2020, 15:43:03)
[Clang 11.0.0 (clang-1100.0.33.17)]
NumPy 1.18.5
SciPy 1.4.1
librosa 0.8.0-dev
INSTALLED VERSIONS
------------------
python: 3.7.7 (default, Mar 10 2020, 15:43:03)
[Clang 11.0.0 (clang-1100.0.33.17)]

librosa: 0.8.0-dev

audioread: 2.1.8
numpy: 1.18.5
scipy: 1.4.1
sklearn: 0.22.2.post1
joblib: 0.15.1
decorator: 4.3.0
soundfile: 0.10.2
resampy: 0.2.2
numba: 0.43.0

numpydoc: None
sphinx: 2.4.4
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.1
presets: None
```

**Additional context**

I did not get this error with pypi librosa 0.7.2

On master I don't get this error with `bins_per_octave=12`.

**Comment by bmcfee** [comment] 2020-06-29 13:44
This a warning, not an error, and I think this is entirely intended behavior.  Here's what's going on:

1. CQT uses adaptive window lengths to construct filters.  If you use a higher frequency resolution (bpo=36 instead of 12, for example), it will need longer windows.  The way to understand this is to think about how many cycles you need to observe before you can detect a difference between two frequencies; the closer those frequencies are, the more cycles you'll need (hence longer windows).
2. CQT does recursive downsampling of the input signal to efficiently compute the filter response at low frequencies.  Your input signal is ~2.5sec long, but after 5 downsamplings, it will be ~1/16 of a second long.  Depending on your CQT resolution, this may not be enough duration to capture the minimum frequency (C1).
3. CQT uses a separate STFT for each octave.  Per #1132 , if the signal is too short to do an stft, it throws an error (if left-aligned) or a warning (if centered, which CQT always is).

So, TLDR, the warning is there to tell you that the signal is too short to reliably analyze in the way that you're asking to.  Possible resolutions to this:

1. Raise your `fmin` parameter; C1 is probably lower than you need, but you'll know best based on your data.  C2 might be fine.
2. Use chroma_stft instead of cqt.  This will always use a fixed-length window that you can control directly.
3. Use VQT to pre-compute the spectrogram at the target resolution, and then pass that into chroma_cqt as the `C` parameter.  The difference here is that VQT tapers the window lengths at low frequencies so that they can't grow too large.  This improves time resolution but reduces frequency resolution for low frequencies, and that might be a reasonable trade-off for you.
4. Reduce the `bins_per_octave` parameter to `24` or `12`.  I don't really recommend this, as the resulting chroma will be pretty noisy.

**Comment by lostanlen** [comment] 2020-07-06 21:35
As @bmcfee explained, the best solution to this issue is to adjust the parameters according to your use case.
I suggest we close this now.

**Closed by lostanlen** 2020-07-06 21:35 UTC
Labels: discussion
