### ISSUE TITLE
About using time_stretch function

### ISSUE THREAD

**Issue by IcyGrain** [librosa/librosa#1081] opened 2020-03-05 05:05 UTC
How can I gradually change speed of a audio clip with time_stretch function?
like:
     gradually change bpm 120 to 140 in 20 seconds

**Comment by bmcfee** [comment] 2020-03-05 17:22
Probably not with time-stretch, but you could do it with the phase_vocoder function if you slice up columns of the STFT matrix into segments that you want to adjust by a constant rate.  However, the results won't sound all that great in general because our implementation of time-stretching is quite naive.

Instead, I recommend using the [rubberband](https://breakfastquay.com/rubberband/) tool which allows you to do variable-rate time stretching.

**Comment by lostanlen** [comment] 2020-03-07 01:38
closing as duplicate of #517

**Closed by lostanlen** 2020-03-07 01:38 UTC
Labels: question
