### ISSUE TITLE
Synthetic phase for inverse transforms

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#434] opened 2016-11-04 14:54 UTC
Would it be useful to have inverse transforms `istft`, `icqt` #165 synthesize phase when the input is magnitude spectra?  @dpwe's repsonse to #424 provides an example of how to do this for inverting MFCCs by transferring the phase of the corresponding forward transform of white noise.

I've test-driven this on my `icqt` prototype, and it sounds pretty good; much better than a magnitude-only reconstruction.

It's a bit of a nuisance to do this by hand since the parameters and duration need to be matched to the input signal.  It would be easy to do this from within the inverse transform though, since that information is all present.  I'm thinking an optional (defaulting to False) parameter.

Thoughts?

**Comment by dpwe** [comment] 2016-11-04 14:59
Sounds like a neat idea.

  DAn.

**Comment by jongwook** [comment] 2017-04-03 20:37
I'm using this implementation of Griffin-Lim algorithm, and the restored audio sounds perceivably better than random/from-white-noise initialization of phases.

```python
def griffinlim(spectrogram, n_iter = 100, window = 'hann', n_fft = 2048, hop_length = -1, verbose = False):
    if hop_length == -1:
        hop_length = n_fft // 4

    angles = np.exp(2j * np.pi * np.random.rand(*spectrogram.shape))

    t = tqdm(range(n_iter), ncols=100, mininterval=2.0, disable=not verbose)
    for i in t:
        full = np.abs(spectrogram).astype(np.complex) * angles
        inverse = librosa.istft(full, hop_length = hop_length, window = window)
        rebuilt = librosa.stft(inverse, n_fft = n_fft, hop_length = hop_length, window = window)
        angles = np.exp(1j * np.angle(rebuilt))

        if verbose:
            diff = np.abs(spectrogram) - np.abs(rebuilt)
            t.set_postfix(loss=np.linalg.norm(diff, 'fro'))

    full = np.abs(spectrogram).astype(np.complex) * angles
    inverse = librosa.istft(full, hop_length = hop_length, window = window)

    return inverse
```

Is it something to be avoided due to the slow speed? In that case, I think @Jonathan-LeRoux's algorithm would be a nice addition, although I found it hard to write it efficiently only using Python.

**Comment by stefan-balke** [comment] 2017-04-04 08:24
+1 for having Griffin-Lim + x (other phase reconstruction methods from magnitude spectrograms, e.g., https://ai2-s2-pdfs.s3.amazonaws.com/2042/3dffa92efd5371489e6b11b22779b0a2fc85.pdf)

**Comment by Jonathan-LeRoux** [comment] 2017-04-04 13:34
How timely! I have been in the process of preparing my old phase reconstruction C code for release.
The MEX version and accompanying Matlab script had been 95% ready for a year, and I finalized them last week, but I was considering preparing a Python wrapper before releasing the whole thing. I have never used C code in Python, and I was stopped in my tracks by the number of options. Any input on whether I should use ctypes, Cython, SWIG, or Python-C-Api? I'm looking for something easy and quick to code, and easy to use by the user.

**Comment by bmcfee** [comment] 2017-04-04 13:40
> Any input on whether I should use ctypes, Cython, SWIG, or Python-C-Api? I'm looking for something easy and quick to code, and easy to use by the user.

Cython is the go-to these days, and it's the easiest to package and ship in my experience.

**Comment by bmcfee** [comment] 2017-04-04 13:42
> Is it something to be avoided due to the slow speed?

Not necessarily -- the initial proposal here was for a generic phase reconstruction method that could apply both to i/stft and i/cqt.  I'm not sure GL would work on CQT, but it's worth a shot.

**Comment by Jonathan-LeRoux** [comment] 2017-04-06 15:45
Thanks Brian, I'll give Cython a try.

**Comment by diggerdu** [comment] 2017-04-15 13:23
I tried Griffin-Lim algorithm in Constant Q, the results is bad.

**Comment by lonce** [comment] 2017-04-16 02:26
Check this our for a fast-and-not-too-dirty reconstruction:
https://github.com/lonce/SPSI_Python
Works great as an initial phase estimate for Griffin-Lim, too.

**Comment by Jonathan-LeRoux** [comment] 2017-06-26 15:16
I uploaded my phase reconstruction code on Github and Pypi:
https://github.com/Jonathan-LeRoux/lws
The core is C/C++, with wrappers for both Python (via Cython) and Matlab (via Mex).

**Comment by carlthome** [comment] 2017-08-31 21:30
Curious, what use cases are there when the phase from the forward transform can't be kept around for doing the inverse? :astonished:

**Comment by bmcfee** [comment] 2017-08-31 21:33
> Curious, what use cases are there when the phase from the forward transform can't be kept around for doing the inverse?

The main one I have in mind is sonifying samples from a generative model of magnitude spectra.

**Comment by lostanlen** [comment] 2018-02-18 01:30
> The main one I have in mind is sonifying samples from a generative model of magnitude spectra.
Yes. This is even more difficult than inversion from CQT modulus because we have no guarantee that there exists a solution in the reproducing kernel Hilbert space (RKHS) associated to the CQT operator such that the modulus of the solution will yield the expected magnitude spectra.
BTW working on generative models in the time-frequency domain that would guarantee this RKHS property is AFAICT terra incognita in ML research ... but I digress.

**Comment by Pzoom522** [comment] 2018-02-21 14:21
It's also very welcomed if we can have inverse transform ```imel```

**Comment by deepanwayx** [comment] 2018-04-21 12:35
Hey @jongwook can you please provide a concrete example of how to use the Griffin-Lim function? I am using the following code and it is throwing a inconsistent shape error while multiplying spectrogram and angles.

`def griffinlim(spectrogram, n_iter = 100, window = 'hann', n_fft = 2048, hop_length = -1, verbose = False):
    
    if hop_length == -1:
        hop_length = n_fft // 4

    angles = np.exp(2j * np.pi * np.random.rand(*spectrogram.shape))

    t = tqdm(range(n_iter), ncols=100, mininterval=2.0, disable=not verbose)
    
    for i in t:
        
        print ('Iter:' , i , ', Spectrogram Shape:', spectrogram.shape)
        print ('Iter:' , i , ', Angles Shape:', angles.shape)

        full = np.abs(spectrogram).astype(np.complex) * angles
        inverse = librosa.istft(full, hop_length = hop_length, window = window)
        rebuilt = librosa.stft(inverse, n_fft = n_fft, hop_length = hop_length, window = window)
        angles = np.exp(1j * np.angle(rebuilt))

        if verbose:
            diff = np.abs(spectrogram) - np.abs(rebuilt)
            t.set_postfix(loss=np.linalg.norm(diff, 'fro'))

    full = np.abs(spectrogram).astype(np.complex) * angles
    inverse = librosa.istft(full, hop_length = hop_length, window = window)

    return inverse


y, sr = librosa.load('of6p3-xkgvy.wav')
    
mfccs = librosa.feature.mfcc(y)
back = griffinlim(mfccs)`

The error message is this
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-7ccbc35ccd09> in <module>()
----> 1 griffinlim(S.T)

<ipython-input-22-cb1ddb6bd5f1> in griffinlim(spectrogram, n_iter, window, n_fft, hop_length, verbose)
      7     t = tqdm(range(n_iter), ncols=100, mininterval=2.0, disable=not verbose)
      8     for i in t:
----> 9         full = np.abs(spectrogram).astype(np.complex) * angles
     10         inverse = librosa.istft(full, hop_length = hop_length, window = window)
     11         rebuilt = librosa.stft(inverse, n_fft = n_fft, hop_length = hop_length, window = window)

ValueError: operands could not be broadcast together with shapes (1292,128) (1025,128) `

**Comment by jongwook** [comment] 2018-04-24 00:54
@deepanwayx this is not a Q&A board, but it seems that you're passing a Mel spectrogram to the function, which is designed to deal with the usual STFT spectrograms. They have different default set of parameters, so the shapes are different.

Inverting a Mel spectrogram without any prior is ill-defined in general; you may try [Tacotron 2](https://arxiv.org/abs/1712.05884) for inverting Mel spectrograms of speech

**Comment by rafaelvalle** [comment] 2018-07-07 05:22
Sharing the link to support @bmcfee idea of "sonifying samples from a generative model of magnitude spectra.", or related transforms.
https://github.com/rafaelvalle/asrgen

**Comment by vinaykumar2491** [comment] 2018-10-22 11:57
> Curious, what use cases are there when the phase from the forward transform can't be kept around for doing the inverse?

I'm having this issue when doing Audio Source Separation. The input to my neural net is a magnitude STFT features of the mixture and the output is the magnitude STFT features of the separated source.

**Comment by lostanlen** [comment] 2018-10-23 19:03
@vinaykumar2491 read this message: https://github.com/librosa/librosa/issues/434#issuecomment-366485232

**Comment by jeremyworger** [comment] 2019-01-07 23:11
Has anyone implemented the "phase retrieval for wavelet transforms" in python?

**Comment by lostanlen** [comment] 2019-01-08 16:59
@jeremyworger not that I know of, but it would be of immense value.

**Comment by bmcfee** [comment] 2019-03-08 21:38
This thread's spiraled pretty far off from the original issue, but that's okay!

I've spent a decent amount of time this week hacking on various things in the space of spectrogram inversion using a slightly modified version of @jongwook's griffin-lim implementation.  Despite having better options for phase retrieval out there (mentioned above in this thread), I still think it would be good to have a reference GL to rely on.  With that in hand, we could easily provide (approximate) mfcc and mel inverters using pseudo-inverses; I have prototypes in local notebooks, and they sound not-perfect but not horrible either.

I'll create a new issue with a narrowed down checklist of deliverables to include in the 0.7 release.

**Comment by bmcfee** [comment] 2019-05-05 21:28
The recently merged #843 includes (fast) griffin-lim, which I think covers most of the content of this issue.  It does not (currently) support cqt phase retrieval, but we can add that later if there's demand.  Any objection to closing this out?

**Comment by lostanlen** [comment] 2019-05-05 22:24
yes, let's close this one. then we can release griffin-lim in the next stable version, collect some user feedback, and eventually open a CQT-related issue around that feedback.
amazing work @bmcfee !!!

**Closed by lostanlen** 2019-05-05 22:24 UTC
Labels: enhancement, functionality

**Comment by walidbou6** [comment] 2022-03-18 16:14
the Griffin-Lim method causes unnatural artifacts in synthetic speech.
