### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.decorators'

### ISSUE THREAD

**Issue by maxwellmckinnon** [librosa/librosa#1160] opened 2020-06-12 03:10 UTC
**Describe the bug**
`import librosa` breaks on latest librosa and numba. Upstream dependency break

librosa==0.7.2
numba==0.50.0

**To Reproduce**
```
import librosa
```

```
.tox/s-py38/lib/python3.8/site-packages/librosa/util/utils.py:15: in <module>
    from .decorators import deprecated
.tox/s-py38/lib/python3.8/site-packages/librosa/util/decorators.py:9: in <module>
    from numba.decorators import jit as optional_jit
E   ModuleNotFoundError: No module named 'numba.decorators'
```

**Comment by yemata** [comment] 2020-06-12 05:10
`pip install numba==0.48`
seems like `numba` removed the `decorators` module with version 0.50. real fix would be pinning `numba` version in librosa requirements

**Comment by lostanlen** [comment] 2020-06-12 10:47
Thank you @yemata 
Closing as duplicate of #1105, fixed by #1107 

@bmcfee i'm starting to think that it might be good to make an 0.7.3 release before 0.8.0
If not, everyone package requiring `librosa<0.8` will hit this installation bug.

**Closed** 2020-06-12 10:47 UTC
Labels: Upstream/dependency bug

**Comment by adarob** [comment] 2020-06-12 15:10
> Thank you @yemata
> Closing as duplicate of #1105, fixed by #1107
> 
> @bmcfee i'm starting to think that it might be good to make an 0.7.3 release before 0.8.0
> If not, everyone package requiring `librosa<0.8` will hit this installation bug.

+1

**Comment by orkenstein** [comment] 2020-06-15 08:21
> Thank you @yemata
> Closing as duplicate of #1105, fixed by #1107
> 
> @bmcfee i'm starting to think that it might be good to make an 0.7.3 release before 0.8.0
> If not, everyone package requiring `librosa<0.8` will hit this installation bug.

Please, do it ASAP. Hits really hard with automated daily builds.

**Comment by jonrosner** [comment] 2020-06-24 10:16
> `pip install numba==0.48`
> seems like `numba` removed the `decorators` module with version 0.50. real fix would be pinning `numba` version in librosa requirements

With python3.6 venv and librosa==0.7.2 and numba==0.48 I get an Assertion Error upon importing librosa.

```python
.../venv_36/lib/python3.6/site-packages/numba/targets/cpu.py in <module>
     12 from numba import utils, cgutils, types
     13 from numba.utils import cached_property
---> 14 from numba.targets import (
     15     callconv, codegen, externals, intrinsics, listobj, setobj, dictimpl,
     16 )

.../venv_36/lib/python3.6/site-packages/numba/targets/listobj.py in <module>
   1069 
   1070 @overload_method(types.List, "sort")
-> 1071 def ol_list_sort(lst, key=None, reverse=False):
   1072 
   1073     _sort_check_key(key)

.../venv_36/lib/python3.6/site-packages/numba/core/extending.py in decorate(overload_func)

.../venv_36/lib/python3.6/site-packages/numba/core/typing/templates.py in make_overload_method_template(typ, attr, overload_func, inline)

.../venv_36/lib/python3.6/site-packages/numba/core/typing/templates.py in make_overload_attribute_template(typ, attr, overload_func, inline, base)

AssertionError: 
```

**Comment by bmcfee** [comment] 2020-06-24 11:24
> With python3.6 venv and librosa==0.7.2 and numba==0.48 I get an Assertion Error upon importing librosa.

That looks like an assertion error upon importing numba.  Are you able to import numba on its own?

**Comment by dangvansam98** [comment] 2020-07-02 04:14
> > `pip install numba==0.48`
> > seems like `numba` removed the `decorators` module with version 0.50. real fix would be pinning `numba` version in librosa requirements
> 
> With python3.6 venv and librosa==0.7.2 and numba==0.48 I get an Assertion Error upon importing librosa.
> 
> ```python
> .../venv_36/lib/python3.6/site-packages/numba/targets/cpu.py in <module>
>      12 from numba import utils, cgutils, types
>      13 from numba.utils import cached_property
> ---> 14 from numba.targets import (
>      15     callconv, codegen, externals, intrinsics, listobj, setobj, dictimpl,
>      16 )
> 
> .../venv_36/lib/python3.6/site-packages/numba/targets/listobj.py in <module>
>    1069 
>    1070 @overload_method(types.List, "sort")
> -> 1071 def ol_list_sort(lst, key=None, reverse=False):
>    1072 
>    1073     _sort_check_key(key)
> 
> .../venv_36/lib/python3.6/site-packages/numba/core/extending.py in decorate(overload_func)
> 
> .../venv_36/lib/python3.6/site-packages/numba/core/typing/templates.py in make_overload_method_template(typ, attr, overload_func, inline)
> 
> .../venv_36/lib/python3.6/site-packages/numba/core/typing/templates.py in make_overload_attribute_template(typ, attr, overload_func, inline, base)
> 
> AssertionError: 
> ```

I fix that by install numba 0.45.0, librosa 0.7.2

**Comment by waffletower** [comment] 2020-07-03 09:34
I am sorry, but we don't have to waste time as often on careless breakage exactly like this in other ecosystems such Java, Erlang or Swift in my direct and broad experience.  My do so many tolerate python amateur hour?  Why don't python developers understand the concept of pinning and downstream consequences?  The amount of time wasted for countless developers is staggering.

**Comment by bmcfee** [comment] 2020-07-03 12:10
@waffletower if you want to complain about python devs not adhering to semantic versioning practices, go right ahead.  But please do it elsewhere.  Comments like yours here will not be tolerated in this forum.

**Comment by maxwellmckinnon** [comment] 2020-07-06 16:30
@waffletower 

Definitely users should **always pin for robust production**. I'm with you there. If you notice the original post and comments, folks are reporting routine breaks in testing, not complaining about blocking breaks in production. 

Many people who are breaking in production are googling and finding this though, so I appreciate your commentary calling out the awfully bad practice of not pinning production.

Everyone is unique in where they are at in their journey. You know you shot yourself in the foot with dependency pinning when you first started. Python doesn't exactly have great design, standardization, or documentation around pip, deployment and "one good way to do things". Any ideas on how to improve the ecosystem to make it simpler and easier, apart from getting the word out to pin production?

**Comment by phamdanglam** [comment] 2020-09-12 20:27
conda install numba==0.48
conda install librosa==0.6.3

--> solution: install numba firstly

**Comment by pratikshaya** [comment] 2020-11-12 00:52
This bug is occur when you have librosa version less than 0.8. First install numba of any version then after install librosa if you want to install librosa less than 0.8.

**Comment by loretoparisi** [comment] 2022-05-04 13:20
> 0.7.2

I have used as you suggested

```
pip install librosa==0.7.2
pip install numba==0.45.0
```

but I'm getting now

```
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/__init__.py", line 47, in <module>
    import numba.typed
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/typed/__init__.py", line 3, in <module>
    from .typeddict import Dict
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/typed/typeddict.py", line 18, in <module>
    @njit
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/decorators.py", line 239, in njit
    return jit(*args, **kws)
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/decorators.py", line 176, in jit
    return wrapper(pyfunc)
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/decorators.py", line 192, in wrapper
    **dispatcher_args)
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/dispatcher.py", line 650, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/targets/registry.py", line 50, in target_context
    return self._toplevel_target_context
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/utils.py", line 390, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/targets/registry.py", line 34, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/targets/base.py", line 250, in __init__
    self.init()
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/targets/cpu.py", line 51, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/targets/codegen.py", line 612, in __init__
    self._init(self._llvm_module)
  File "/usr/local/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.14-x86_64.egg/numba/targets/codegen.py", line 621, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'
```

I have then tried 

```
pip install -U llvmlite==0.32.1
```

as suggested [here](https://github.com/rapidsai/cuml/issues/2389) but no look so far!

**Comment by ovuruska** [comment] 2022-06-22 17:08
Got the same error.
Solved it with
`pip uninstall --yes librosa
pip install librosa --force-reinstall`

**Comment by arashhmt90** [comment] 2022-09-03 14:46
Your python version should be 3.8.

**Comment by luziyi1998** [comment] 2022-09-25 06:48
> 得到同样的错误。 用 ` pip uninstall --yes librosa解决了它
> 
> pip install librosa --force-reinstall `

it works! thank u

**Comment by Forence1999** [comment] 2022-09-28 15:02
The problem is that I cannot install numba==0.48 for my M1 Macbook. Is there a more general solution? Please

**Comment by Forence1999** [comment] 2022-09-28 15:12
> The problem is that I cannot install numba==0.48 for my M1 Macbook. Is there a more general solution? Please

Solved this problem by commenting the line "from numba.decorators import jit as optional_jit" in the file "librosa/util/decorators.py".

Configuration:
    librosa = 0.7.2
    numba = 0.56.2 



librosa/util/decorators.py

**Comment by Forence1999** [comment] 2022-09-30 09:07
> I would strongly advise you to upgrade your librosa to the most recent stable (0.9.2) rather than hack code out of the release from 3 years ago.

Thank you so much for your kind reminder, @bmcfee! I don't even notice that librosa has been updated to 0.9.2, because conda installs the 0.7.2 version automatically for me. I tried 0.9.2 just now and everything ran smoothly. Thanks, @bmcfee !

**Comment by nehat005** [comment] 2022-10-25 08:35
> Got the same error. Solved it with ` pip uninstall --yes librosa
> 
> pip install librosa --force-reinstall `

This works! Thank you!

**Comment by SebinLee** [comment] 2023-07-27 12:33
> Got the same error. Solved it with ` pip uninstall --yes librosa
> 
> pip install librosa --force-reinstall `

Great solution!! Thank you so much!!

**Comment by lurongkang123** [comment] 2024-05-30 07:35
> I would strongly advise you to upgrade your librosa to the most recent stable (0.9.2) rather than hack code out of the release from 3 years ago.

thank you, this is a viable plan

**Comment by WachasWps** [comment] 2024-12-25 23:07
ollecting numba==0.48
  Using cached numba-0.48.0.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... done
Collecting llvmlite<0.32.0,>=0.31.0dev0 (from numba==0.48)
  Using cached llvmlite-0.31.0.tar.gz (110 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.10/dist-packages (from numba==0.48) (1.26.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from numba==0.48) (75.1.0)
Building wheels for collected packages: numba, llvmlite
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for numba (setup.py) ... error
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build numba llvmlite
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numba, llvmlite)
