### ISSUE TITLE
Display axis decorators: seconds, ms

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#737] opened 2018-06-28 05:18 UTC
#### Description

We currently support two temporal decoration modes: `time` and `lag`.  These modes use seconds as the underlying data representation, and the `TimeFormatter` object adaptively scales the units to an appropriate resolution given the display range.

It would be good to be able to override this, and display in fixed units.  This could be easily done by adding a couple of new modes:

- `seconds`: always use seconds
- `ms`: always use milliseconds
- `lag_seconds`: always use seconds (including negative for lag)
- `lag_ms`: as above, but for milliseconds.

Implementing this is simply a matter of adding some control logic to the `TimeFormatter`, and adjusting the automatic axis labels to `Time (s)` or `Time (ms)` accordingly.

**Comment by kyungyunlee** [comment] 2018-08-05 02:10
Hi, first time contributing and would love to help when I can!
Could I try this, since it's "for beginners"? 😄 

I have 2 suggestions/questions at this point (if no one has been working on this ...)
1. Currently, the default is to perform adaptive time scaling with no lag. 
In order to keep this default working as it is, I am thinking of keeping the existing parameter, `lag=False`, and adding `unit=None`. 
The default value `unit=None` will scale time adaptively, but when given `'seconds'` or` 'ms'`,  we can display the value without any time scaling modifications. 

2. In case of  displaying in `seconds` and `ms`, how many digits should we limit the display to show? 
3-4 digits seem to look ok. (ex. `{:.4g}`)

Thanks!

**Comment by lostanlen** [comment] 2018-08-05 11:56
Hello @kyungyunlee, welcome to librosa. It's good to hear that you want to fix this issue.

I think that your idea of introducing a `unit` kwarg defaulting to `None` is good. It is backwards compatible AFAICT and avoids the combinatorial explosion of having to parse six different values of `lag`. I'd be curious to hear the opinion of other contributors, but I think that you may start with implementing your proposal as-is, and we'll review from there.

1. One thing that comes to mind is that `ms` is an abbreviation whereas `seconds` is spelled in full. It might be good to allow `s` as a synonym of `seconds` and `milliseconds` as a synonym of `ms`. This is not what @bmcfee asked for initially, but I think that in this case it does not hurt to relax the API a little bit, and allow both abbreviated and full denominations of time unit.

2. IIUC, at the moment there are two digits of precision when the audio is shorter than one minute, and zero digits otherwise. This `TimeFormatter` object inherits from `matplotlib.ticker.Formatter`, so the main application is to display time on the x-axis. I personally tend to have a strong preference for integer-valued ticks: they are very simple to understand and do not clutter the axis. Therefore, I would be in favor of keeping zero digits of precision. If the user needs more digits, it's preferable to change the units (e.g. from s to ms) than to increase rounding precision IMO. Why would you advocate for 3-4 digits? It's true that audio editing softwares like Audacity usually round time units down to the millisecond, so that's three digits of precision, or that MIR papers report parameters down to `1e-4` seconds (e.g. a window size of `23.2 ms`), but here the use case is different, I think.

**Comment by bmcfee** [comment] 2018-08-05 12:39
Thanks @kyungyunlee for taking this on, and @lostanlen for comments!

Some more comments:



> Currently, the default is to perform adaptive time scaling with no lag.
> In order to keep this default working as it is, I am thinking of keeping the existing parameter, lag=False, and adding unit=None.
> The default value unit=None will scale time adaptively, but when given 'seconds' or'ms', we can display the value without any time scaling modifications.

I think the term `lag` is overloaded here.  Are you using it to refer to a time offset?  In `specshow`, we use `lag` somewhat differently, to denote relative time due to skewing a self-similarity matrix.  (See https://librosa.github.io/librosa/generated/librosa.segment.recurrence_to_lag.html )  If you want to plot time with a built-in offset, you can currently do it with `x_coords`, though I agree this is inelegant.  For now, I'd say leave offset out of this PR, since it's independent of axis decoration.

I'm not 100% sold on splitting the functionality into extra parameters (`units=`).  I see where you're coming from, but it would get awkward if you're dealing with multiple time axes (eg in a self-similarity matrix) where you may want to decorate each one differently.  In the API I proposed, you can do `x_axis='time', y_axis='lag_ms'` (for example), but this would not be possible if the units parameter is factored out.

It does make total sense to add a units parameter to the `TimeFormatter` class though, since you would have a separate one for each axis.



> In case of displaying in seconds and ms, how many digits should we limit the display to show?
> 3-4 digits seem to look ok. (ex. {:.4g})

I think the simplest thing to do first is to keep `TimeFormatter`'s precision logic exactly the same, and just use a `units=` parameter to override the scale inference.  If we get that working, and don't like how it looks, then we can get into adapting the precision formatting.

Does that all make sense?

**Comment by kyungyunlee** [comment] 2018-08-06 01:52
Thanks for the comments @lostanlen @bmcfee !

I will attempt to reply to all comments at once to organize.

> I think the term lag is overloaded here. Are you using it to refer to a time offset? In specshow, we use lag somewhat differently, to denote relative time due to skewing a self-similarity matrix. (See https://librosa.github.io/librosa/generated/librosa.segment.recurrence_to_lag.html ) If you want to plot time with a built-in offset, you can currently do it with x_coords, though I agree this is inelegant. For now, I'd say leave offset out of this PR, since it's independent of axis decoration.

>It does make total sense to add a units parameter to the TimeFormatter class though, since you would have a separate one for each axis.

Sorry about the unclear explanation. I actually meant to add `units=` to the TimeFormatter class. I think it makes sense to add `seconds, ms, lag_seconds, ms` to the "Time types" for x_axis and y_axis parameters of specshow() function and add `units` parameter to the TimeFormatter class. We are keeping the existing `time, lag` options, if I am correct? 


This brings to the next comment mentioned below :  

> One thing that comes to mind is that ms is an abbreviation whereas seconds is spelled in full. It might be good to allow s as a synonym of seconds and milliseconds as a synonym of ms. This is not what @bmcfee asked for initially, but I think that in this case it does not hurt to relax the API a little bit, and allow both abbreviated and full denominations of time unit.

I guess we should to do either 
1. `seconds, milliseconds, lag_seconds, lag_milliseconds`
2. `s, ms, lag_s, lag_ms`
3. Combine both 


> 2. In case of displaying in seconds and ms, how many digits should we limit the display to show?
3-4 digits seem to look ok. (ex. {:.4g})

I think I confused everyone here 😖
I was specifically thinking about a situation when someone uses a very large time range (ex. 10000) with a fixed unit of either seconds or milliseconds. Just concerned about whether it would appear cluttered or not, so I thought of displaying such large numbers as `1e+04`, for instance.
I will keep the existing scale inference method, if time unit is unspecified.

**Comment by lostanlen** [comment] 2018-08-06 02:58
> I was specifically thinking about a situation when someone uses a very large time range (ex. 10000) with a fixed unit of either seconds or milliseconds. 
My bad. I misread your `{:4g}` as a `{:.4f}`. Clearly I don't speak printf well enough :/ 
Your comment makes a lot more sense to me now.

> I guess we should to do either
> 1.  seconds, milliseconds, lag_seconds, lag_milliseconds
> 2.  s, ms, lag_s, lag_ms
> 3.  Combine both
Hm. Combining both seems like a lot of possible values to handle and document now (2x2x2=8). There's a tradeoff between simplicity and flexibility here.

**Comment by bmcfee** [comment] 2018-08-06 12:56
> Sorry about the unclear explanation. I actually meant to add units= to the TimeFormatter class. I think it makes sense to add seconds, ms, lag_seconds, ms to the "Time types" for x_axis and y_axis parameters of specshow() function and add units parameter to the TimeFormatter class. We are keeping the existing time, lag options, if I am correct?

Oh, great.  We're all on the same page then! :+1: 


> I guess we should to do either

My vote would be for option 2 (SI unit abbreviations and all), but I'm okay with having some redundancy here for long-form names as well.



> I was specifically thinking about a situation when someone uses a very large time range (ex. 10000) with a fixed unit of either seconds or milliseconds. Just concerned about whether it would appear cluttered or not, so I thought of displaying such large numbers as 1e+04, for instance.
> I will keep the existing scale inference method, if time unit is unspecified.

Yup.  We presently use `{:.2g}` (two decimal places with automatic scientific notation). 4 seems like a bit much to me, but I guess it would help to have some examples to look at once everything's in place.  I guess we could also make that configurable by the user, but let's not worry about it yet.

**Comment by kyungyunlee** [comment] 2018-08-07 01:25
Ok! I will go with option 2 for now and plot some examples by tmr!!

**Comment by kyungyunlee** [comment] 2018-08-08 00:37
I tried some examples. 
[https://gist.github.com/kyungyunlee/463c62a91bdc175fc45d1d48fde16725](https://gist.github.com/kyungyunlee/463c62a91bdc175fc45d1d48fde16725)

Things look fine as long as users do not use large numbers, when specifying units. 
I think using 3 digits for displaying in `s (seconds)` is not a bad choice (can be seen with the tempogram example) , since `seconds` are commonly used for time ranges of few minutes (ex. songs).

**Comment by lostanlen** [comment] 2018-08-08 02:36
Yes, 3 digits looks good. 999 seconds is ~16 minutes, which will cover the overwhelming majority of use cases.
I work in bioacoustics, where we may have 4-digit and even 5-digit audio recordings (up to 24 hour long), but typically I would use the adaptive format rather than the `seconds` format to display those recordings.

**Comment by bmcfee** [comment] 2018-08-08 03:57
Thanks @kyungyunlee, this looks great!

I agree that we probably want at least `'{.3g}'`, and not `2g` as is currently done.  I agree with @lostanlen that 999s is a reasonable upper bound, but it's also worth considering how it looks on very small ranges (eg when plotting samples in a waveform).  I guess `3g` also works well for reasonable ranges there, but it's worth testing that before locking into a decision.

**Comment by kyungyunlee** [comment] 2018-08-08 14:44
Yes, 3-digit seems reasonable at this point. 

But I did not quite get 

>  but it's also worth considering how it looks on very small ranges (eg when plotting samples in a waveform)

Is this referring to the `waveplot` function? 
If so, I made a quick plot (plotting as little as 22 samples (~1 ms)) and added to the gist page at the bottom. 
[https://gist.github.com/kyungyunlee/463c62a91bdc175fc45d1d48fde16725](https://gist.github.com/kyungyunlee/463c62a91bdc175fc45d1d48fde16725)


By the way in `waveplot` function, there are 2 parameters,  `x_axis` and `offset`, which are related to time units. 
If  user specifies `x_axis='ms'`, are we going to assume that when `offset` value is given, it is in the `ms` unit as well?

Thanks!

**Comment by bmcfee** [comment] 2018-08-08 14:57
> Is this referring to the waveplot function?

Yeah, or if we ever implement #676 for sample (not amplitude envelope) plotting, it would apply there as well.  Mostly I'm thinking more about interactive plotting and what happens if the user zooms in on a very small region.  It's not a huge deal, I just want to make sure we consider it.



> If user specifies x_axis='ms', are we going to assume that when offset value is given, it is in the ms unit as well?

Oh, great question.  I hadn't considered this, but I think that it will be simplest to always have offset specified in seconds.  It's not currently documented as such, but we should fix that.

**Comment by lostanlen** [comment] 2018-08-10 11:57
Looks great!

> In case of implementing the referenced issue, maybe adding milliseconds to the automatic time inference scaling could help (since 0.025 ms is easier to understand than 2.5e-05 s, at least for me), unless the user specifies the time unit.
Yes, that would be really useful. If the signal is shorter than one second, printing the time axis in milliseconds would be good.

Your ten-sample signal is so short in physical time that the most appropriate SI unit might actually be ... microseconds (μs). That said, I'm not sure if we want to go down the route of SI prefixes. Microseconds are very rare in the audio processing literature, except for what's related to electrical circuits and real-time computer music, but these topics are largely out of scope for librosa. In addition, microseconds carry a Greek letter in their prefix (μ), which is non-ASCII and therefore hard to reach for many users.

Thoughts?


> If user specifies x_axis='ms', are we going to assume that when offset value is given, it is in the ms unit as well?
I would prefer keeping the offset in seconds whatever be the x-axis unit.

**Comment by bmcfee** [comment] 2018-08-10 14:17
> In case of implementing the referenced issue, maybe adding milliseconds to the automatic time inference scaling could help (since 0.025 ms is easier to understand than 2.5e-05 s, at least for me), unless the user specifies the time unit.

I agree, that would be useful to have.





> That said, I'm not sure if we want to go down the route of SI prefixes. Microseconds are very rare in the audio processing literature, except for what's related to electrical circuits and real-time computer music, but these topics are largely out of scope for librosa. In addition, microseconds carry a Greek letter in their prefix (μ), which is non-ASCII and therefore hard to reach for many users.

I also agree with this.  If we really wanted full SI support, we could use [pint](https://pint.readthedocs.io/en/latest/index.html), but I don't think we need or want anything that sophisticated.



> I would prefer keeping the offset in seconds whatever be the x-axis unit.

Agreed.  Overloading the units on input data should be avoided whenever possible.  



> Is fixing the offset parameter description (under the waveplot function)
> Horizontal offset (in time) to start the waveform plot to Horizontal offset (in seconds) to start the waveform plot sufficient?

I like that solution.

**Comment by kyungyunlee** [comment] 2018-08-11 14:49
Yeah I agree, it's true that plotting such a few samples is not common. 
And I might take my word back....just keeping the minimum unit to `s`, not `ms` as I suggested, seems to be better for now, because `TimeFormatter` class is used in `specshow` and `waveplot` as well. 
I tried using `ms` for plotting under 1 second spectrogram (shown below),  but it looks like keeping `s` is better here. 

![image](https://user-images.githubusercontent.com/19829532/43992782-66388a7c-9dbe-11e8-9d9e-6c8240aaee94.png)

![image](https://user-images.githubusercontent.com/19829532/43992788-8352cd84-9dbe-11e8-81f4-ddce57b4a0b4.png)

I agree that sticking to seconds as much as possible and keeping things not too complicated is the way to go. 

When the referenced "sample plotting" function is implemented, we can consider adding `ms` as the minimum unit only for that sample plotting function but probably not `specshow`. 

Beside this problem, I think most things are clear. Any other thoughts?  :)

**Comment by bmcfee** [comment] 2018-08-13 14:02
> I agree that sticking to seconds as much as possible and keeping things not too complicated is the way to go.

This sounds good to me.



> When the referenced "sample plotting" function is implemented, we can consider adding ms as the minimum unit only for that sample plotting function but probably not specshow.

I'd prefer things to be consistent across the board, but we can always generalize later on if we decide it's necessary.





> Beside this problem, I think most things are clear. Any other thoughts? :)

Nope, i think we're good to get cracking on this!

**Closed** 2018-08-30 23:46 UTC
Labels: API change, enhancement, functionality, good for beginners

**Comment by lostanlen** [comment] 2020-02-27 06:16
I am looking at this again in the context of bioacoustics (signals which are multiple hours long and hop lengths of the order of 10-60 seconds).
The pretty-print works as intended (hh:mm:ss) but it's a bit annoying that the default xticks are expressed every 1000 seconds, rather than, say, every 900 seconds (15 minutes).
There's a simple workaround, of course, which is to define your own xticks after the fact; but perhaps this should be the default in librosa?

**Comment by lostanlen** [comment] 2020-02-27 06:17
example with the PCEN-gram of a file that is 2 hours and 40 minutes long

![Screen Shot 2020-02-27 at 1 16 06 AM](https://user-images.githubusercontent.com/3943142/75417347-c8adeb00-58fe-11ea-8729-64294592b3da.png)

**Comment by bmcfee** [comment] 2020-02-28 20:09
> The pretty-print works as intended (hh:mm:ss) but it's a bit annoying that the default xticks are expressed every 1000 seconds, rather than, say, every 900 seconds (15 minutes).

That's a great point; I'd advocate moving to either 900 or 1200; slight preference for the latter for [reasons](http://www.dozenal.org/).

This is an easy enough change to make if we add that multiple into the call to `MaxNLocator`: https://github.com/librosa/librosa/blob/f54cc970e6089b3d1254cdb430a8747e5e68a940/librosa/display.py#L885-L889
