### ISSUE TITLE
Librosa + Numpy 1.22

### ISSUE THREAD

**Issue by nyckmaia** [librosa/librosa#1468] opened 2022-03-26 15:15 UTC
I would like to create a python script that uses both "librosa" and "essentia" Python packages.

The problem is that: the Essentia package requires numpy `v1.22` and librosa requires numpy `v1.21` or lesser!

First I installed the Essentia package.
When I install the librosa, the pip installer process automatic removes the numpy `1.22` and replace it to the old version `1.21`.
Finally, librosa works good, but I got a broken Essentia that I'am not able to import in my Python script.

**The import error is that:**
`Unable to import Numpy C API from Essentia module. Error code = -1`

**So, how can I be able to get these two packages working together in the same kernel and in the same Python script?**

**Obs.:** The "essentia" package was installed in my computer using HomeBrew, because the "essentia" package cannot be installed via "pip3" on Mac OSX.

My System:
- OS: Mac OSX 10.15 Catalina
- Python Kernel: 3.9

**Comment by bmcfee** [comment] 2022-03-26 15:26
> librosa requires numpy `v1.21` or lesser!

This is not correct.  Librosa requires numpy >= 1.17, and there is at present no upper limit on the supported version:

https://github.com/librosa/librosa/blob/a464b336c23a94e00943fc50e936180f503367eb/setup.cfg#L42-L47

If there's a version conflict, it's probably coming from some other upstream dependency.

I'm reluctant to bump the minimum supported numpy version here because 1.22 drops python 3.7 support, which we decided to keep for another year or so after polling our users.

It also looks like essentia does not require numpy 1.22:
https://github.com/MTG/essentia/blob/aedf5958ee748c7e9368ff63b70f9e992fccd5fd/setup.py#L106

**Comment by nyckmaia** [comment] 2022-03-27 03:25
@bmcfee sorry! My mistake!

**The real problem is that:**
I create a new Python script that contains just a single line:

`import librosa`

So I got this error:
`ImportError: Numba needs Numpy 1.21 or less`

My Python Kernel contains NumPy 1.22 because this version is automatic installed by Homebrew as a `Essentia` package dependency

How can I import `librosa` in this case?

Obs.: I installed librosa using: `pip3 install librosa`.
I don't manually installed any other dependency as `Numba`. 

Why librosa is asking about `Numba`?

**Comment by bmcfee** [comment] 2022-03-27 13:19
Numba is a dependency for librosa, so that makes sense. As I said previously, librosa does not specify a maximum numpy version, but its dependencies might.

It sounds like the problem is that the essentia homebrew package is incorrectly specifying the numpy version.

My general recommendation here is to not mix package managers (ie homebrew and pip). You're probably better off using conda, which will be able to resolve versions across all packages.

**Comment by nyckmaia** [comment] 2022-03-27 19:12
Thank you @bmcfee

Now I created a new issue about it on the `Essentia` package github.

Please, be free to add any informations to help Essentia devs to fix this **numpy version conflict.**

**Issue link:**
https://github.com/MTG/essentia/issues/1244

Obs.: At this moment I'm not able to install Essentia package through any other way. **It must be done using Homebrew.**
You can see it on Essentia installing documentation for Mac OSX.

https://essentia.upf.edu/installing.html

I will let this Librosa issue opened here to be able to help other devs that want to use Librosa + Essentia packages on Mac OSX, ok?

Thanks,

**Comment by bmcfee** [comment] 2022-03-27 19:21
I'll close this out since there's nothing to be done from the librosa side.

**Closed by bmcfee** 2022-03-27 19:21 UTC
Labels: question
